### ISSUE TITLE
Discussion: Contract status

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/infrastructure#1]
## The issue

'Contract Status' is one of the [Infrastructure Data Standard Elements](http://infrastructuretransparency.org/resource/guidance-note-6-designing-a-disclosure-process/). 

The draft 'guidance note 9' states that values for this should:

> Select from pre-award, active or closed

However, these categories do not map to OCDS categories. In OCDS, we have status values for [tender](http://standard.open-contracting.org/latest/en/schema/codelists/#tender-status), [award](http://standard.open-contracting.org/latest/en/schema/codelists/#award-status) and [contract](http://standard.open-contracting.org/latest/en/schema/codelists/#contract-status)

## Considerations
In suggesting how this should be populated, when mapping from OCDS data to Project Level Data, we could suggest either:

* Use the most recent of tender, award or contract status, and express as '{stage}.{status}'

For example, if the most recent OCDS release included `award.status` = 'pending', then in project level data, `contractingProcess.status` would be 'award.pending'

* Use the latest stage indicated by the `release.tag` (or contents) of the most recent release

E.g. if the latest release contains `release.tag` = ['tender','award','awardUpdate'] then `contractingProcess.status` would be 'award'.

The suggested codelist for `contractingProcess.status` would be 

* planning
* tender
* award
* contract
* implementation
* cancelled
* completion

Mapping to this would require some logic when OCDS data is imported. 

## Proposal

The ``contractingProcess.status`` field should have a codelist consisting of:

* planning
* tender
* award
* contract
* implementation
* cancelled
* completion

No detailed definition of these codes should be provided.

The mapping from IDS "Contract status" should be written as:

> Contracting Process: publish as  ``contractingProcesses.status`` using the processStatus codelist

In guidance on converting from OCDS to Project Level Data Specification data we should provide examples of possible logic that could be applied to map to this field.

**Comment by jpmckinney** [comment]
The simplest reading of 'Select from pre-award, active or closed' is that 'Contract Status' (however it's named in the schema) should be a three-value closed codelist of 'preAward', 'active' and 'closed' (camel-casing to be consistent with OCDS code style).

Could you expand the proposal to explain the rationale of departing from the codelist expressed in the draft guidance note 9, which presumably chose those three values for valid reasons?

**Comment by jpmckinney** [comment]
> No detailed definition of these codes should be provided.

If a code is not described, then it is meaningless i.e. entirely open to the interpretation of the data publisher, which renders the data somewhat useless to users. Some description should be provided even if it is challenging to author.

If the three codes from guidance note 9 aren't used, then, for context to the discussion, the status codelists in OCDS are closed and contain:

tenderStatus.csv | awardStatus.csv | contractStatus.csv | proposal
- | - | - | -
planning | | | planning
planned | | | 
 | pending | pending | 
active | active | active | 
 | | | tender
 | | | award
 | | | contract
cancelled | cancelled | cancelled | cancelled
unsuccessful | unsuccessful | | 
complete | | | 
withdrawn | | | 
 | | terminated | 
 | | | implementation
 | | | completion

**Comment by timgdavies** [comment]
> Could you expand the proposal to explain the departure from the codelist expressed in the draft guidance note 9, which presumably chose those three values for valid reasons?

The discussions we've had suggest that Guidance Note 9 remained unpublished because many fields did not have worked up reasons for their suggested codelists. I've generally presumed that GN9 is informative, but that it has been built from the assumption of manual data entry. In context of OCDS data, we may have more detail available. 

> If a code is not described, then it is meaningless 

This is an unhelpful overstatement. Codes use english language words which can be interpreted by a reasonable user within a range of meanings. 

In some cases, without detailed analysis of source data, and of a full set of possible use cases, it is not always possible to give a tight definition - and in those cases, we have generally gone with the pragmatic approach of best efforts towards standardisation within the resources available: and improving definitions over time.

**Comment by jpmckinney** [comment]
While the interpretation is not unbounded, a single word is too ambiguous. OCDS and extensions contain many descriptions of codes that are not 'tight', but that nonetheless narrow the range of interpretations. I understand that we don't know everything (full set of use cases, detailed analysis of source data), but we can nonetheless write a description that reflects what we do know, with enough ambiguity around what we don't know.

For example, we know that we mean 'tender' as in 'call for tender', and not 'tender' in terms of documents submitted by a bidder. Without a description, a publisher who is unfamiliar with the former might not know how to interpret the code. Similarly, the distinction between 'contract' and 'implementation' is not obvious to a reasonable user. I can give more examples. Can we please attempt to include descriptions? If we then realize that descriptions are indeed worthless, we can remove them.

**Comment by timgdavies** [comment]
Going back to the original proposal, this suggested providing a business logic mapping between the properties of `releases` fields and `ContractingProcess.status`.

Given [comment 2](https://github.com/open-contracting/infrastructure/issues/1#issuecomment-423865248), the targets in `ContractingProcess.status` for that mapping could be:

* pre-award
* active
* closed 

Or (or a variation on):

* planning
* tender
* award
* contract
* implementation
* cancelled
* completion

The semantics of the terms will be more or less defined by the business logic itself, and so that needs working up prior to writing definitions. 

Coming from the user needs side of things, we should consider:

* When might a user interface want to distinguish between these states? (e.g. visually indicating when a contracting process is pre-award, active or closed)?
* When might analysis need to be based on the status, and what cuts of analysis are wanted?
* What might it be possible for a business process **without** access to OCDS data to keep up to date?

To see if we can go the simpler path, below my **first draft attempt** at a business logic mapping:

| code | business logic | definition |
|------|------------------|---------------|
| pre-award | The last release did not include any awards or contracts | No contract has yet been awarded |
| active | The last release includes award, contract or implementation information | There is at least one active award or contract |
| closed | The last release either indicates the status of all contracts as terminated, or all contract periods have passed | All contracts have now ended |

Would welcome thoughts on whether this feels like it would meet potential user needs - or whether the longer list should be worked up. 

I'm tempted in the interests of an alpha to move to this short list initially, and then the longer list could be re-introduced perhaps.

**Comment by jpmckinney** [comment]
Given the ambiguous status of draft Guidance Note 9, I don't know if the three values were the result of consultation and discussion, or simply one person's opinion. That said, the three statuses are close to a 'common denominator' among statuses seen in procurement data and portals. The question then is whether users need more granular statuses within the contract summary (whose general design is not to express the full detail of OCDS releases).

**Comment by jpmckinney** [comment]
Some suggested tweaks, to cover more edge cases:

code | business logic | definition
-- | -- | --
pre-award | There are no `awards` or `contracts`, or all `Award.status` and `Contract.status` are 'pending'  | No contract has yet been awarded.
active | One of: There is at least one `Contract.status` of 'active' | A contract was awarded, but not all contracts have ended.
closed | One of: `tender.status` is 'cancelled', 'unsuccessful' or 'withdrawn'; There is at least one award, and all `Award.status` are 'cancelled' or 'unsuccessful'; There is at least one contract, and all `Contract.status` are 'terminated' or 'cancelled'; The `endDate` of all contract periods (whether expressed as `Contract.period`, `Award.contractPeriod` or `tender.contractPeriod`) are in the past | The process ended with no contract being awarded, or all contracts have ended.

Award has no status to indicate 'complete', so successful, ended contracts end up with an award status of 'active'. I therefore don't include logic around award status being 'active'.

**Comment by timgdavies** [comment]
Thanks for the additional logic. 

I've put this into an update that makes the codelist include the simple three values.

I've moved this issue to alpha release, and will close: although @duncandewhurst & team may want to just pick up on this field in any follow up consultations with CoST team.
