### ISSUE TITLE
Discussion: Contract types (and focus codelist)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#11]
In the alpha version of the project level schema, the `contractingProcess/focus` codelist uses the following codes:

code | title | description
-------|------|--------------
design | Design | This contracting process relates to design of the project.
build | Build | This contracting process relates to build or construction work for the project.
supervision | Supervision | This contracting process relates to supervision or monitoring of the project.

Elsewhere the documentation varies between construction or build and supervision or monitoring.

In [CoST Guidance Note 6](http://infrastructuretransparency.org/wp-content/uploads/2011/12/31_CoST_Guidance_Note_6_Proof.pdf) mentions contracts for:

> design, supervision and or construction, etc.

The current version of the schema doesn't specify whether `contractingProcess/focus` is an open or closed codelist.

**Discussion**

* Are these the correct codes and titles?
* Can the descriptions be improved?
* Should `focus` be an open codelist so other types of contract can be included?(e.g. contracts for the preparation of project documentation, environmental studies etc.)
* What other types of contract are important for users of data on infrastructure projects?

**Comment by jpmckinney** [comment]
I find the misalignment between code and title to be confusing – most codelists have a closer match between the two. If you want to use multiple synonyms, I think it's best to do so in the description, rather than alternating words across code and title.

In the draft guidance note 9, I see 'Contract type' with the description "Develop a list such as Design, Supervision, Design & Supervision, Design & Build, Construction", which matches the schema (which allows for selecting multiple codes).

I don't know if `focus` is the correct term. The description of the field is more-or-less a description of its codelist, which doesn't shed light on the possibilities for its broader semantics (viz. the last two discussion questions).

If we stick to the three codes from CoST IDS, then perhaps `phase` is a better term, as the three codes tend to occur in a chronological sequence, much like the four project phases (#10).

**Comment by timgdavies** [comment]
Thanks both. The CoST documentation is inconsistent in term use, and I got caught out there - using one set for the codes, and then another set of terms in the descriptions. That was unintentional - but I've now updated the draft schema to settle on just 'design', 'build' and 'supervision' which appear to be the wider used terms as far as I can see.

I've updated  the table in Duncan's post above with proposed titles and descriptions. 

I'd be happy to have suggestions for a better term than `focus`. I had thought of `phase`, but thought there was potential for confusion there with the project phase.

**Comment by jpmckinney** [comment]
I also see the possibility for confusion. On the other hand, we already have a status field for both project and contract – which I think is using the word 'status' correctly and consistently. If 'phase' would similarly be used correctly and consistently for both project and contract, then I think it's simpler – for reader's conceptual clarity – to have two objects (project, contract) with two field names (status, phase) than to have two objects with three field names (status, phase, focus). Three field names can be confusing, in a different way, if two mean the same thing (phase, focus).

**Comment by duncandewhurst** [comment]
From IODC consultation:

* Design, Construction, Supervision (and combinations thereof) are the preferred codes
* Verification was also proposed as an additional contract type which some CoST implementers have included in monitoring but there wasn't clarity on what a verification contract was exactly
* The codelist should be open, to permit other types of contract to be linked to the project

**Comment by timgdavies** [comment]
We discussed this issue and I would advocate for maintaining a close codelist, to ease use of this field in analysis, and interface design. 

We have two main options then:

(1) The definition of 'design' is broadened to include 'preparation', and 'supervision' to also include 'verification'

(2) Additional codes are added for 'preparation' and 'verification' 

We should explore (1) in the first instance in conversation with partners.

**Comment by jpmckinney** [comment]
So that it's not lost, repeating that `phase` might be preferred to `focus` https://github.com/open-contracting/infrastructure/issues/11#issuecomment-424099477

**Comment by EvelynDinora** [comment]
I think we should maintain a closed codelist to facilitate disclosure. Design, Supervision and Construction and a combination of 2 and 3 of them. 

If we have some exceptional cases such as verification (its a technical and administrative audit to construction and supervision companies) option 1 would my preferred one:

(1) The definition of 'design' is broadened to include 'preparation', and 'supervision' to also include 'verification'



We should explore (1) in the first instance in conversation with partners

**Comment by EvelynDinora** [comment]
Also I want to refer to focus and phase. I think none of them are appropriate. It should be something like Contracttype or Contractservices or something else that really tell what should be selected from the code list.

**Comment by jpmckinney** [comment]
The trouble with 'type' is that 'type' is also used in other contexts to distinguish between, e.g. framework agreements, partnership agreements, concession agreements, lease agreements, etc. which are all different 'types' of contracts.

'Design', 'Construction' and 'Supervision' tend to follow a chronological order, so a word that implies a sequence is preferred. Such words include phase, stage, step.

**Comment by duncandewhurst** [comment]
Agree we should avoid 'type', in addition to the examples from @jpmckinney 'type' has also been proposed in the past to distinguish between fixed price, cost plus, time based contracts etc.

@EvelynDinora the description of this field is:

> This array field should record whether this contract is related to design, build or supervision. More than one value may be provided in cases where the contract is for design and build, or design and supervision etc.

With that additional context, would you be happy with renaming the field to 'phase'?

**Comment by EvelynDinora** [comment]
Agree on avoid type. We can use instead contract "category" or contract "nature" or contract "classification". I am not happy with "phase" since in a project not always we have a chronological order to procure those services, there are different ways to proceed including some services provided "in house" by the procuring entities.

**Comment by jpmckinney** [comment]
Of those, I prefer `nature`, though I'm open to `category`. We use `classification` elsewhere in a different way, so I prefer not to use it here.

**Comment by duncandewhurst** [comment]
Great, thanks both, I agree with `nature`.

I've made this update in the schema, added a codelist csv and updated the master copy of the IDS mapping.
