### ISSUE TITLE
Delete non-PR branches if stale, otherwise create PRs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#117]
https://github.com/open-contracting/infrastructure/branches/all

**Comment by duncandewhurst** [comment]
I've deleted any unused branches, for the remaining ones:

* `add-custom-switcher` can be deleted once the PR is merged
* `latest` was created as part of the deploy process, I'm not sure if we need to keep it (it exists and is protected in the main standard)
* `0.9` was created as part of the deploy process and reflects the current live docs, this should be kept and protected
* `gh-pages` does the redirect from the old github pages url to the current version of the docs, this should be kept and protected
* `alpha-2` was created when we deployed alpha-2, this should be kept and protected
* `master` is the dev branch, I suggest we create a new branch from this named `0.9-dev` and delete `master`

Do you agree with the above? If so please could you protect `latest` (if needed), `0.9`, `gh-pages` and `alpha-2` (I don't have admin rights on the repo) and I will create the new `0.9-dev` branch

**Comment by jpmckinney** [comment]
I have:

* protected latest, as a production branch (standard and ppp protect it)
* protected 0.9, as the production branch for minor series 0.9
* renamed master to 0.9-dev locally (`git branch -m`) and pushed 0.9-dev
  * changed default branch on GitHub to 0.9-dev
  * changed protection from master to 0.9-dev and deleted master
* protected gh-pages, to prevent accidental deletion of the redirect from http://open-contracting.github.io/infrastructure/

We typically don't use branches for things like `alpha-2`. Shouldn't we instead tag it?

**Comment by jpmckinney** [comment]
@duncandewhurst This should be easy to close, though can be done independently of a release (see question at end of my last update).

**Comment by duncandewhurst** [comment]
> We typically don't use branches for things like `alpha-2`. Shouldn't we instead tag it?

Yes, it can be tagged.

I drafted a release which you should be able to see [here](https://github.com/open-contracting/infrastructure/releases).

If you're happy with it I'll publish the release and delete the `alpha-2` branch

**Comment by jpmckinney** [comment]
Hmm, we don't typically create a full-on release through GitHub. Setting the tag is enough. (At least, I've never seen this documented anywhere.)

**Comment by duncandewhurst** [comment]
Just to check I have understood what you are asking for correctly:

* `git checkout alpha-2`
* `git tag -a alpha-2 -m 'alpha-2 release from initial development of OC4IDS.'`
* `git push --tags`

Then delete the `alpha-2` branch

**Comment by jpmckinney** [comment]
Yes, the tag message can simply be:

    git tag -a alpha-2 -m 'alpha-2 release.'

We keep longer descriptions in changelogs, announcements, etc.

**Comment by duncandewhurst** [comment]
Done: https://github.com/open-contracting/infrastructure/tags
