### ISSUE TITLE
Add public project identifier prefixes to documentation

### ISSUE THREAD

**Issue by pindec** [open-contracting/infrastructure#120]
We need a way to expose registered OC4IDS project identifier prefixes in the documentation.

Similar mechanism as for [OCDS](http://standard.open-contracting.org/latest/en/implementation/registration/)

**Comment by jpmckinney** [comment]
@pindec Do we have a spreadsheet set up yet? If so, this should be easy to do in 0.9.2.

**Comment by pindec** [comment]
Yes, it's in the OC4IDS helpdesk internal resources folder.

**Comment by jpmckinney** [comment]
Okay, I think it should be fairly quick and easy to include in 0.9.2 (in a similar embed to OCDS documentation), so adding to milestone.
