### ISSUE TITLE
Linked releases specification is overly constrained

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#127]
`url` is described as "A URL (Web link) to the related OCDS release where available. This should be provided within a releasePackage **that contains only one release.** Where this release is sourced from a third party system (e.g. procurement portal), transparency portal developers **are encouraged to cache this data and link to their cached copy**."

I recommend removing "that contains only one release", as release packages that contain only one release are rare; if the release is sourced from a third-party system that puts multiple releases into packages (as anticipated by OCDS), the OC4IDS implementer would have to both cache the release data and manufacture their own package, which are unnecessary steps to data publication.

With respect to caching data and linking to copies, I see this as providing poorer data provenance information. If the transparency portal developers are interacting with an unreliable source, then caching is an option that can be open to them, but this shouldn't be part of the field's description and instead moved to guidance.

Copy edits: "release package" should be two words, and "web" should be lowercase. "Related" is unnecessary here. So, I recommend:

> A URL (web link) to a release package containing the OCDS release, if available.

The other fields within `LinkedRelease` can also omit the word "related" and use "if available" instead of "where available".

**Comment by duncandewhurst** [comment]
@jpmckinney I've drafted the changes to the schema descriptions in #188 and removed the mention of caching OCDS releases from the getting started section.

Do you have a suggestion for where to put the guidance on caching releases from unreliable sources?

Adding a tip under https://standard.open-contracting.org/infrastructure/latest/en/guidance/using/#identify-how-you-will-query-the-data seems like the best place to me.

**Comment by jpmckinney** [comment]
Agreed, that looks best.
