### ISSUE TITLE
Linked release should include ocid field

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#128]
Otherwise, the release ID is not scoped to the contracting process of which it is a part.

**Comment by yolile** [comment]
is not the `contractingProcess/id` [field](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#contractingprocess) used for this?

> An identifier for this contracting process. If this contacting process has been assigned an Open Contracting Identifier (OCID) by an external platform (e.g. national procurement system), that OCID must be recorded here.

**Comment by jpmckinney** [comment]
Indeed! I somehow missed that.
