### ISSUE TITLE
Add a `publicAuthority` organization reference field on project

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#132]
Currently the project owner / public authority is only disclosed in the parties section.

To determine the owner of a project this means users need to check two arrays (`parties` and `parties/roles`).

We should consider adding a `publicAuthority` organization reference on the `project` object so that users and applications can more easily filter by the project owner.

**Comment by pindec** [comment]
@duncandewhurst I've added a new entry in `parties` for a publicAuthority, and added it to the `publicAuthority` field. A different party still has the roles of procuringEntity, buyer and administrativeEntity - is that realistic?
