### ISSUE TITLE
Improve clarity of 'what is project' section in Getting Started

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#133]
@juanpane flagged that the tip in the getting started section caused has caused some confusion when scoping OC4IDS implementation:

![image](https://user-images.githubusercontent.com/19265814/56808752-20d11800-682a-11e9-85a8-555dd64b9292.png)

@juanpane, would it help if we amended the second paragraph as follows? Please feel free to suggest alternatives or additions.

> In other contexts, the term ‘project’ can refer to a larger programme of work – of which projects in the sense of OC4IDS would form part of – like the construction of an entire highway, or to a public investment to which funds are allocated in a government’s budget, like the electrification of a rail network.

**Comment by duncandewhurst** [comment]
Note from Nico at OCP on the public investment project counter example:

> I would also like to add that public investment projects in countries include things other than infrastructure (although these are the most common). For example, a vaccination program may be a public investment project with several contracts and a specific timeframe. These projects may be funded through different loans, budget sources, etc.

**Comment by duncandewhurst** [comment]
@juanpane - I took another pass at improving the clarity of the tip. Please let me know if you are happy with the following and I'll add it to the 0.9.2 release:

> In OC4IDS, the term ‘project’ refers to an individual infrastructure project, defined as the development of a set of infrastructure assets in a specified location, generally the responsibility of a single procuring entity and budget authority: for example, a highway overpass or a university campus.
> 
> In other contexts, the term ‘project’ can refer to:
>
> * a larger programme of work – of which projects in the sense of OC4IDS would form part – like the construction of an entire highway.
> * a public investment, like the electrification of a rail network or a vaccination program, to which funds are allocated from a government’s budget or from another funding source, such as a loan from a multilateral development bank.

**Comment by duncandewhurst** [comment]
@jpmckinney @juanpane - are you happy with the revised text?

**Comment by jpmckinney** [comment]
I think 'electrification of a rail network' is a confusing example, as that can equally be a 'larger programme of work' involving multiple OC4IDS expansion/rehabilitation projects.

I'm not clear on the concept of 'public investment'. Before, it was scoped to things that arise in the government's budget, but now it can use any funding source, such that the source of funds no longer serves to disambiguate the concept.

Maybe what we're trying to say is that a "project" in the context of a government's budget might or might not be equivalent to an "infrastructure project" (depending on its nature, scope, etc.) – but then we might as well cut that bullet. The first paragraph is clear enough in that respect.

**Comment by jpmckinney** [comment]
Since we're not trying to exhaustively list what infrastructure projects are not (software projects, personal projects, etc.), I think we can instead replace the subsequent paragraphs/bullets with content like:

> A larger programme of work – like the construction of an entire highway – would be composed of multiple 'projects', in the context of OC4IDS.

If we have some useful clarification to make regarding public investments, we can compose a similar paragraph.

**Comment by duncandewhurst** [comment]
I think we're trying to highlight that 'project' in OC4IDS has a specific meaning and shouldn't be confused with other common uses of the word in the context of infrastructure or in the context of public financial management.

I think we are also trying to address @juanpane's concerns about disambiguating between the different uses of the word project, but perhaps that isn't necessary to do in the OC4IDS documentation.

**Comment by jpmckinney** [comment]
I think it's appropriate to do, but we need to clearly disambiguate. I think this is clear:

> A larger programme of work – like the construction of an entire highway – would be composed of multiple 'projects', in the context of OC4IDS.

If we can come up with other clear statements (e.g. regarding budget projects), we can add them. Otherwise, we can always add them at a later date.

**Comment by duncandewhurst** [comment]
I agree that your proposed update is clear, but I am not sure it addresses the concerns originally raised by @juanpane, which I think specifically included confusion between projects in OC4IDS, projects in the national budget and investment projects (related to https://github.com/open-contracting/standard/issues/887).

I will add this to the Latam check-in agenda to try and get some input from Juan.

**Comment by jpmckinney** [comment]
Sounds good. Sentence likes "A public investment – like [unambiguous example] – [is related to OC4IDS infrastructure projects in this way]" will be most useful to disambiguate.

By my understanding, that might be:

> A budget project [assuming this is the term that we're trying to clarify – 'public investment' doesn't include the word 'project'] is a programme of work as it appears in a government's budget. A budget project might relate to one or more infrastructure projects, in the context of OC4IDS: for example, a budget project to promote sustainability by electrifying a rail network. It might also not correspond to any infrastructure project at all: for example, a vaccination program.

Anyhow, our goal isn't to describe a taxonomy of different projects, so if my definition of budget project isn't correct, we can just omit the first sentence and limit the paragraph to how a budget project is different from an infrastructure project.

**Comment by jpmckinney** [comment]
Once resolved, we should align the paragraph about planning/budget/projectID, which refers to a national budget, though I think it can be any government's budget.

**Comment by duncandewhurst** [comment]
> Anyhow, our goal isn't to describe a taxonomy of different projects,

Agreed. I think that rather than explaining what a 'budget project' is, we should just say either 'project in a government's budget' or 'project code in a government's budget'.

Are you proposing to remove:

> In other contexts, the term ‘project’ can refer to:

I think that is helpful to introduce why we are talking about these other types of project, alternatively we could have an 'Other types of project' sub-heading.

**Comment by jpmckinney** [comment]
I'm happy to wait for the results of the call :) Right now, I think the first paragraph of the tip is very clear. We can maybe just say:

> The term "project" is used in many contexts to mean different things. However, to correctly implement and interpret OC4IDS, the above definition needs to be adhered to.

**Comment by duncandewhurst** [comment]
@tetecervantes94 please ask Juan if he can contribute to this issue. Thanks!

**Comment by duncandewhurst** [comment]
@juanpane and I discussed this issue and propose the following text:

> In the context of OC4IDS, the term ‘project’ refers to an infrastructure project, defined as the development of a set of infrastructure assets in a specified location, generally the responsibility of a single procuring entity and budget authority: for example, a highway overpass or a university campus.
>
> The term "project" is used in many contexts to mean different things, for example:
>
> * a larger programme of work, like the construction of an entire highway
> * an investment project, like in National Public Investment Systems (SNIP) in Latin America
> * a project code in a government's budget
>
> However, to correctly implement and interpret OC4IDS, the above definition needs to be adhered to.

**Comment by jpmckinney** [comment]
Looks good to me! I did a small copy-edit.
