### ISSUE TITLE
Update to OCDS 1.1.4

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#139]
After updating OCDS for PPPs to OCDS 1.1.4, we can run `borrow-schema.py` to update this to OCDS 1.1.4 (just changes code/field descriptions).

**Comment by duncandewhurst** [comment]
@jpmckinney do you have an idea of when OCDS for PPPs 1.0.0.beta2 will be deployed?

If I understood `borrow-schema.py` correctly, it pulls from https://standard.open-contracting.org/profiles/ppp/latest so we need to wait for it to be deployed before running (or edit `borrow-schema.py` if that won't happen soon)

**Comment by jpmckinney** [comment]
Salt broke on macOS Catalina, so I'm looking at a workaround. I had made some fixes and changes to the Apache configuration that I wanted to deploy before deploying OCDS for PPPs. If I can't sort it out, I'll ask ODS to deploy it.

**Comment by jpmckinney** [comment]
@duncandewhurst I've now deployed OCDS for PPPs 1.0.0.beta2.
