### ISSUE TITLE
Contracting processes summary: Update descriptions of `modifications` and `description`

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#141]
The current description for `modifications` is:

> Details of changes to the duration, price, scope or other significant features of the contracting process should be logged here.
> 
> A semi-structured description of each change can be provided in the relevant description field, and the justification of the change given in reason.
> 
> When a modification is detected, the contracting process summary information should also be updated.

I think this needs two updates:

1. Remove the following statement:

> When a modification is detected, the contracting process summary information should also be updated.

Modifications can relate to either the value, duration or scope of the contracting process, however the `summary/contractValue` and `summary/contractPeriod` properties are the **initial** values, so shouldn't be updated.

We should also update the description of `summary/description` to make it clear this should be the initial scope of the contract.

2. Remove the following statement:

> A semi-structured description of each change can be provided in the relevant description field, and the justification of the change given in reason.

The modifications model now has structured fields for the before and after values, so we can remove this statement about providing semi-structured information.

**Comment by jpmckinney** [comment]
First update sounds good.

> The modifications model now has structured fields for the before and after values, so we can remove this statement about providing semi-structured information.

Did we anticipate any other semi-structured information besides before/after values? If not, then second update sounds good, too.

**Comment by duncandewhurst** [comment]
> Did we anticipate any other semi-structured information besides before/after values? If not, then second update sounds good, too.

Sorry for leaving your comment hanging.

No, as far as I'm aware this statement just related to providing semi-structured information on changes to values and dates in the `description` field (the statement was added before there were any other structured fields available).

#174 removes the statement per the above
