### ISSUE TITLE
Link to OCDS publication policy guidance and add package metadata to worked example

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#143]
@yolile noticed that the publication policy isn't mentioned in the documentation (though it's present in the schema). Since this is important metadata, we should mention it somewhere (likely linking to OCDS documentation to avoid duplication of content).

**Comment by yolile** [comment]
We also need to update the "Implementation Guidance" section specially the [worked example](http://standard.open-contracting.org/infrastructure/latest/en/guidance/example/) to include packaging info, now the worked example is presented as a "fully completed OC4IDS JSON file" but the worked example doesnt have the package metadata.
