### ISSUE TITLE
Move OCDS codelists to the top of the codelist reference page

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#145]
From @jpmckinney:

> please put the references at the top of the page, before the codelists. As a documentation user, I find that I assume the structure of the page is codelist names followed by tables; I wouldn't expect to look for or find a list of links at the bottom of the long page

**Comment by jpmckinney** [comment]
This one should be easy and can be done as part of 0.9.2, but no problem if postponed.

**Comment by jpmckinney** [comment]
Re-opening as related: Why do we have currency and method in OC4IDS's documentation? All the codes are from OCDS, so should they be linked, like the release tag codelist? Removing the currency codelist in particular would make the page lighter.

**Comment by duncandewhurst** [comment]
Good question, I don't think that was intentional. https://github.com/open-contracting/infrastructure/pull/194 replaces those with links to the OCDS documentation.

The codelist reference page also includes two codelists from the location extension, so we could refer to the extension documentation for those, but keeping them in the OC4IDS documentation means users have fewer links to follow and don't need to worry about what an extension is, so I think that's OK.

**Comment by jpmckinney** [comment]
These links lead to fairly clean pages:

https://extensions.open-contracting.org/en/extensions/location/master/codelists/#geometryType.csv
https://extensions.open-contracting.org/en/extensions/location/master/codelists/#locationGazetteers.csv

I think users just need to follow the links, without an explanation of what an extension is.

**Comment by duncandewhurst** [comment]
I've updated those in https://github.com/open-contracting/infrastructure/pull/194
