### ISSUE TITLE
Unsure about Branch use

### ISSUE THREAD

**Issue by ghost** [open-contracting/infrastructure#151]
I was working on this and got in a bit of a muddle about which branch was active, which I should be working against, etc.

I checked https://ocds-standard-development-handbook.readthedocs.io/en/latest/github/branch_management/ but couldn't find anything to help.

I ended up working against the default branch in the repo, currently 0.9-dev. I did a few P.R.'s against that, and I also cherry picked a commit from another branch to it in #150.

Are there other docs somewhere I should have checked? Is this ok? If this isn't ok in terms of branch management, can it be documented somewhere what I should have done?

Thanks,
James

**Comment by jpmckinney** [comment]
Default branch is correct. Infrastructure follows the same pattern as other profiles: https://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/technical/repository/#branches-and-tags

**Comment by jpmckinney** [comment]
I added links from that page: https://github.com/open-contracting/standard-development-handbook/commit/f84677949ba0d083cedf16e4edebf9dd30c027c7
