### ISSUE TITLE
Consider to add 'expansion' code to projectType

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/infrastructure#152]
There are some infrastructure projects, like the airport expansions, who seeks to expand the existing assets.

It would be helpful if we can add the 'expansion' code to the projectType codelist, with the following description.

"The primary focus of this project is the expansion of an existing asset.

This code will be used at Nuevo León's implementation.

**Comment by jpmckinney** [comment]
Thanks, @antonioherrera! @duncandewhurst, this does indeed seem like a distinct project type to the existing codes. Who is best to engage among stakeholders (at least one person from CoST)?

**Comment by duncandewhurst** [comment]
@EvelynDinora are you happy for the code proposed by @antonioherrera to be added to the projectType codelist?

Given we have a use case in Neuvo Leon for the code, I am happy to add this, since other implementations can opt not to use the code, if they don't collect this much detail.

**Comment by duncandewhurst** [comment]
@EvelynDinora - please could you provide some feedback from CoST on this proposed code?

Ideally we would include this in the 0.9.2 release of OC4IDS, so feedback in the next week would be appreciated.

Thanks

**Comment by EvelynDinora** [comment]
@duncandewhurst we can add the proposal to the projectType code list. An extension of an asset is clearly different from other types. Thanks.

**Comment by duncandewhurst** [comment]
Thanks @EvelynDinora
