### ISSUE TITLE
Add 'relatedProjects' array to schema

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/infrastructure#153]
### Description

This addition to the schema allows relating different kinds of projects involved in the same infrastructure. For example: the construction, expansion, rehabilitation, or replacement of an existing airport through time. 

This extension seeks to have a record of modifications and spendings related to a specific infrastructure.

### Schema additions

```
“relatedProjects”: [{
          “id”: “relatedproject-0218462172sbue82”,
          “relationship”: “expansion”,
          “title”: “Ampliación de la Terminal 2 del Aeropuerto Internacional de Monterrey”,
          “scheme”: “OC4IDS”,
          “identifier”: “oc4ids-gx3fo2-PRO7261-2019”,
          “uri”: “https://www.nl.gob.mx/infraestructura/proyectos/PRO7261-2019”
          }
]

```

### Codelists

`Relationship` is an open codelist who has at least, the following codes:

Code | Title | Description
-- | -- | --
construction | Construction project | The related project is the initial construction of the infrastructure.
rehabilitation | Rehabilitation project | The related project might result in the rehabilitation of the same infrastructure.
replacement | Replacement project | The related project might result in the replacement of the same infrastructure.
expansion | Expansion project | The related project might result in the expansion of the same infrastructure.

As you can see, we duplicate the values from `projectType` to relationship, because we tried to replicate the `relatedProcess` structure, but maybe this field could be eliminated. We are open to your feedback.

You can see a draft of this addition (created as an extension) in: https://github.com/antonioherrera/oc4ids-Related-Projects

We think this could be added as a part of the main schema and not only as an extension.

**Comment by jpmckinney** [comment]
@duncandewhurst I'd agree that this is a good candidate for addition to OC4IDS.

**Comment by duncandewhurst** [comment]
Thanks @antonioherrera 

I agree this seems like a good addition to the core schema and I'm happy with your proposed modelling and codelist (edit: subject to the resolution of #152), so I've added this to the 0.9.2 milestone.

Regarding duplicating the values from the `projectType` codelist, I can see this would be useful for a user to understand which types of related projects exist without needing to fetch the whole data, so I'm happy for this to be kept.
