### ISSUE TITLE
Add 'requestDate' on 'budget' object

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/infrastructure#154]
There is a use case for this extension. 

When having a central institution responsible for the contracting process of infrastructure projects, there is a need to inform the other institutions when the budget was requested and when the budget was finally approved. So, with this, the central institution can justify why the project has not been initiated.

You can see a draft of this extension here: https://github.com/antonioherrera/oc4ids_requestDate_extension

**Comment by jpmckinney** [comment]
@duncandewhurst Do the budget-related OCDS extensions contain any alternate modelling for this information?

I think with OC4IDS, we should try to simply add fields to the main schemas, and only adopt an extension mechanism if we really see a significant demand for additional fields.

**Comment by duncandewhurst** [comment]
Thanks @antonioherrera!

> @duncandewhurst Do the budget-related OCDS extensions contain any alternate modelling for this information?

No, in OCDS this would be modelled using `planning.milestones` (with `.type` set to 'preProcurement'). However, adding `requestDate` on `budget` is consistent with having an explicit field for `approvalDate` in OC4IDS, so I'm happy with the proposed modelling.

> I think with OC4IDS, we should try to simply add fields to the main schemas, and only adopt an extension mechanism if we really see a significant demand for additional fields.

Agreed, this is a good opportunity for the standard to meet use cases outside of those originally envisaged by CoST in the IDS. I've added this issue to the 0.9.2 milestone so we can add the field in that update.

@antonioherrera that means you can just include `requestDate` as an additional field in your data and once 0.9.2 is released it should validate.

**Comment by pindec** [comment]
Does adding a budget/requestDate field also require an update to the [document type codelist](https://github.com/open-contracting/infrastructure/blob/0.9-dev/schema/project-level/codelists/documentType.csv)?

The field description for budget/approvalDate is:

> "The date on which the project budget was approved. Where documentary evidence for this exists, it may be included amongst the project documents with the documentType set to 'budgetApproval'.

Is there also documentary evidence for the request date which might be disclosed and therefore require a "budgetRequest" document type code?

**Comment by duncandewhurst** [comment]
It looks like @antonioherrera omitted "Where documentary evidence..." from the description of `requestDate`, so I think we can do the same and not add anything to the document type codelist, until we have an example where such a document exists.
