### ISSUE TITLE
Restore all Travis tests

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#155]
To ensure there are no schema or codelist errors before releasing 0.9.2.

**Comment by duncandewhurst** [comment]
I've restored the tests on [`155-restore-travis-tests`](https://github.com/open-contracting/infrastructure/tree/155-restore-travis-tests). They are currently failing on the `#ref` to the project schema in `project-package-schema.json` as follows:

```bash
=================================== FAILURES ===================================

/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jsonref.py:229: jsonref.JsonRefError: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

=============================== warnings summary ===============================

test_json.py::test_json_schema

  ERROR: schema/project-level/project-package-schema.json has JSONDecodeError: Expecting value: line 1 column 1 (char 0) at properties/projects/items
```
I can't see anything wrong with the package schema so I tried updating `test_json.py` to handle the project package schema in case that was causing the issue, but I'm still getting errors. My efforts are on [this branch](https://github.com/open-contracting/standard-maintenance-scripts/tree/project-package).

@jpmckinney could you take a look please?

**Comment by jpmckinney** [comment]
I'm not sure if you pushed your commits to that branch. In any case, see #196
