### ISSUE TITLE
contractingProcesses/releases/tag is string instead of array

### ISSUE THREAD

**Issue by romifz** [open-contracting/infrastructure#158]
Should `contractingProcesses/releases/tag` be an array? Definition says 

> One **or more** values from the releaseTag codelist...

![screenshot-standard open-contracting org-2019 10 21-15_05_40](https://user-images.githubusercontent.com/1881108/67230924-a23de780-f414-11e9-8a85-ae792de034e8.png)

**Comment by duncandewhurst** [comment]
Yes, good spot!
