### ISSUE TITLE
Discussion: Sector classification

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/infrastructure#16]
## The problem

The CoST IDS asks for projects to be classified by **sector** and **sub-sector**. Guidance suggests these lists should be developed on a national basis:

> Develop a list of sectors relevant to country e.g. housing, transport, energy, water etc.

and

> Develop a subset for each sector e.g. Transport could be subdivided into national highway, local road, railway, port, airport etc.

respectively. 

However, in draft work, the CoST team have suggested use of a sector list from the [PPP Certification guide](https://ppp-certification.com/ppp-certification-guide/4-where-ppps-are-used-%E2%80%93-infrastructure-sectors). This has been identified as providing good coverage of sectors that infrastructure transparency programmes may wish to describe, but it lacks established codes, or commitments to code list management. 

In OCDS for PPPs we recommend classification using UN COFOG (Classifications of the Functions of Government) which has the advantage of established codelist management, and being widely used for production of statistics. 

At present, our guidance in the Project Level Data Specification reads:

> The main sector this project relates to. CoST guidance suggests that countries should develop a list of sectors and sub-sectors relevant to the country. When these codelists are organised hierarchically, it should be possibly to classify at the sub-sector level, but then infer the top-level sector from this. In the absence of an appropriate national list, either (a) use of UN COFOG codes, with ‘COFOG’ as the classification scheme, and the numerical COFOG code used; or (b) use of the sector list from the PPP Certification guide with ‘PPPCERT’ as the classification scheme, is recommended. It should be

## Options for discussion

* We could maintain the current guidance that gives a range of options on how to represent sector classification
* We could narrow our recommendation to use of UN COFOG only
* We could fork a copy of PPPCERT and maintain this a codelist with codes and labels

Discussion of this may require infrastructure analysis experts to review and compare PPCERT and UNCOFOG.

**Comment by jpmckinney** [comment]
FYI, COFOG can be [consulted here](https://unstats.un.org/unsd/publications/catalogue?selectID=145).

COFOG is broader than infrastructure, but a subset may be appropriate. For the benefit of other participants, COFOG stands for 'Classification of the Functions of Government'. It's a good classification scheme for describing the 'sectors' of *government organizations*, e.g. the EU uses it for the 'Main activity' of contracting bodies. Government organizations, presumably, run procurements and projects that relate to their main activity, but using COFOG to classify procurements and projects nonetheless seems a bit of a fudge, because the COFOG codes are frequently defined in a way that is only properly interpretable from the perspective of classifying organizations, not classifying procurements or projects. As a facile example, 'Executive and legislative organs' are not procured.

**Comment by jpmckinney** [comment]
FYI, PPPCERT can be [consulted here](https://ppp-certification.com/ppp-certification-guide/4-where-ppps-are-used-%E2%80%93-infrastructure-sectors). Would the codelist be based on the 'Sector' column of Table 1.5?

**Comment by duncandewhurst** [comment]
From consultation at IODC:

* Use of the PPPCERT codelist (with some adaptations to the sub-sectors) was based on consultation with 13 countries by CoST
* There were concerns raised about allowing choice between PPPCERT and COFOG for data interoperability
* There should be two codelists: a closed codelist for sector and an open codelist for sub-sector

**Comment by timgdavies** [comment]
This will require addition of a sub-sector field, and we may be able to simplify sector to a single field rather than object with a closed codelist.

We will need to create a CSV copy of the forked PPPCERT list, and manage this.

There may be IP issues with that, to check with CoST on.

**Comment by jpmckinney** [comment]
It might be the case that there is no good list to use. I did a little exploring and found classifications of sectors by the PPP Knowledge Lab (also in the World Bank Group) (Note: The website doesn't always load, so you might need to use the Internet Archive.) Its lists omit the division between 'economic' and 'social', which I agree is not a robust division.

Here's its main list: https://pppknowledgelab.org/sectors

Some subsectors are repeated under multiple sectors:

* Irrigation
* Urban Revitalization
* Urban Transport
* Urban Water & Sanitation

It makes sense for these to be classified under multiple sectors, but in an eventual codelist, I think they should only appear once.

Sector | Subsector
-- | --
Agribusiness | Grain Storage
Agribusiness | Irrigation
Education | 
Health | 
ICT | Broadband
ICT | E-Government 
Municipal  | District Heating & Cooling
Municipal  | Public Lighting
Municipal  | Urban Revitalization 
Municipal  | Urban Transport
Municipal  | Urban Water & Sanitation
Municipal  | Waste
Power | Generation 
Power | Transmission
Power | Distribution
Power | Renewables 
Tourism | Heritage Sites
Tourism | National Parks 
Tourism | Urban Revitalization 
Transport | Airports
Transport | Ports
Transport | Rail
Transport | Roads
Transport | Urban Transport
Water & Sanitation | Irrigation
Water & Sanitation | Small-Scale Water & Sanitation
Water & Sanitation | Urban Water & Sanitation

```
import requests
import lxml.html

print('Sector | Subsector\n-- | --')
url = 'https://pppknowledgelab.org/sectors'
page = lxml.html.fromstring(requests.get(url).content)
for div in page.xpath('//div[@class="view-content"]/div'):      
    sector = div.xpath('.//h1//text()')[0]
    subsectors = div.xpath('.//a/@title')
    if subsectors:
        for subsector in subsectors:
            print('{} | {}'.format(sector, subsector))
    else:
        print('{} | '.format(sector))
```

There's another list elsewhere, but it omits many sectors like Agribusiness, ICT, Tourism: https://pppknowledgelab.org/guide/sections/8-how-ppps-are-used-sectors-and-services

Additions are:

* Prisons (under Social and government infrastructure)

Changes are:

* Generation -> Generation assets
* Distribution -> Distribution systems
* Education -> Education—school facilities and services (under Social and government infrastructure)
* Health -> Health—hospitals and other health facilities and services (under Social and government infrastructure)
* Urban Transport -> Mass transit systems
* Roads -> Roads, tunnels, and bridges
* Waste -> Solid waste management services

For 'Urban regeneration and social housing projects', 'Urban regeneration' might correspond to 'Urban Revitalization', but 'social housing projects' has no correspondence.

In the above codelist, 'Waste' is under 'Municipal'. In the below codelist, 'Waste' is under 'Water and waste', hence the sector name doesn't correspond to 'Water & Sanitation'.

Water subsectors are different: 'Irrigation', 'Small-Scale Water & Sanitation' and 'Urban Water & Sanitation versus 'Bulk water treatment' and 'Water distribution and sewerage systems'

Sector | Subsector
-- | --
Power | Distribution systems
Power | Generation assets
Social and government infrastructure | Education—school facilities and services
Social and government infrastructure | Health—hospitals and other health facilities and services
Social and government infrastructure | Prisons
Social and government infrastructure | Urban regeneration and social housing projects
Transport | Airports
Transport | Mass transit systems
Transport | Ports
Transport | Rail
Transport | Roads, tunnels, and bridges
Water and waste | Bulk water treatment
Water and waste | Solid waste management services
Water and waste | Water distribution and sewerage systems

Extracted using:

```python
import requests
import lxml.html

print('Sector | Subsector\n-- | --')
url = 'https://pppknowledgelab.org/guide/sections/8-how-ppps-are-used-sectors-and-services'
page = lxml.html.fromstring(requests.get(url).content)
sectors = []
for tr in page.xpath('//section[@id="table-4"]//tr[position() > 1]'): 
     sector = tr.xpath('./td[1]/p/text()')[0]
     for subsector in tr.xpath('./td[2]/p/text()'): 
         sectors.append('{} | {}'.format(sector, subsector)) 
for sector in sorted(sectors):
    print(sector)
```

**Comment by jpmckinney** [comment]
If I take the first list as a starting point, and compare to the PPPCERT list, I get the list below.

I removed the repeated subsectors mentioned above:

* Irrigation from Water & Sanitation
* Urban Revitalization from Tourism
* Urban Transport from Municipal
* Urban Water & Sanitation from Municipal

I added from the second list above, from under Social and government infrastructure:

* Prisons
* Social Housing (was Urban regeneration and social housing projects)

I removed 'Waste' from 'Municipal' and replaced the 'Water & Sanitation' breakdown with the 'Water & Waste' sector from the second list above, as the different lists didn't have shared subsectors.

I remove the 'Municipal' sector, which had three remaining subsectors: District Heating & Cooling, Public Lighting, Urban Revitalization.

I interpret the 'Examples' column from PPPCERT as informative and non-normative, but I include examples in parentheses if they match a subsector in the table below.

Sector | Subsector | PPPCERT
-- | --
Agribusiness | | Economic – Agribusiness
Agribusiness | Grain Storage | Example: Grain storage PPPs
Agribusiness | Irrigation | Example: Irrigation projects
Education | | Social – … education …
Health | | Social – health …
ICT | | Economic – Information and Communications Technology (ICT) /telecommunications
ICT | Broadband | -
ICT | E-Government | -
Power | | Economic – energy
Power | Generation | -
Power | Transmission | -
Power | Distribution | -
Power | Renewables | -
Tourism | | Economic – Tourism
Tourism | Heritage Sites | Example: Cultural heritage buildings
Tourism | National Parks | Example: National parks
Transport | | Economic – transport
Transport | Airports | Economic – transport > … airports
Transport | Ports | Economic – transport > ports …
Transport | Rail | Economic – transport > rail
Transport | Roads | Economic– transport > roads
Transport | Urban Transport | Economic–transport > other urban mobility infrastructure
Water & Waste | | Economic – water and waste
Prisons | | Social – … security/prisons …
Social Housing | | Social – … social housing

Not included from PPPCERT:

* Social – … courts/justice …
* Social (others) – sports, emergency response and local security, government accommodations
  * Sport centers
  * Fire stations
  * Police stations
  * Government offices
* Other potential sectors for PPPs
  * Defense: flight simulators or other simulators
  * Military facilities
  * National border posts or facilities

**Comment by jpmckinney** [comment]
Looking for similar lists of sectors (which I sometimes group under parenthesized headings):

US National Research Council https://www.nap.edu/read/798/chapter/3 in a footnote:

* (Energy)
  * electric power generation …
  * electric power … transmission
* telecommunications
* (Transport)
  * airports and airways
  * highways, streets, roads, and bridges
  * mass transit
* (Water & Waste)
  * water supply and water resources
  * wastewater management
  * solid-waste treatment and disposal
  * hazardous waste management

Observations: Water and waste are sub-classified.

American Society of Civil Engineers: Infrastructure Report Card https://www.infrastructurereportcard.org/wp-content/uploads/2016/10/2017-Infrastructure-Report-Card.pdf (emphasis added)

* Schools
* Energy
* (Transport)
  * Aviation
  * Ports
  * Rail
  * Roads
  * **Bridges**
  * Transit
* (Water & Waste)
  * Dams
  * Drinking Water
  * Hazardous Waste
  * Inland Waterways
  * Levees
  * Solid Waste
  * Wastewater
* **Parks & Recreation**

Observations: Water and waste are sub-classified. Bridges are distinct (in other classifications, they might be under Roads and/or Rail).

The Canadian Council for Public-Private Partnerships http://p3spectrum.ca/project/

* Education
* Health
* Information Technology
* Energy
* Transportation
* Water & Wastewater
* **Accommodations**
* **Justice**
* **Recreation & Culture**
* **Government Services**

USAID: web page https://www.usaid.gov/infrastructure

* schools
* health
* communications
* energy
* transportation
* water, sanitation

PWC: PDF report https://www.pwc.com/gr/en/publications/greek-thought-leadership/infrastructure%20-funding-the%20-future-%202017-en.pdf uses informal classifications, adding up to (emphasis added):

* Schools (Social Infrastructure) (definition)
* Hospitals (Social Infrastructure) (definition)
* ICT (definition)
* Energy (pie chart)
* Tourism (pie chart)
* Transport (definition)
  * Airports (definition)
  * Ports (definition)
  * Rail (pie chart)
  * Road (definition)
  * **Urban Rail** (pie chart)
  * Transit Transport (pie chart)
* (Water & Waste)
  * Waste Management (pie chart)
  * Water & Sanitation (definition)
* **Other (Social Infrastructure)** (definition)
  * Public Buildings
  * Sport Structures
  * Green Areas

Observations: Urban Rail is grouped with Rail in a bar chart, though in terms of density (urban), it might be grouped with Transit Transport.

Infrastructure Victoria http://www.infrastructurevictoria.com.au/sites/default/files/images/Infrastructure%20Victoria_fact_sheet.PDF (emphasis added)

* Science, agriculture and environment
* Education and training
* **Health and human services (including social housing)**
* Information and Communications Technology (ICT)
* Energy
* **Cultural, civic, sporting, recreational and tourism**
* Transport (including public transport, freight, ports and airports, cycling and walking, roads)
  * airports
  * ports
  * freight
  * roads
  * public transport
  * cycling
  * walking
* Water (including waste-water) and waste
* **Justice (including courts, police, corrections, emergency services) / [Justice and emergency services](https://s3.ap-southeast-2.amazonaws.com/hdp.au.prod.app.iv-30year.files/7914/5672/8242/160229_-_Executive_Summary_-_Final.pdf)**

Observations: I haven't (yet) seen other references to science or environment infrastructure. The [Victoria's 30-year Infrastructure Strategy](http://infrastructurevictoria.com.au/sites/default/files/images/IV_30_Year_Strategy_WEB_V2.pdf) has a "Recommendations quick reference guide" listing infrastructure projects, each of which may belong to multiple sectors. There is only one 'Science, agriculture and environment' project (Habitat corridors) that is not 'Water and waste' or 'Cultural, civic, sporting, recreation and tourism'. Freight is given as an example of transport; it overlaps airports, ports, rail and roads, and I haven't seen other references to it.

https://www.statista.com/statistics/264753/ranking-of-countries-according-to-the-general-quality-of-infrastructure/ (emphasis added)

* communications
* energy
* transport
* water, waste
* **defense**

OECD Economic Infrastructure ([link](https://www.oecd.org/dac/aft/AFT-Economic-Infrastructure.pdf), [link](https://www.oecd.org/dac/aft/Aid-for-trade-sector-codes.pdf)) includes sub-classifications that might better fit into the meta-classifications of personal or institutional infrastructure. Anyhow, the top-level classifications are:

* Transport and storage
* Communications
* Energy generation, distribution and efficiency / Energy generation and supply

If we eliminate subsectors from the above table, and expand or merge some sectors, we get this list. 

We might want to retain the transport breakdown as above, however, as transport [sometimes](https://www.pwc.com/gr/en/publications/greek-thought-leadership/infrastructure%20-funding-the%20-future-%202017-en.pdf) exceeds 50% of infrastructure budgets.

We might also want to retain a water and waste breakdown, as these are more frequently broken down, in the observed classifications. I would propose (with number of occurrences in 5 breakdowns):

* Water Supply ([link](https://en.wikipedia.org/wiki/Water_supply), [link](https://en.wikipedia.org/wiki/Water_supply_network) (8) (including desalination, purification, treatment, distribution, drinking water, dams, levees, inland waterways)
* Irrigation (1)
* Wastewater (4) (including treatment and sewerage)
* Solid Waste (4)
* Hazardous Waste (2)

Which eliminates:

* Waste to energy plants – incineration plants (treated as Energy)
* Small-Scale Water & Sanitation (a density meta-classification)
* Urban Water & Sanitation (a density meta-classification)
* Integrated water cycle concessions (few search results)

'Sanitation' [includes](https://www.cdc.gov/healthywater/global/sanitation/index.html) wastewater, solid waste and hazardous waste, and therefore is not included.

Energy is inconsistently sub-classified. Some classifications omit either transmission (PPP Knowledge Lab's second list) or distribution (US National Research Council). If we include sub-classifications, we can consider combining the two into one.

When writing code definitions, we can include alternate names, like schools and training, and clarifications, like where bridges are classified.

* Health is expanded to Health & Human Services, and Social Housing is removed
* Power is renamed to the more commonly observed Energy
* Prisons is expanded to Justice & Emergency Services
* Accommodations is added (including public buildings, government offices)
* Culture & Recreation is added (including parks and sports)
* Defense is added (including borders)

Tourism isn't combined with others, as it [sometimes](https://www.pwc.com/gr/en/publications/greek-thought-leadership/infrastructure%20-funding-the%20-future-%202017-en.pdf) represents a major share of a budget of its own.

Sector | PPPCERT
-- | --
Agribusiness | Economic – Agribusiness
Education | Social – … education …
Health & Human Services | Social – health … social housing
ICT | Economic – Information and Communications Technology (ICT) /telecommunications
Energy | Economic – energy
Tourism | Economic – Tourism
Transport | Economic – transport
Water & Waste | Economic – water and waste
Justice | Social – … security/prisons, courts/justice … / Social (others) – … emergency response and local security …
Accommodation | Social (others) – … government accommodations
Culture & Recreation | Social (others) – sports …
Defense | Other potential sectors for PPPs

**Comment by EvelynDinora** [comment]
We prefer to fork a copy of PPPCERT and maintain this a codelist with codes and labels since this classifictaion is specifically for infrastructure. Remember that PPPs can also be used for other purposes not only for infrastructure and is understandable the use of the UN COFOG list for PPPs.

**Comment by jpmckinney** [comment]
@EvelynDinora I reviewed 19 different classifications for infrastructure, and PPPCERT has several issues, so I recommend basing the codelist on it, but taking the opportunity to fix issues that aren't in the other classifications.

For example:
* PPPCERT puts ports and airports together, whereas the 10 other classifications with a transport breakdown put them separately. In the real world, the responsible agencies for ports and airports are usually different, and the projects are quite different.
* PPPCERT has a giant category of "health, education, security/prisons, courts/justice, social housing". 
  * Health (including social housing) and education are two huge areas of investment, whereas the 14 other classifications that include these categories puts them separately.
  * The remaining "security/prisons, courts/justice" parts can fit into a new category like Governance (government accommodations, public buildings, government offices; justice, courts; emergency services / response, local security; security, prisons, corrections; defense, military).
* Meanwhile, PPPCERT separates out tourism and agribusiness, which rarely occur in other classifications, and which are better bundled into Economy (agribusiness, agriculture, science, environment) and Culture, sports and recreation (tourism, parks, green areas).
* PPPCERT has a mixed category of "sports, emergency response and local security, government accommodations". These have nothing to do with each other. Sports can go in Culture, sports and recreation, and the other two can go in Governance.
* PPPCERT has an ambiguous category of "Other potential sectors for PPPs", but all its examples are defense / military. This can go into Governance.

So, my recommended classification (based on all 19 classifications reviewed, including PPPCERT) is:

## Minimal version

* Education (training, schools)
* Health (hospitals, healthcare, human services, social housing)
* Energy (power)
* Communications (ICT, IT, telecommunications, postal facilities, high-speed internet, broadband)
* Transport (transportation)
* Water and waste (sanitation, wastewater)

## Minimal version plus infrequent categories

As above plus:

* Governance (government accommodations, public buildings, government offices; justice, courts; emergency services / response, local security; security, prisons, corrections; defense, military)
* Economy (agribusiness, agriculture, science, environment)
* Culture, sports and recreation (tourism, parks, green areas)

## Minimal version with transport breakdowns

As one of the above plus:

* Transport (transportation)
  * Air transport (airports, airways, aviation)
  * Water transport (ports, inland waterways)
  * Rail transport (rail)
  * Road transport (roads, highways, streets, tunnels, bridges)
  * Urban transport (mass transit, urban mobility, buses, cycling and walking, taxi)

**Comment by duncandewhurst** [comment]
@jpmckinney thanks for your comprehensive research in this issue.

I agree that if the specification does not defer to a widely used codelist with an established approach to management then we should base any new codelist on this research rather than only on PPPCERT.

Did your research surface appropriate descriptions for the proposed codes or do you suggest crafting descriptions based on the alternative names in parentheses (e.g. For the Education code "Education projects, including schools and training facilities")?

**Comment by jpmckinney** [comment]
Most classifications were just a list of words, following by more detailed lists of words, so I agree with your proposal. Some notes:

* We might want to check that we have the best names for 'Governance' and 'Economy'.
* Many classifications break down energy and water/waste, but not in similar ways. So, a breakdown might be desired by users, but I don't think we have a common breakdown to offer.
* I wouldn't have expected social housing to appear under health, but more than one classification does so, and I can see the justification. Just flagging.

**Comment by EvelynDinora** [comment]
As we discussed we would like the PPPCERT codelist as the basic one and then improve it based on @jpmackinney research. When the draft is ready when can validate it with CoST members.

**Comment by duncandewhurst** [comment]
thanks @EvelynDinora the draft codelist for review is [here](https://docs.google.com/spreadsheets/d/17FRnRXaXmsQZusf9_vmlRhRUuA4Fdy2ORIxizABCLRI/edit#gid=587149807)

Could a project belong to more than one sector from the list? i.e should we allow an array of values for the `sector` field in the schema?

**Comment by duncandewhurst** [comment]
Note from @jpmckinney on proposed codelist:

> If the field is an array of codes, then I think the guidance should be to have ["transport", "transport.air"] so that applications don't need to understand how to segment subsectors.

**Comment by cost-platform** [comment]
About the Code List: It would be important to add more details for energy: power producer plants, Electricity transmission lines, Gas pipelines. Please take social housing out of health: Social housing should be one separate sector. In education we should add university and other learning facilities.

**Comment by cost-platform** [comment]
About the possibility of having a project that belong to more than one sector: Yes, it could be possible, for instance inter-urban roads with cycle tracks (this possibility is according the proposed code list). Also, it could be possible when a project is responding to an emergency: for instance repair an urban road and at the same time water and electricity or communication facilitates after affected by a natural disaster. This is normally the exception to the rule, but it could happen.

**Comment by jpmckinney** [comment]
> add more details for energy: power producer plants, Electricity transmission lines, Gas pipelines. 

The different codelists I researched added more detail in different ways. To cover the three you describe, we could add:

* energy.generation: Electric power generation, including power plants
* energy.transmission.electric: Electric power transmission, including power lines
* energy.transmission.gas: Gas transmission, including pipelines

The pattern of "." sub-codes makes it easier to fill in any gaps in the future.

> take social housing out of health: Social housing should be one separate sector

We can make it into its own sector. It's a very small sector compared to the others, so I had attempted to fit it into the closest category.

> In education we should add university and other learning facilities.

We can have "Education, including schools, universities and other learning and training facilities" instead of "Education, including training and schools".

**Comment by duncandewhurst** [comment]
Thanks both, I've updated the [draft codelist](https://docs.google.com/spreadsheets/d/17FRnRXaXmsQZusf9_vmlRhRUuA4Fdy2ORIxizABCLRI/edit#gid=587149807) to incorporate the suggested changes (highlighted in green).

@cost-platform please confirm whether the additional sub-codes proposed by @jpmckinney are required, or whether the expanded description for the 'energy' code ("Energy, including electric and gas power generation and transmission") is sufficient.

**Comment by jpmckinney** [comment]
If we expand the energy description, I suggest:

> Energy, including electric power generation, and the transmission and distribution of electricity, oil and gas

i.e. adding in the concepts of distribution and oil.

**Comment by jpmckinney** [comment]
I might have misunderstood @cost-platform's earlier comment – if the intention was simply to clarify the definition of energy, then I would prefer that to adding more codes at this time.

**Comment by cost-platform** [comment]
Yes, the comments on energy and education are aiming to clarify the definition, instead of adding more codes.

**Comment by cost-platform** [comment]
> Thanks both, I've updated the [draft codelist](https://docs.google.com/spreadsheets/d/17FRnRXaXmsQZusf9_vmlRhRUuA4Fdy2ORIxizABCLRI/edit#gid=587149807) to incorporate the suggested changes (highlighted in green).
> 
> @cost-platform please confirm whether the additional sub-codes proposed by @jpmckinney are required, or whether the expanded description for the 'energy' code ("Energy, including electric and gas power generation and transmission") is sufficient.

The expanded description is sufficient. Many thanks

**Comment by duncandewhurst** [comment]
thanks all, I've updated the [draft codelist](https://docs.google.com/spreadsheets/d/17FRnRXaXmsQZusf9_vmlRhRUuA4Fdy2ORIxizABCLRI/edit#gid=587149807) to remove the extra energy codes and use the expanded description.

These changes are staged in https://github.com/open-contracting/infrastructure/pull/98 and will be merged in by the end of this week, for inclusion in the beta.
