### ISSUE TITLE
ocid duplication

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#161]
There are two fields in the schema in which the `ocid` of a related contracting process should be provided:

`contractingProcesses/id`:

> "An identifier for this contracting process. If this contacting process has been assigned an Open Contracting Identifier (OCID) by an external platform (e.g. national procurement system), that OCID must be recorded here. If information about this contracting process has been entered manually, or from a non-OCDS system, then an identifier may be created by the system data is entered into, following the [guidance for creating contracting process identifiers](http://standard.open-contracting.org/latest/en/schema/identifiers/#contracting-process-identifier-ocid)."

`contractingProcesses/summary/ocid`:

> "If this contacting process has been assigned an Open Contracting Identifier (OCID) by an external platform (e.g. national procurement system), that OCID must be recorded here. Otherwise this field should be omitted."

`contractingProcesses/id` is required because items in an array must have an `id` field, but `contractingProcesses/summary/ocid` seems duplicative.

The latter field was introduced in https://github.com/open-contracting/infrastructure/issues/9, as part of aligning the structure of `summary` with a compiled release, but having both could be confusing for publishers (e.g. in the draft SISOCS data an ocid was provided in `ocid`, but an internal identifier was provided in `id`, which is wrong).

@jpmckinney can you recall a specific reason for having the `ocid` field or do you think we could drop it?

**Comment by jpmckinney** [comment]
I think we can remove it. Related: #128

**Comment by duncandewhurst** [comment]
I just came upon the reason for having both fields in https://github.com/open-contracting/infrastructure/issues/51#issuecomment-470386164

@jpmckinney - based on that, should we reinstate the `ocid` field?

**Comment by jpmckinney** [comment]
Yes, thanks for catching that!
