### ISSUE TITLE
Link to projects schema from project package schema is broken

### ISSUE THREAD

**Issue by pindec** [open-contracting/infrastructure#162]
[Packaging data](https://standard.open-contracting.org/infrastructure/latest/en/reference/package/) project package schema browser has a broken link to the project schema.

Currently displays as `array[1..] http://standard.open-contracting.org/infrastructure/schema/0__9__1/project-schema.json`

**Comment by pindec** [comment]
Looks like the docson/widget.js might be trying to load the schema over HTTP even though the path is relative:

"Mixed Content: The page at 'https://standard.open-contracting.org/infrastructure/latest/en/reference/package/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://standard.open-contracting.org/infrastructure/schema/0__9__1/project-schema.json'. This request has been blocked; the content must be served over HTTPS."

**Comment by jpmckinney** [comment]
This is fixed in https://github.com/open-contracting/infrastructure/commit/1359cfacfce091ed1f51eacfc89414c7962784ee

The problem was:

```
"items": {
  "$ref": "http://standard.open-contracting.org/infrastructure/schema/0__9__1/project-schema.json"
},
```

**Comment by jpmckinney** [comment]
Works on dev branch https://standard.open-contracting.org/infrastructure/0.9-dev/en/reference/package/
