### ISSUE TITLE
Spellcheck project

### ISSUE THREAD

**Issue by pindec** [open-contracting/infrastructure#165]
Further to spelling corrections in the schema #157 we should run a spellcheck across the whole project.

**Comment by jpmckinney** [comment]
I've done this in other repos using this process: https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/spellcheck.html

It's fairly repetitive (lots of false positives), so I don't mind doing it for OC4IDS given that I have the hang of it now.

**Comment by duncandewhurst** [comment]
@jpmckinney are you happy to run the spell check again now everything else is merged?

**Comment by jpmckinney** [comment]
Yes, see #200.

**Comment by duncandewhurst** [comment]
Closed by #200
