### ISSUE TITLE
Update Spanish translation with changes in 0.9.2

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#179]
Once all other issues and PRs in the 0.9.2 milestone are closed/merged, before deployment, we'll need to follow the [translation process](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/translation/workflow.html#steps) in the standard development handbook, to update the Spanish translation to include the changes in 0.9.2.

**Comment by jpmckinney** [comment]
Noting that we'll also need to update `config.mk`, `tests/__init__.py`, `.travis.yml`.
