### ISSUE TITLE
Run schema-strict and add validation properties to schema

### ISSUE THREAD

**Issue by pindec** [open-contracting/infrastructure#182]
Further to @duncandewhurst's comment  [here](https://github.com/open-contracting/infrastructure/pull/178#discussion_r340889614), I note the identifier field in the budgetBreakdown array also doesn't have minLength set to 1.

**Comment by jpmckinney** [comment]
We should maybe run the `schema-strict` command from OCDS Kit on the schema, to add this and other validation properties.

**Comment by pindec** [comment]
@jpmckinney should we add that to the pre-deploy list, and therefore no need to do it here? If so, we should also add a check of the example file to ensure it's still valid.

**Comment by jpmckinney** [comment]
`schema-strict` is only something we can run until version 1.0.0, so I'd rather add validation properties here and not make it an assumed part of schema deployment.
