### ISSUE TITLE
Don't allow integer type for identifiers

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#184]
Similar to https://github.com/open-contracting/standard/issues/789, OC4IDS also has some `id` fields which permit only strings and some which permit either strings or integers.

@jpmckinney given the early stage of implementations, should we fix this in 0.9.2 and make all `id` fields only permit strings?

**Comment by jpmckinney** [comment]
Yes, let's do it.

Edit: If this requires any changes to `borrow-schema.py` and you'd like any help, let me know.
