### ISSUE TITLE
Add document section to contractingProcesses

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/infrastructure#19]
After reviewing the **reactive disclosure** needs set out in the Infrastructure Data Standard, we identified that many may be provided through either:

* Text narrative or documents;
* Structured data fields within an extended OCDS release;

Recognising that it will not always be possible to provide that structured data, and that additional reactive disclosures are likely to be narrative in form, it would help to have a `documents` block at the level of the `ContractingProcess` object.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/infrastructure/commit/2cb7d69ba0cef41478dc170ce4dc9cd127780995
