### ISSUE TITLE
Update to latest profile template

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#207]
I can do this when we're ready to deploy. Updating now might interfere with the translation process.

**Comment by duncandewhurst** [comment]
@jpmckinney I think we're ready to create a PR for the 0.9.2 update. Do you need to do this first?

**Comment by jpmckinney** [comment]
Looks like I did it in 33c7c5e62d5eeac0f883d77386bba9d2da3fd6b4!

**Comment by jpmckinney** [comment]
Actually, noticing some things I might have been referencing.
