### ISSUE TITLE
Review business logic in contractingProcessStatus codelist

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#209]
Some cases aren't handled by the current logic, e.g.

```json
        {
            "ocid": "ocds-213czf-5",
            "id": "1",
            "tag": "planning",
            "date": "2001-02-03T04:05:06Z",
            "awards": [{"date": "3000-01-01"}],
            "tender": {"id": 1, "awardPeriod": {"startDate": "2000-01-01"}},
        },
```

```json
        {
            "ocid": "ocds-213czf-6",
            "id": "1",
            "tag": "planning",
            "date": "2001-02-03T04:05:06Z",
            "awards": [{"date": "2000-01-01"}],
            "tender": {"id": 1, "awardPeriod": {"startDate": "3000-01-01"}},
        },
```

**Comment by duncandewhurst** [comment]
The cases in this issue can be addressed by changing 'whether expressed as' to 'in order of preference' in the business logic for the 'pre-award' code. A similar change can be made to the logic for the 'active' and 'closed' codes. At the same time, we can add code formatting to the field paths for all codes:

| Code | Title | Description | Business Logic (Current) | Business Logic (Proposed) |
| -- | -- | -- | -- | -- |
| pre-award | Pre-award | No contract has yet been awarded, and the process has not ended. | tender.status is not 'cancelled', 'unsuccessful' or 'withdrawn', and one of: There are no awards or contracts; All Award.status and Contract.status are 'pending'; All award dates (whether expressed as award.date or tender.awardPeriod) are in the future. | `tender.status` is not 'cancelled', 'unsuccessful' or 'withdrawn', and one of: There are no awards or contracts; All `Award.status` and `Contract.status` are 'pending'; All award dates (in order of preference: `Award.date`, `tender.awardPeriod`) are in the future. |
| active | Active | A contract was awarded, but not all contracts have ended. | One of: There is at least one Contract.status of 'active'; At least one contract period (whether expressed as Contract.period, Award.contractPeriod or tender.contractPeriod) includes the present date. | One of: There is at least one `Contract.status` of 'active'; At least one contract period (in order of preference: `Contract.period`, `Award.contractPeriod`, `tender.contractPeriod`) includes the present date. |
| closed | Closed | The process ended with no contract being awarded, or all contracts have ended. | One of: tender.status is 'cancelled', 'unsuccessful' or 'withdrawn'; There is at least one award, and all Award.status are 'cancelled' or 'unsuccessful'; There is at least one contract, and all Contract.status are 'terminated' or 'cancelled'; The endDate of all contract periods are in the past. | One of: `tender.status` is 'cancelled', 'unsuccessful' or 'withdrawn'; There is at least one award, and all `Award.status` are 'cancelled' or 'unsuccessful'; There is at least one contract, and all `Contract.status` are 'terminated' or 'cancelled'; The `.endDate` of all contract periods (in order of preference: `Contract.period`, `Award.contractPeriod`, `tender.contractPeriod`), are in the past.

@jpmckinney does that sound good?

**Comment by duncandewhurst** [comment]
Once agreed, an issue can be opened to update the OCDS to OC4IDS transform in OC4IDS Kit: https://github.com/open-contracting/oc4idskit/issues

**Comment by jpmckinney** [comment]
Yes, order of preference is a good solution!
