### ISSUE TITLE
Docs generation: add in token replacement for codelist links

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/infrastructure#21]
For reasons of time, at present I've included codelist links in the schema on the assumption that they will be rendered on the same page as the codelist can be found. E.g:

```json
"description": "The current phase or status of this project, from the [projectStatus](#projectstatus) codelist.",
```

This will need replacing in the final version with absolute links, ideally which include tokens to allow version and language to be substituted at compile time. There is an established model in OCDS it should be possible to replicate.

**Comment by pindec** [comment]
Codelist links in the schema viewer are currently broken. 
Looks like they link to widget.js folder not schema folder.
e.g. projectStatus codelist link rendered in [schema page](https://open-contracting.github.io/infrastructure/projects/schema/) points to https://open-contracting.github.io/infrastructure/_static/docson/index.html#projectstatus
