### ISSUE TITLE
Review OCDS Kit's OC4IDS transform and update mapping

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#210]
Review the [logic](https://ocdskit.readthedocs.io/en/latest/cli/ocds.html#convert-to-oc4ids) used in the OCDS-OC4IDS transform for each mapping and update the mapping table in the OC4IDS docs as required.

In particular, improve the documentation for the project sector mapping to explain what is left to the reader.

**Comment by duncandewhurst** [comment]
> In particular, improve the documentation for the project sector mapping to explain what is left to the reader.

At the same time we can update the OC4IDS mapping column to explain that a code from the OC4IDS sector codelist should be used, since the description from the IDS mentions developing a list.

**Comment by pindec** [comment]
See also ocdskit convert-to-oc4ids issue [#165](https://github.com/open-contracting/ocdskit/issues/165)

**Comment by duncandewhurst** [comment]
For posterity, @pindec's notes from reviewing the mapping are in a [Google Doc](https://docs.google.com/document/d/1zJs64sY76O5-9YhFozgtlTd98YFiSGAFB8TOK176664/edit#).
