### ISSUE TITLE
Fix link to releaseTag codelist

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#213]
The link from the [codelist reference](https://standard.open-contracting.org/infrastructure/0.9-dev/en/reference/codelists/#ocds-codelists) points to the releaseTag codelist in the OCDS documentation, however OC4IDS uses the extended releaseTag codelist from OCDS for PPPs, so the link should point to that instead.

**Comment by jpmckinney** [comment]
OCDS for PPPs no longer edits the release tag codelist. open-contracting-extensions/ocds_ppp_extension#11
