### ISSUE TITLE
Add project.identifiers array

### ISSUE THREAD

**Issue by yolile** [open-contracting/infrastructure#214]
Currently project.id description is:

> A unique identifier or reference number for this infrastructure project.

And only if you go to the Implementation guidance section you will know that you should use the project identifier prefix, which leads is some confusion for some publishers that are used to the ocid in OCDS, so maybe we can update the project.id definition with something more like the ocid definition:

>  A globally unique identifier for this Open Contracting Process. Composed of an ocid prefix and an identifier for the contracting process. For more information see the Open Contracting Identifier guidance

cc @ElioenaiVazquez

**Comment by ElioenaiVazquez** [comment]
Considering that the project.id field will be used for the global identifier, there should be a field to indicate the local identifier. I propose that the project.id field be the local identifier and that a new field be added for the global identifier.

**Comment by duncandewhurst** [comment]
Thanks both!

This change is already staged for the next release of OC4IDS (see #160), where the description of the `id` field will be updated to:

> A unique identifier or reference number for this infrastructure project, composed of a project identifier prefix and a local project identifier. For more information, see the project identifier guidance.

Rather than changing the semantics of the existing field to be a local identifier, we can follow the pattern using for contracting processes and add an `.externalReference` field at the project level with the following description:

> If this project is identified by an external reference number or local identifier it may be recorded here.

@yolile @ElioenaiVazquez how does that sound?

**Comment by duncandewhurst** [comment]
Noting the SISOCS also maintains a local/external identifier

**Comment by ElioenaiVazquez** [comment]
Sounds great, descriptions and logic seem correct to me

**Comment by duncandewhurst** [comment]
The RICS Data Standard includes an array of identifiers for an infrastructure project:

![image](https://user-images.githubusercontent.com/19265814/140826696-495d6a89-c59f-4b0e-a06c-a78ed0d9e37b.png)

Based on this, I think the new field should be an array. We can choose a name that aligns with https://github.com/open-contracting/standard/issues/815

**Comment by duncandewhurst** [comment]
CoST West Lombok are using `externalReference` as originally suggested in this issue so if we decide on a different name then we should ask them to update their data.

**Comment by duncandewhurst** [comment]
@jpmckinney are you happy with the proposal in this issue?

To summarize:

* Add a `project.identifiers` array
* Reuse the `SimpleIdentifier` definition from OCDS 1.2

**Comment by jpmckinney** [comment]
Yes, sounds good.

Edit: And I assume we are using `identifiers` and not `additionalIdentifiers`, because there is no primary `identifier` field.

**Comment by odscrachel** [comment]
I think having an `id` field and an `identifiers` field might cause publishers some confusion (or those doing data entry who haven't read the standard), I suggest we use `id` and `additionalIdentifiers` instead. Would anyone object to this?

**Comment by jpmckinney** [comment]
Hmm, we have several cases of `id` with `identifier`, and, as in my previous comment, `additionalIdentifiers` doesn't make much sense in the absence of a primary `identifier`.

Identifiers are objects (id, scheme, etc.). `id` are strings for internal referencing. If this is a cause for confusion, let's address it in documentation, rather than in the field name.

**Comment by odscrachel** [comment]
True, okay, we will go ahead with the original proposal and address any potential confusion in the documentation.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/infrastructure/pull/390
