### ISSUE TITLE
Add example flatten-tool command to documentation

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#215]
The guidance on [publishing data from an infrastructure transparency portal](https://standard.open-contracting.org/infrastructure/0.9-dev/en/guidance/publishing/#publish-your-data) currently references using flatten-tool to generate CSV and Excel version of the data.

Since the flatten-tool docs don't have any OC4IDS specific content, we should include an example command, e.g.

> The following command will generate an Excel format version of an OC4IDS project package JSON file, you can test it using the [example file](https://standard.open-contracting.org/infrastructure/latest/en/_static/example.json) from the OC4IDS documentation:
> 
> ```
> flatten-tool flatten -f xlsx example.json --root-id=id --root-list-path=projects
> ```

**Comment by odscrachel** [comment]
+1 This would be helpful
