### ISSUE TITLE
Separate the IDS and OCDS mappings

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#216]
The [IDS and OCDS mapping](https://standard.open-contracting.org/infrastructure/latest/en/cost/#mapping-to-ids-and-from-ocds) is serving two purposes:

1. Describing how to disclose each element of the CoST IDS using OC4IDS
2. Describing how to populate an OC4IDS file when you have access to OCDS data

Since those relate to two quite distinct use cases (disclosing data which complies with the CoST IDS and using OCDS data for infrastructure project monitoring) and given the potential for confusion about OC4IDS/OCDS implementation, I think it would be best to separate them.

This will also make it easier to:

1. Extend the IDS mapping to cover the reactive disclosure elements
2. Improve the coverage of the OCDS mapping and integrate the improvements/clarifications identified in the course of developing OCDSKit's convert-to-oc4ids feature.

@jpmckinney @LindseyAM @nadineFernz @pindec @yolile @romifz - what do you think?

**Comment by pindec** [comment]
Yes, I agree this would be helpful, given the distinct use cases.

**Comment by jpmckinney** [comment]
Yes, sounds good to me!

**Comment by romifz** [comment]
Sounds good for me as well.

**Comment by LindseyAM** [comment]
Would like to preserve this mapping of OCDS -> OC4IDS -> CoST IDS 

We have a strong use case for its existence in Afghanistan and I can envision more demand for this guidance down the road. 

Would propose we have one table that presents IDS -> OC4IDS  and then another table that presents OCDS -> OC4IDS -> Cost IDS (accompanied by link and guidance on how to use OCDS KIT to convert).

**Comment by jpmckinney** [comment]
@LindseyAM Can you clarify the use case in Afghanistan?

@duncandewhurst Are you anticipating any change in the structure of the source CSV files, or only a change in how those files are rendered in the documentation?

If there's no change in structure, then we can have tables rendered with different sets of columns and different column orders, on different pages, to satisfy all use cases.

**Comment by duncandewhurst** [comment]
I think it can be achieved whilst keeping a single source table, but I'll need to work through how to integrate the improvements and clarifications from convert-to-oc4ids to be sure.

**Comment by LindseyAM** [comment]
Integrity Watch Afghanistan is advocating for the NPA to become an OC4IDS publisher. NPA agreed but wants to prioritize completing their work on OCDS first. The next thing they are finishing is the tender module of their eGP (and the related OCDS publication).  Then, it seems like it would be a good candidate to convert to OC4IDS and fill in the gaps.
