### ISSUE TITLE
Docs generation: deploying as an OCDS profile or stand-alone site?

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/infrastructure#22]
At present, we're hosting the draft documentation using GitHub pages, because I could not work out whether it was possible to run the `make` scripts on a ReadTheDocs infrastructure, nor how to quickly set-up travis etc. to deploy docs.

This means that (a) we can easily deploy one copy on GitHub Pages right now; (b) the gh-pages branch has to be manually updated with the output of a locally run build. 

My current workflow for that has been to have two copies of the repo checked out, one as /infrastructure/, and one as /gh-pages/, and then to:

* Run `make` in /infrastructure/
* Switch to the parent directory, and run the following commands

```
cd gh-pages
git checkout gh-pages
git rm -rf *
cp -R ../infrastructure/build/en/* .
git checkout master -- README.md
git checkout master -- LICENSE
git checkout master -- assets
echo "" > .nojekyll
git add *
```

* Commit the changes in /gh-pages/ and push live

This is a hacky stop-gap, and so it would be good to identify how documentation should be deployed and hosting in future, particularly before lots of people are linking to the temporary github pages location.

**Comment by duncandewhurst** [comment]
I've just edited Tim's instructions, to include switching to the gh-pages branch, otherwise changes will be pushed to the master branch

**Comment by duncandewhurst** [comment]
Related to #26

**Comment by duncandewhurst** [comment]
Docs are now deployed with Travis and a redirect from the old github pages location has been set up.
