### ISSUE TITLE
`documentType` description in schema links to OCDS for PPP codelist

### ISSUE THREAD

**Issue by romifz** [open-contracting/infrastructure#221]
In development version. Is this right?

**Comment by duncandewhurst** [comment]
Ah, good spot. `party/roles` has the same issue.

The descriptions previously pointed to the OC4IDS codelists, but it looks like the PPP links were introduced by running `borrow-schema.py` in https://github.com/open-contracting/infrastructure/commit/9ae90e0e738cfc0f745c6eafb52703cf563a1304

I've updated `borrow-schema.py` to replace the links with the correct OC4IDS ones
