### ISSUE TITLE
Docs version warning refers to OCDS not OC4IDS

### ISSUE THREAD

**Issue by pindec** [open-contracting/infrastructure#224]
When viewing a development version of the docs, e.g. [dev master here](https://standard.open-contracting.org/infrastructure/master/en/), the warning at the top reads:

"This is a development copy of the **OCDS** docs, the latest live version is 1.1."

This should say OC4IDS.

**Comment by jpmckinney** [comment]
I can fix this in the deploy repository.

**Comment by jpmckinney** [comment]
Done.
