### ISSUE TITLE
Upgrade to OCDS 1.1.5

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#235]
~~Very simple steps: https://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/technical/build.html~~

**Comment by duncandewhurst** [comment]
`build-profile.py` doesn't exist in OC4IDS and I don't think `standard_tag` set in `conf.py` is used anywhere.

The correct steps for OC4IDS are:

1. Upgrade OCDS for PPPs to the latest version of OCDS
2. Run `make clean_dist` then `python schema/borrow-schema.py`

Edit: The updated version of OCDS for PPPs needs to be deployed before running `borrow-schema.py`.

**Comment by jpmckinney** [comment]
Thanks! Once we update OCDS for PPPs, we can return to this issue.

https://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/infrastructure.html#development-tasks

**Comment by jpmckinney** [comment]
@duncandewhurst Ideally, OC4IDS 0.9.3 would align with the new version of OCDS for PPPs, which only has a few issues left.
