### ISSUE TITLE
Add maintenance code to projectType codelist, update code descriptions and add typeDetails field

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#237]
CoST Ukraine uses the World Bank's classification for road project types which has the following codes (these were shared via email, I've asked for a link to where the classification is documented):

Project Type | Description
-------------------------------------|----------------
Construction | The primary focus of this project is the construction of a new road
Rehabilitation | The primary focus of this project is the rehabilitation of an existing asset
Upgrade | Comprehensive restoration of transport and operational parameters of the road taking into account the growth of traffic intensity and axial loads, increasing the strength of the road structure without changing the technical category.
| Periodic Maintenance | Major repairs or rehabilitation of those parts of the highway that have deteriorated over the years. The frequency involves intervals of some years. The activities include surface dressing or resealing and re-gravelling of shoulders for paved roads and re-gravelling for unpaved roads.
| Routine Maintenance | Routine maintenance is required to be carried out continually on every road, irrespective of its engineering features or volume of vehicular traffic. Routine maintenance expenses are typically treated as fixed-cost items in the maintenance budget. They include lane marking, drainage clearing, basic maintenance of culverts and bridges, grass cutting and so on.
Recurrent Maintenance | This is required at intervals during the year. The frequency of this maintenance depends on the topographic and climatic characteristics of the area and the volume of traffic on the road. It involves maintenance of pavements for paved roads, repairing of potholes and (for unpaved roads) grading.
| Winter Maintenance | This includes gritting, snow clearance and related storage and possible further disposal.

Construction and Rehabilitation have equivalent codes in the [project type codelist](https://standard.open-contracting.org/infrastructure/latest/en/reference/codelists/#projecttype) and Periodic Maintenance seems to map to 'rehabilitation' in OC4IDS. To model the other project types in OC4IDS we would need to:

* Add 'upgrade' and 'maintenance' codes to the project type codelist
* Add a `typeDetails` field at the project level, which publishers can use to provide a more detailed breakdown of the project type using the codes from their local classifications, e.g. subdividing maintenance into routine, recurrent or winter maintenance.

Routine, Recurrent and Winter maintenance seem to stretch the definition of an infrastructure project ("the development of a set of infrastructure assets in a specified location") however if there is a use case for CoST programmes to include such work in the same dataset as other project types, then OC4IDS should support that.

@nadinefernz, @evelyndinora, @jpmckinney - are you happy with the proposal?

Also, we should improve the descriptions in the project type codelist, as presently these just restate the title of the code. I'll open an issue.

**Comment by jpmckinney** [comment]
"upgrade" sounds a bit like 'expansion' ("taking into account the growth of traffic intensity and axial loads, increasing the strength of the road structure").

I'm not clear on the difference between routine and recurrent maintenance. Anyhow, we'll need to be careful in distinguishing 'rehabilitation' from 'maintenance'.

**Comment by duncandewhurst** [comment]
> "upgrade" sounds a bit like 'expansion' ("taking into account the growth of traffic intensity and axial loads, increasing the strength of the road structure").

Yes, that was my initial thought, but there seems to be a distinction between upgrading the road "without changing the technical category" and other types of project, which by inference might change the category of the road, e.g. adding a lane. I suspect the definitions of construction and rehabilitation in the full classification might help to clarify, or perhaps Evelyn or Ben can advise.

> I'm not clear on the difference between routine and recurrent maintenance.

My reading was that the distinction is based on whether the frequency is fixed or dependent on weather conditions, volume of traffic etc. In any case, I think it's OK to have a maintenance code and leave the distinctions to the `.typeDetails` field.

> Anyhow, we'll need to be careful in distinguishing 'rehabilitation' from 'maintenance'.

Agreed.

**Comment by EvelynDinora** [comment]
Hi, 

I had an internal discussion before responding to you and I could get the following explanation:


Periodic Maintenance, such as re-gravelling, or surface dressing, is carried out proactively on a planned basis shortly before visible signs of distress and defects, though the underlying deterioration can be detected and predicted through a testing regime including - in the case of sealed roads - deflection tests.   By contrast, Rehabilitation occurs reactively after significant distress become visible, so requires a wider range of different interventions typically including partial reconstruction of the underlying pavement.   As a result, Rehabilitation is much more expensive, and generally represents poor value for money, suggesting a failure in asset management systems or related capacity.  Unlike Upgrading, neither Periodic Maintenance nor Rehabilitation entail any change to the road standard.

**Comment by EvelynDinora** [comment]
We know that they have something in common, but they are clearly different types of intervention:

Maintenance and rehabilitation are used to slow down or reset deterioration process.  
Maintenance actions help slow the rate of deterioration by identifying and addressing specific deficiencies that contribute to overall deterioration.  
Rehabilitation is the act of repairing portions of an existing assets to reset the deterioration process. 

I think we will need either to extend the list or to covert it in an open list. What do you think @jpmckinney and @duncandewhurst?

**Comment by duncandewhurst** [comment]
Thanks @EvelynDinora, that's a really helpful clarification.

Based on your feedback and @jpmckinney's suggestion to map 'upgrade' to 'expansion' we could update the project type codelist as follows (changes in *italics*):

**Project type codelist**

Code | Title | Description
-- | -- | --
construction | Construction | The primary focus of this project is the construction of a new asset.
rehabilitation | Rehabilitation | The primary focus of this project is *reactively addressing significant deficiencies in an existing asset to stop the asset deteriorating further.*
replacement | Replacement | The primary focus of this project is the replacement of an existing asset.
expansion | Expansion | The primary focus of this project is the expansion *or upgrade* of an existing asset.
*maintenance* | *Maintenance* | *The primary focus of this project is proactively identifying and addressing deficiences in an existing asset to slow the rate of deteriation of the asset.*

CoST Ukraine could map their project types to the above codelist so that the data is interoperable and publish the original values in a `.typeDetails` field so that users can still filter on the same project types shown in the portal:

**CoST Ukraine mapping**

CoST Ukraine Project Type | OC4IDS Project Type
-- | --
Construction | construction
Rehabilitation | rehabilitation
Upgrade | expansion
Periodic Maintenance | maintenance
Routine Maintenance | maintenance
Recurrent Maintenance | maintenance
Winter Maintenance | maintenance

This approach would allow us to keep the codelist closed, rather than mixing levels of detail in one open codelist. Do you think the proposed project type codelist is appropriate as a comprehensive list of project types for all kinds of infrastructure projects (i.e. not only roads)?

@jpmckinney what do you think?

For reference https://github.com/open-contracting/infrastructure/issues/17 has the background on the project type field.

**Comment by jpmckinney** [comment]
I like the proposed approach.

**Comment by EvelynDinora** [comment]
I agree with the approach too.

In case we need the definitions for Maintenance sub-categories I have asked my colleagues to provide something acceptable from a technical perspective:

Routine Maintenance
Routine maintenance entails work that is required to be carried out continually (often on a rolling basis) on every road, irrespective of its engineering features or volume of vehicular traffic. Routine maintenance expenses are typically treated as fixed-cost items in the maintenance budget. They include lane marking, drainage clearing, bridge and culvert inspections and related minor maintenance and repairs, and grass cutting.

Recurrent Maintenance
This is required at intervals during the year. The frequency of this maintenance depends on the topographic and climatic characteristics of the area and the volume of traffic on the road. For both paved and unpaved roads it entails the repair of minor potholes and other surface defects, and for unpaved roads also includes grading.

Periodic Maintenance
This involves major repairs of those parts of the road that have deteriorated over a sustained period. The frequency typically involves intervals of 4 to 7 years. The activities include surface dressing or resealing and re-gravelling of shoulders for paved roads and re-gravelling for unpaved roads.

Emergency Maintenance
This maintenance is carried out beyond routine, recurrent and periodic maintenance. In many countries it is prompted mainly by unexpected substantial landslides, when a road is abruptly cut or a bridge washout occurs. Or it could be required in response to a seismic event or major accident.

Winter Maintenance
This maintenance is weather dependent, and generally consists of a combination of gritting and snow clearance, carried out in response to weather forecasts and road conditions.  Though closely associated with winter, post-winter pothole repairs are normally classified as recurrent maintenance, though sometimes unused winter maintenance budgets can be used for this purpose.

If it is too much detailed please ignore the above.

**Comment by duncandewhurst** [comment]
Thanks, both.

I've suggested CoST Ukraine use this approach and include the descriptions provided by @EvelynDinora in their publication policy.

In terms of including the additional descriptions as a codelist, we'd need to think about how to do that exactly since they are specific to roads, but we could certainly include them in the documentation.

**Comment by duncandewhurst** [comment]
CoST would like to include the proposed changes in the 0.9.5 release. We'll need to check the proposed codes, titles and descriptions for alignment with the updated project definition and project status codelist added in 0.9.4.

**Comment by odscjen** [comment]
The proposed projectType code `maintenance` is in keeping with the updated project definition, however we did add a new `projectStatus` code also called `maintenance` as part of the already completed 0.9.5 upgrades. It's definition is
> Maintenance covers any preventative or corrective maintenance and the day-to-day running of the assets. This stage is also called operation.

Comparing that to the proposed `projectType` code for `maintainence`
> The primary focus of this project is proactively identifying and addressing deficiences in an existing asset to slow the rate of deterioration of the asset.

It's missing the element of prevention, i.e. identifying issues before they actually become a deficiency. Given that the proposed updated `rehabilitation` code is covering "significant deficiencies" should this maintenance be changed to:
> The primary focus of this project is proactively identifying and addressing **potential and minor** deficiencies in an existing asset to slow the rate of deterioration of the asset."?

The updated project definition is also missing any reference to rehabilitation. This could be a simple insert into the existing definition list:
> The development, maintenance, **rehabilitation** and decommissioning of a set of infrastructure assets in a specified location, generally the responsibility of a single procuring entity and budget authority: for example, a highway overpass or a university campus. Development covers project identification, preparation, implementation and completion.

Aside: Noticed that the project definition hasn't been updated in https://standard.open-contracting.org/staging/infrastructure/latest/en/reference/schema/#project

@duncandewhurst @EvelynDinora @jpmckinney

**Comment by jpmckinney** [comment]
For my part, I think this requires more domain-specific knowledge than I have.

That said, I would omit "potential and" as I'm not clear on how a potential deficiency can be addressed.

It'll be easier to review all projectType updates as a group, to check for consistency and lack of ambiguity.

I guess it's fine to have overlap between projectType and projectStatus, since perhaps the maintenance comes so many years after the original project, that operationally it is effectively like a new project. This is where domain-specific knowledge would help, as I don't know where practitioners draw the line here. But, since we already have an "rehabilitation" project type, I guess it falls into the same logic (i.e. too much time has passed, so it's a new project, even if it's the same asset). Note that the project definition doesn't allow for this ambiguity. According to the definition, projects are asset-based, and all activity with respect to the assets are the same project.

**Comment by duncandewhurst** [comment]
> I guess it's fine to have overlap between projectType and projectStatus, since perhaps the maintenance comes so many years after the original project, that operationally it is effectively like a new project. This is where domain-specific knowledge would help, as I don't know where practitioners draw the line here. But, since we already have an "rehabilitation" project type, I guess it falls into the same logic (i.e. too much time has passed, so it's a new project, even if it's the same asset). Note that the project definition doesn't allow for this ambiguity. According to the definition, projects are asset-based, and all activity with respect to the assets are the same project.

That's how I've been thinking about decommissioning, which I understand is typically treated as a separate project. I'd been reading the definition as allowing for that possibility, but on re-reading I see that we should probably replace 'and' with 'and/or':

> the development, maintenance **and/or** decommissioning of a set of infrastructure assets in a specified location, generally the responsibility of a single procuring entity and budget authority: for example, a highway overpass or a university campus. Development covers project identification, preparation, implementation and completion.

Regarding adding rehabilitation to the project definition, if we add that, I think we should probably add replacement and expansion, too. Similar to above, I'd previously been reading 'development' as a synonym for any of the project types, but now that we've added explicit references to maintenance and decommissioning, I think that we should be consistent.

**Comment by jpmckinney** [comment]
Sounds good!

**Comment by odscjen** [comment]
Thanks both. Looking again at the `maintenance` codes I think the use of the word "proactively" in the `projectType` code definition covers the "preventative" aspect from the `projectStatus` code so agree that we don't need to add the "and potential" that I'd previously suggested. Additionally the use of the word "reactively" in the `rehabilitation` code distinguishes  this code from `maintenance` and so I don't think we need to add "minor" to the `maintenance` code either and it is still consistent with the `projectType` code of the same name.

So I think what we're saying is the following changes need made:

**Project type codelist**

Code | Title | Description
-- | -- | --
construction | Construction | The primary focus of this project is the construction of a new asset.
rehabilitation | Rehabilitation | The primary focus of this project is *reactively addressing significant deficiencies in an existing asset to stop the deterioration of the asset.*
replacement | Replacement | The primary focus of this project is the replacement of an existing asset.
expansion | Expansion | The primary focus of this project is the expansion *or upgrade* of an existing asset.
*maintenance* | *Maintenance* | *The primary focus of this project is proactively identifying and addressing deficiencies in an existing asset to slow the deterioration of the asset.*

Project definition
> The development, maintenance, *rehabilitation, expansion, replacement and/or* decommissioning of a set of infrastructure assets in a specified location, generally the responsibility of a single procuring entity and budget authority: for example, a highway overpass or a university campus. Development covers project identification, preparation, implementation and completion.

@EvelynDinora @jpmckinney @mgraca-prado

**Comment by jpmckinney** [comment]
Looks good. We can simplify to "slow the ~~rate of~~ deterioration", and then reword as "stop the +deterioration of+ the asset ~~deteriorating further~~", to mirror that construction.

**Comment by odscjen** [comment]
good suggestions, I've updated the definitions in the table accordingly
