### ISSUE TITLE
Check that a csv is present for all codelists referenced in the schema 

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#24]
@jpmckinney spotted a duplicated `copy_codelist` reference in https://github.com/open-contracting/infrastructure/commit/bc54cee59a2ffa3f01eac0a57f201985514f7a60#r30849020

Before deploying the beta version we should check that all codelists referenced in the schema have an associated codelist csv, in case the duplicate should have referenced a different codelist

**Comment by jpmckinney** [comment]
I ran the maintenance scripts, which detected no missing codelists.
