### ISSUE TITLE
Add approvalDate to BudgetBreakdown object

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#242]
In CoST Ukraine's platform, an infrastructure project can have multiple funding sources, each with their own approval date. For [example](https://costportal.mtu.gov.ua/tblpub/PROJECTS.php?hname=dbo_PROJECTS_dbo_PROJECTS_FINANCING_handler&fk0=13524&master_viewmode=0):

![image](https://user-images.githubusercontent.com/19265814/96780230-1e647400-1449-11eb-8af4-cfce5179bf3b.png)

This can occur when:

* a project spans multiple years, with a separate budget approval for each year;
* multiple entities contribute funds to a project (e.g. a local administration funds the project development and design and a regional administration funds the construction), with a separate budget approval for each entity;
* a single entity uses funding from different sources (e.g. the Ministry of Infrastructure might use funds from its regular budget, funds from the [Stockholm arbitration](https://www.ft.com/content/47bcd385-9eca-309b-b018-18423a05b11c) award and funds from the COVID-19 recovery fund), with a separate budget approval for each source

In OC4IDS, the total value of the budget is represented using `budget/amount` and the breakdown by funding source is represented using the `budget/budgetBreakdown` array of [BudgetBreakdown](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#budgetbreakdown) objects.

However, OC4IDS only has one `budget/approvalDate` per project, so the multiple approval dates in CoST Ukraine's portal can't be represented.

# Proposal

Add an `approvalDate` property to the `budgetBreakdown` object with the following description:

> The date on which this budget entry was approved. Where documentary evidence for this exists, it may be included among the project documents with `documentType` set to 'budgetApproval'.

**Comment by jpmckinney** [comment]
Looks good to me!

**Comment by duncandewhurst** [comment]
Noting that we lack a means to link documents tagged with 'budgetApproval' to specific `BudgetBreakdown` objects. cc @pindec

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/infrastructure/pull/367
