### ISSUE TITLE
Add classification scheme codelist with SDG and SDGTarget codes

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#244]
Similar to https://github.com/open-contracting/standard/issues/1098, [SIF SOURCE](https://public.sif-source.org/source/) tags infrastructure projects with the SDGs the project targets.

`additionalClassifications` can be used to model this data in OC4IDS, but we should add a codelist for `.scheme` so that publishers use a consistent scheme code for SDGs.

**Comment by duncandewhurst** [comment]
Example (shared in CRM-6710):

```json
{
  "projects": [
    {
      "additionalClassifications": [
        {
          "description": "Gender equality",
          "id": "5",
          "scheme": "SDG"
        },
        {
          "description": "Decent work and economic growth",
          "id": "8",
          "scheme": "SDG"
        }
      ]
    }
  ]
}
```

**Comment by duncandewhurst** [comment]
@jpmckinney are you happy with the proposal in this issue?

**Comment by jpmckinney** [comment]
Yes, sounds fine.

**Comment by odscrachel** [comment]
Hi @jpmckinney, I'm working on a PR for this issue but 'SDGTarget' does not match the current regex as it is not in camelCase. Using upper case letters for initialisms is consistent with the item classification scheme codelist: https://standard.open-contracting.org/latest/en/schema/codelists/#item-classification-so so I wanted to check if we should update the tests here or use camelCase?

**Comment by jpmckinney** [comment]
The [codelist schema](https://github.com/open-contracting/standard-maintenance-scripts/blob/main/schema/codelist-schema.json) has for the Code column:

> The value to use in OCDS data. Codes should match the letter case of external codes (e.g. ISO 4217, JSON Schema, GeoJSON, IANA Media Types) and should be camel case, otherwise.

We've made exceptions for all-caps, for sub-codes ('abc.xyz'), for codes like 'foreignBidsFromEU', etc. We can make an exception here, but I don't mind 'sdgTarget'.

**Comment by odscrachel** [comment]
Great, we'll stick to 'sdgTarget'

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/infrastructure/pull/369
