### ISSUE TITLE
Broken link to budgets and projects extension

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#246]
The [project identifiers in OCDS guidance](https://standard.open-contracting.org/infrastructure/latest/en/guidance/identifiers/#project-identifiers-in-ocds) has a broken link to https://extensions.open-contracting.org/en/extensions/budget_project/

The link should be https://extensions.open-contracting.org/en/extensions/project/master/

I'm pretty sure this was working previously, so the URL must have changed.

**Comment by jpmckinney** [comment]
Yes, the project extension has nothing to do with budgets, to the name was changed.

**Comment by aguilerapy** [comment]
This fix was not deployed or something? Because the [Budget and Projects extension](https://extensions.open-contracting.org/en/extensions/budget_project/) link in https://standard.open-contracting.org/infrastructure/latest/en/guidance/identifiers/#project-identifiers-in-ocds is still broken.

**Comment by duncandewhurst** [comment]
It's fixed in 0.9.3 (https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/guidance/identifiers/#project-identifiers-in-ocds) which has just been shared for public feedback
