### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/infrastructure#247]
I noticed that the OC4IDS standard website doesn't yet have a favicon tab icon. Is this something we should add? Firefox doesn't show a default, so it's easy to lose when a lot of tabs are open.

If we create one, I suggest that we make it a crane :)

**Comment by jpmckinney** [comment]
In the short term I think we just need to add `html_favicon = '_static/favicon-16x16.ico'` to `conf.py` like in the standard docs to get our regular favicon. Creating a new favicon would involve agreeing a logo between OCP and CoST, which will not be a short affair :)
