### ISSUE TITLE
Add a field to indicate whether a project is an unsolicited proposal

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#249]
SIF's SOURCE platform includes a boolean `Unsolicited Project` field, to indicate whether a project resulted from an [unsolicited proposal](https://ppp.worldbank.org/public-private-partnership/ppp-overview/ppp-procurement-bidding/unsolicited-proposals/unsolicited-proposals).

**Comment by jpmckinney** [comment]
In OCDS, this would broadly fall under the semantics of `tender/procurementMethodDetails` (the name of the field obviously not being friendly to non-procurement contracts).

**Comment by duncandewhurst** [comment]
My understanding is that, in SOURCE, this information relates to planning the project as a whole so there likely wouldn't be any entries in the `contractingProcesses` array at that stage.

**Comment by jpmckinney** [comment]
I meant in terms of an analogue that can be added to the Project object.

**Comment by duncandewhurst** [comment]
[ANZIP](https://infrastructurepipeline.org/) includes a `Procurement Approach` field which mixes various concepts but includes some values relevant to this issue:

* **Market Led Proposal**
* Confirmed PPP
* Traditional Procurement
* Possible PPP
* Alliance
* Privatisation
* Unconfirmed
* Operations & Maintenance
* Power Purchase Agreement

**Comment by duncandewhurst** [comment]
> I meant in terms of an analogue that can be added to the Project object.

Adding an example, based on SOURCE's data:

```json
{
  "projects": [
    {
      "procurementMethodDetails": "PPP/Concession"
    }
  ]
}
```

**Comment by jpmckinney** [comment]
Can we merge with #248?

We can consider renaming the field, since its values are broader than in OCDS.

**Comment by duncandewhurst** [comment]
> Can we merge with #248?
> 
> We can consider renaming the field, since its values are broader than in OCDS.

Yes, sure.

**Comment by jpmckinney** [comment]
I've updated #248 with this issue's description and updated my first comment.
