### ISSUE TITLE
Add specific fields for project stage start and end dates

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#252]
SIF's SOURCE platform includes the following fields for start and end dates for project stages:

* Project_Definition_Start_Date
* Project_Definition_End_Date
* Project_Preparation_End_Date
* Procurement_End_Date
* Construction_End_Date
* O&M_End_Date

These stages mostly seem to map to the stages in the CoST IDS:

SOURCE stage | SOURCE description | IDS stage | IDS description
-- | -- | -- | --
Definition | The description of the strategic context in which the project lies as well as the identification its key characteristics and stakeholders (ends with the decision to mobilise resource for project appraisal) | Identification | the decision to develop a project within the budget and programme of a project owner.
Preparation | TBC | Preparation | The feasibility study, environmental and social impact assessment, general scoping of the project, establishing the packaging and procurement strategy, preliminary statutory requirements on environmental and land impacts, and the resulting budget authorization.
Procurement | TBC | Procurement | The procurement of the planning, design and works according to the procurement strategy.
Construction | TBC | Implementation | The implementation of the planning, design and works according to the procurement strategy.
Operation & Maintenance | TBC | n/a | n/a

**Proposal**

Add the following `Period` objects to the OC4IDS schema:

path | name | description
-- | -- | --
`identificationPeriod` | Identification Period | Identification of key project characteristics and stakeholders, and the decision to develop the project within the budget and programme of the project owner. Also known as project definition.
`preparationPeriod` | Preparation Period | The feasibility study, environmental and social impact assessment, general scoping of the project, establishing the packaging and procurement strategy, preliminary statutory requirements on environmental and land impacts, and the resulting budget authorization.
`procurementPeriod` | Procurement Period | The procurement of the planning, design and works according to the procurement strategy.
`implementationPeriod` | Implementation Period | The implementation of the planning, design and works according to the procurement strategy.
`operationAndMaintenancePeriod` | Operation and Maintenance Period | The technical operation, maintenance and/or provision of services relating to the infrastructure asset

Alternatively, we could add a flexible `milestones` array at the project level and use `Milestone.Code` to identify the end of each stage. However, given the close alignment between SOURCE and the CoST IDS, I think explicit fields should be OK and will be easier for users.

**Comment by jpmckinney** [comment]
I'm okay with the first four since they match IDS, but I'd prefer to leave the last in milestones until we have more evidence from more jurisdictions.

**Comment by duncandewhurst** [comment]
ANZIP includes expected and actual construction commencement and completion dates, which could map to `implementationPeriod`

**Comment by duncandewhurst** [comment]
The CoST IDS/OC4IDS review proposes adding the start and end dates of the decommissioning period so I figure we may as well address this issue at the same time.

<details> <summary> Decommission period </summary>

## Decommission period

**Module:** Climate finance
**Indicator:** Stranded assets

### Disclosure format

> Intended start and end dates of decommissioning.

### OC4IDS mapping

TBC

</details>

@jpmckinney, some modelling questions:

1. Regarding https://github.com/open-contracting/infrastructure/issues/252#issuecomment-748741415, now that the IDS is being expanded to include operation and decomissioning (see https://github.com/open-contracting/infrastructure/issues/391 and https://github.com/open-contracting/infrastructure/issues/394), are you happy to add the operation and decommissioning periods as explicit fields, rather than milestones?
2. To align with the stages in the CoST IDS, should we also add a completion period field?
3. What do you think about grouping all of these stage fields under an object, e.g.

```json
{
  "stagePeriods": {
    "identification": {
      "startDate": "",
      "endDate": ""
    },
    "preparation": {
      "startDate": "",
      "endDate": ""
    },
    "procurement": {
      "startDate": "",
      "endDate": ""
    },
    "implementation": {
      "startDate": "",
      "endDate": ""
    },
    "completion": {
      "startDate": "",
      "endDate": ""
    },
    "operation": {
      "startDate": "",
      "endDate": ""
    }
    "decomissioning": {
      "startDate": "",
      "endDate": ""
    }
  }
}
```

**Comment by jpmckinney** [comment]
Okay to add fields for each stage.

I don't see a strong benefit to adding hierarchy. Ideally, a JSON object should match a real-world concept. In this case, it's just a grouping with no equivalent outside the JSON.

**Comment by duncandewhurst** [comment]
I should've explained my reasoning - I had thought it might be helpful to have them under one object so that they are not scattered amongst other fields if a publisher, user or tool sorts keys in a different order to the OC4IDS schema, but I'm happy to have them all at the top level.

**Comment by jpmckinney** [comment]
I think it's better not to mix presentation layer concerns into the data layer. Ideally, a tool should apply a reasonable order to fields, rather than use the order in the data.

Grouping fields can still be useful if it's expected that users of this data will be reading JSON visually. However, the schema is so large, that I don't expect this to be a frequent use case (moreso for us when validating data).

Other than `Organization.details` in OCDS, I'm not sure that we've added extra layers elsewhere. That said, there could perhaps be a way of encapsulating these periods such that the object doesn't seem as "extra" as `stagePeriods`. The only thing that comes to mind is something resembling `milestones`, but that would bring us to `stages`, where I would expect each entry to be `Stage` object that contains more information than just its period.

**Comment by duncandewhurst** [comment]
> The only thing that comes to mind is something resembling `milestones`, but that would bring us to `stages`, where I would expect each entry to be `Stage` object that contains more information than just its period.

That was my thinking, too, but since the schema mostly isn't structured around the stages otherwise, I figured it would be confusing to introduce that approach only for the dates.

Let's keep them at the top-level.

**Comment by duncandewhurst** [comment]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details> <summary> Decommission period </summary>

## Decommission period

**Module:** Climate finance
**Indicator:** Stranded assets

### Disclosure format

> Intended start and end dates of decommissioning.

### OC4IDS mapping

TBC

</details>

<details> <summary> Project preparation period (preparation) </summary>

## Project preparation period (preparation)

**Module:** Climate finance
**Indicator:** Accessibility/efficiency

### Disclosure format

> Disclose dates for project preparation [start date, end date] 

### OC4IDS mapping

TBC

</details>

I've updated the proposal below to reuse the latest descriptions for each stage from https://github.com/open-contracting/infrastructure/issues/391. I've also omitted the procurement stage so that the fields in this proposal align with the project-level stages.

# Proposal

Add the following fields:

path | title | description | type (format) | codelist
-- | -- | -- | -- | --
`identificationPeriod` | Identification Period | Identification refers to the decision to develop a project within the budget and programme of a project owner (the public entity responsible for executing the budget). This stage is also called definition. | `Period` object | 
`preparationPeriod` | Preparation period | Preparation covers the feasibility study, environmental and social impact assessment, general scoping of the project, establishing the packaging and procurement strategy, preliminary statutory requirements on environmental and land impacts, and the resulting budget authorization. | `Period` object | 
`implementationPeriod` | Implementation period | Implementation covers the procurement and implementation of the group of works or services (such as design and supervision) to be delivered under the project, including works or services performed by the procuring entity. This differs from the definition of 'implementation' in OCDS, which covers the implementation but not the procurement. This stage is also called construction. | `Period` object | 
`completionPeriod` | Completion period | Completion covers the handover of the assets and close-out activities with details of the final scope, cost, and delivery time before operation. | `Period` object | 
`maintenancePeriod` | Maintenance period | Maintenance covers any preventative or corrective maintenance and the day-to-day running of the assets. This stage is also called operation. | `Period` object | 
`decommissioningPeriod` | Decommissioning period | Decommissioning covers the disposal of the assets at the end of their service life. This stage is also called end of life. | `Period` object | 

# Example

```json
{
  "preparationPeriod": {
    "startDate": "2024-01-01T00:00:00Z",
    "endDate": "2024-12-31T00:00:00Z"
  }
}
```

# Sources

* https://github.com/open-contracting/infrastructure/issues/391: Field names, titles and descriptions

cc @evelyndinora @mgraca-prado

**Comment by duncandewhurst** [comment]
Noting that this proposal will need updating to reflect the change from 'operation' to 'maintenance' as discussed in #391 and #394

**Comment by duncandewhurst** [comment]
> Noting that this proposal will need updating to reflect the change from 'operation' to 'maintenance' as discussed in #391 and #394

We agreed on the change so I've updated the proposal and will move this issue to agreed.
