### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#26]
I've updated and simplified the default build process for OCDS documentation. However, when trying to write a PR for this repo, I'm confused that requirements.in uses an unpinned version of Sphinx, and a version of recommonmark that is incompatible with the rest of our tooling. Is requirements.in in use, and if not can it be deleted?

The repository also omits Babel configuration files, which are required to support the translation of codelists and schema. I assume this omission isn't deliberate?

If my assumptions are correct, I'm happy to proceed with a PR.

**Comment by jpmckinney** [comment]
Are 'schema browser' and 'docson' the same thing? In `standard`, 'docson' is checked out into the appropriate directory, through a `.gitmodules` file with the contents:

```
[submodule "standard/docs/en/_static/docson"]
	path = standard/docs/en/_static/docson
	url = https://github.com/OpenDataServices/docson
	branch = master
```

For this repo, I think we'd change `standard/docs/en/_static/docson` to `_static/docson`. If you then run `git submodule update` it should pull in the files (I don't know if you need to run `git submodule init` first).

**Comment by jpmckinney** [comment]
Nevermind, I see that this repo already has a `.gitmodules` file. You might just need to run the `git` commands then.

**Comment by duncandewhurst** [comment]
Yes, that was it. I've created a PR to add the commands to the build process in the handbook: https://github.com/open-contracting/standard-development-handbook/pull/203

Happy for you to go ahead with a PR here based on your assumptions.

**Comment by jpmckinney** [comment]
When do you expect to make a public build? I'll schedule that PR beforehand.

**Comment by duncandewhurst** [comment]
Aiming for late next week - though noting there could be some issues to work through in #22 unless you expect the PR will resolve those?

**Comment by jpmckinney** [comment]
I think #22 is basically done – can you add the gh-pages steps to the readme?

**Comment by duncandewhurst** [comment]
I've added those steps to the readme and kicked off a discussion on where the documentation should be deployed.

Will the PR update `common-requirements.txt` to include a newer version of sphinxcontrib-jsonschema reference to resolve #6?

**Comment by jpmckinney** [comment]
Yes :)
