### ISSUE TITLE
documentType codelist: Add 'projectFeasibilityStudy' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#261]
The reactive disclosure section of the CoST IDS includes the following element:

> Project brief or Feasibility study

## Proposal

Add a 'projectFeasibilityStudy' code to the `documentType` codelist with the following definition:

> Documentation of feasibility studies carried out for this project, providing information on net benefits or costs of the project.

Alternatively, we could add "or project" to the description of the existing (contracting process) 'feasibilityStudy' code from OCDS:

> Documentation of feasibility studies carried out for this contracting process **or project**, providing information on net benefits or costs of the proposed goods, works or services.

@jpmckinney which do you think is the best option?

**Comment by jpmckinney** [comment]
I prefer the second option, like for other `documentType` codes.
