### ISSUE TITLE
documentType codelist: Add 'socialImpact' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#262]
The reactive disclosure section of the CoST IDS includes the following element:

> Environmental and social impact assessment

The `documentType` codelist already has an 'environmentalImpact' code but its description doesn't cover social impact:

> Documentation of assessments of the environmental impacts (e.g. impacts on flora, fauna & woodlands, areas of natural beauty, carbon emissions etc.) and mitigation measures (e.g. pollution control, low carbon solutions, sustainable timber etc.) for this contracting process or project.

Based on the International Association for Impact Assessment's [definition](https://www.iaia.org/wiki-details.php?ID=23), social impact is essentially impact on people.

## Proposal

Add a 'socialImpact' code to the `documentType` codelist with the following title and description:

> **Social Impact Assessment**
> Documentation of social impact assessments (i.e. impacts on people) for this project.

**Comment by jpmckinney** [comment]
A clearer definition might reuse some of these parts of the IAIA page:

> [An assessment of] the intended and unintended social consequences, both positive and negative, of planned interventions

> all issues that affect people, directly or indirectly, are pertinent to social impact assessment.

> social impacts [are] changes to one or more of the following: 
>
> - people’s way of life – that is, how they live, work, play and interact with one another on a day-to-day basis;
> - their culture – that is, their shared beliefs, customs, values and language or dialect;
> - their community – its cohesion, stability, character, services and facilities;
> - their political systems – the extent to which people are able to participate in decisions that affect their lives, the level of democratisation that is taking place, and the resources provided for this purpose;
> - their environment – the quality of the air and water people use; the availability and quality of the food they eat; the level of hazard or risk, dust and noise they are exposed to; the adequacy of sanitation, their physical safety, and their access to and control over resources;
> - their health and wellbeing – health is a state of complete physical, mental, social and spiritual wellbeing and not merely the absence of disease or infirmity;
> - their personal and property rights – particularly whether people are economically affected, or experience personal disadvantage which may include a violation of their civil liberties;
> - their fears and aspirations – their perceptions about their safety, their fears about the future of their community, and their aspirations for their future and the future of their children.

**Comment by jpmckinney** [comment]
The definition can be similarly structured to 'environmentalImpact'.

> Documentation of assessments of the environmental impacts (e.g. impacts on flora, fauna & woodlands, areas of natural beauty, carbon emissions etc.) and mitigation measures (e.g. pollution control, low carbon solutions, sustainable timber etc.) for this contracting process or project.

**Comment by duncandewhurst** [comment]
How about:

> Documentation of assessments of the intended and unintended social consequences, and mitigation measures for this project. Social impacts are changes that affect people, directly or indirectly (e.g. changes to people's way of life, culture, community, health and wellbeing etc.)

The IAIA's definition also mentions that social impact assessment includes recommending mitigation measures, hence including it in the above.

**Comment by jpmckinney** [comment]
Looks good! Just clarifying the first part, where it was hard to read which phrases were modifying which others:

> Documentation of assessments of the intended and unintended social consequences of this project, and documentation of mitigation measures for those social consequences. Social impacts are changes that affect people, directly or indirectly (e.g. changes to people's way of life, culture, community, health and wellbeing etc.)
