### ISSUE TITLE
documentType codelist: Add 'resettlementPlan' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#263]
The reactive disclosure section of the CoST IDS includes the following element:

> Resettlement and compensation plan

The IFC [defines](https://www.ifc.org/wps/wcm/connect/ee19f150-f505-41db-891f-6ef5557195b6/ResettlementHandbook.PDF?MOD=AJPERES&CACHEID=ROOTWORKSPACE-ee19f150-f505-41db-891f-6ef5557195b6-jkD0CRL) (page 12) a resettlement action plan as:

> The document in which a  project sponsor or other responsible entity specifies the procedures that it will follow and the actions that it will take to mitigate adverse effects, compensate losses, and provide development benefits to persons and communities affected by an investment project.

## Proposal

Add a 'resettlementPlan' code to the `documentType` codelist with the following title and description:

> **Resettlement and compensation plan**
> Documentation of the procedures and actions to mitigate adverse effects, compensate losses, and provide development benefits to persons and communities affected by the contracting process or project.

**Comment by jpmckinney** [comment]
Looks good, though I suggest changing "persons" to "people" as the former is just legalistic style, but not semantically different (https://www.merriam-webster.com/words-at-play/people-vs-persons).
