### ISSUE TITLE
Add a field and class for natural persons (project and contract officials and roles)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#264]
The reactive disclosure section of the CoST IDS includes the following elements:

> **Project officials and roles**
> Name and position of the highest authority in the procuring entity where the budget for this project is allocated (project owner)

> **Contract officials and roles**
> Name and position of the public official in charge of administration of the contract(s).

## Proposal

Based on the approach suggested in https://github.com/open-contracting/standard/issues/883#issuecomment-722785450:

* add a `people` array to the `Organization` object
* define a `Person` object with the following properties:
  * `id`
  * `name`
  * `jobTitle`
 
Example:

```json
{
  "parties": [
    {
      "id": "1",
      "name": "Waka Kotahi NZ Transport Agency",
      "people": [
        {
          "id": "1",
          "name": "Sir Brian Roche",
          "jobTitle": "Chair"
        }
      ]
    }
  ]
}
```

**Comment by jpmckinney** [comment]
Looks good!
