### ISSUE TITLE
documentType codelist: add 'projectFinancialAgreement' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#265]
The reactive disclosure section of the CoST IDS includes the following element:

> **Financial agreement**
> Loan or donation agreement with financing conditions

## Proposal

Add a 'projectFinancialAgreement' code to the `documentType` codelist with the following title and description:

> **Project financial agreement**
> Loan or donation agreement with financing conditions

Alternatively, we could omit "project" but we might then find there are other types of financial agreement that do not fit the description.

**Comment by jpmckinney** [comment]
I prefer to omit project, unless you have a good idea of what financial agreements might not fit the description?

I think the style is to start with an article, "A loan", except for descriptions starting with "Documentation"

**Comment by duncandewhurst** [comment]
> I prefer to omit project, unless you have a good idea of what financial agreements might not fit the description?

Nothing in particular, but 'financial agreement' seems like a very general term, whilst the description is quite specific.

Regarding https://github.com/open-contracting/infrastructure/issues/268#issuecomment-762407471, CoST provided this description as I wasn't able to find an authoratitive source to defer to.

**Comment by jpmckinney** [comment]
"Loan or donation agreement with financing conditions" is fairly generic, as they are the most common forms of financing.
