### ISSUE TITLE
documentType codelist: Add 'budgetAmendmentDecision' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#266]
The reactive disclosure section of the CoST IDS includes the following element:

> **Budget amendment decision**
> Document accrediting the approval of budget expansion or extension for this project

## Proposal

Add a 'budgetAmendmentDecision' code to the `documentType` codelist with the following title and description:

> **Budget amendment decision**
> Document accrediting the approval of budget expansion or extension for this project

**Comment by jpmckinney** [comment]
Looks good, though add a period at the end of every description.

**Comment by jpmckinney** [comment]
Actually, we already have 'budgetApproval'

> Additional details about the approval of the budget.

This code doesn't seem so different. At minimum, the code should be changed to 'budgetAmendmentApproval'.

**Comment by duncandewhurst** [comment]
I'm happy with 'budgetAmendmentApproval'. Based on the descriptions, 'budgetApproval' is for the approval of the original budget and this code is for the approval of any subsequent changes to the budget.

Regarding https://github.com/open-contracting/infrastructure/issues/268#issuecomment-762407471, CoST provided this description, as I wasn't able to find an authoritative source to defer to.

**Comment by jpmckinney** [comment]
👍
