### ISSUE TITLE
documentType codelist: Add 'projectCompletionReport' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#267]
The reactive disclosure section of the CoST IDS includes the following element:

> **Project completion report**
> A certificate of completion issued by the relevant authority demonstrating that the works are completed with a certain level of quality (Act of reception of works).

## Proposal

Add a 'projectCompletionReport' code to the `documentType` codelist with the following title and description:

> **Project completion report**
> A certificate of completion issued by the relevant authority demonstrating that the works are completed with a certain level of quality, also known as the act of reception of works.

**Comment by duncandewhurst** [comment]
Noting that based on the description, this seems more like a certificate than a report so we could instead add 'or project' to the OCDS 'completionCertificate' code:

> A completion certificate issued by a relevant authority providing evidence that works were completed to a certain level of quality. Completion certificates might only be relevant for particular kinds of contracting processes **or project**.

**Comment by jpmckinney** [comment]
Yes, let's edit 'completionCertificate'.
