### ISSUE TITLE
documentType codelist: add 'technicalAuditReport' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#268]
The reactive disclosure section of the CoST IDS includes the following element:

> **Technical audit report**
> Documentation of checks that construction work has been undertaken as specified

## Proposal

Add a 'technicalAuditReport' code to the `documentType` codelist with the following title and description:

> **Technical audit report**
> Documentation of checks that construction work has been undertaken as specified

**Comment by jpmckinney** [comment]
Looks good.

**Comment by jpmckinney** [comment]
Actually, for this and #265 and #266, where do the quoted descriptions come from?

**Comment by duncandewhurst** [comment]
This description is based on [CoST's description](https://infrastructuretransparency.org/2018/11/12/turning-infrastructure-data-into-compelling-information-the-added-value-of-cost-assurance/) of a technical audit (beginning of section 2.):

> A technical audit is concerned with checking whether construction work has been undertaken as specified

I'll update #265 and #266 with the source of the descriptions.

**Comment by jpmckinney** [comment]
👍
