### ISSUE TITLE
documentType codelist: Add 'financialAuditReport' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#269]
The reactive disclosure section of the CoST IDS includes the following element:

> **Financial audit report**
> Documentation of checks that project financial statements are correct and complete

## Proposal

Add a 'financialAuditReport' code to the `documentType` codelist with the following title and description:

> **Financial audit report**
> Documentation of checks that project financial statements are correct and complete

**Comment by jpmckinney** [comment]
Looks good, assuming the quoted description is from an authoritative source.

For OCDS, we might prefer this code to the existing 'finalAudit', since audits can occur at other times than final.

**Comment by jpmckinney** [comment]
I see 'finalAudit' is also in OC4IDS. Is it used? If not, we might remove it.

**Comment by duncandewhurst** [comment]
The description is based on the [Cambridge Dictionary definition](https://dictionary.cambridge.org/dictionary/english/financial-audit) of 'financial audit':

> the task of checking a company or organization’s financial statements (= records and accounts) to make certain they are correct and complete, or a report that shows the results of this check

CoST confirmed the description is appropriate.

'finalAudit' is currently referenced in the CoST IDS mapping for the (proactive) 'Reference to audit and evaluation reports' element, but I think it would be better to replace with the more descriptive codes discussed here and in https://github.com/open-contracting/infrastructure/issues/268.

**Comment by jpmckinney** [comment]
👍

**Comment by jpmckinney** [comment]
Small change:

> Documentation of checks that a project's financial statements are correct and complete.
