### ISSUE TITLE
documentType codelist: Add 'projectDesignReport' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#270]
The reactive disclosure section of the CoST IDS includes the following element:

> **Project Design Report**
> Document issued before the works start by the consultant or firm that will supervise the works.

## Proposal

Add a 'projectDesignReport' code to the `documentType` codelist with the following title and description:

> **Project Design Report**
> Document issued before the works start by the consultant or firm that will supervise the works.

**Comment by jpmckinney** [comment]
The description doesn't seem to say what the report is, but rather when it's issued and who authors it.

**Comment by jpmckinney** [comment]
Also, we might consider omitting 'project' from the code, like in other issues.

**Comment by duncandewhurst** [comment]
@evelyndinora - please could you clarify what the project design report is? I struggled to find an authoritative definition.

**Comment by EvelynDinora** [comment]
This is a record of the justification for the design approach adopted in the project. 
P.D. I don't understand why do not use the word project, when the OC4IDS is about projects not only contracts.

**Comment by duncandewhurst** [comment]
Thanks, Evelyn. I believe James' recommendation to omit 'project' from the code is simply for brevity, otherwise all codes related to the project would begin with 'project'.

@jpmckinney are you happy with the following, based on Evelyn's clarification?

> code: designReport
> title: **Project Design Report**
> description: A record of the justification for the design approach adopted in the project, typically issued before the works start by the consultant or firm that will supervise the works.

**Comment by EvelynDinora** [comment]
@duncandewhurst Understood. Yes, I am happy with your proposal. Many thanks!

**Comment by jpmckinney** [comment]
Yes, looks good! For posterity, what is the source of the second clause ("typically issued...")?

**Comment by duncandewhurst** [comment]
@EvelynDinora provided the description in the document shared in CRM-6221
