### ISSUE TITLE
documentType codelist: add 'escalationApprovals' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#271]
The reactive disclosure section of the CoST IDS includes the following element:

> **List of escalation approvals**
> Document containing a list of the escalations approved during the project lifecycle

## Proposal

Add a 'escalationApprovals' code to the `documentType` codelist with the following title and description:

> **escalationApprovals**
> Document containing a list of the escalations approved during the project lifecycle

**Comment by jpmckinney** [comment]
"containing a list of the escalations approved" seems odd. Would it be fine to change the code to singular, and have:

> Documentation of one or more escalations approved during the project lifecycle.

I don't know what an escalation is, though.

**Comment by duncandewhurst** [comment]
The singular version looks good to me. @evelyndinora - please could you confirm?

Based on the draft descriptions in the [CoST IDS mapping](https://standard.open-contracting.org/infrastructure/latest/en/cost/?highlight=escalation#implementation) an escalation is an increase in the price of materials, labour, equipment etc. due to fluctuations in inflation, currency etc.

**Comment by jpmckinney** [comment]
Since the IDS element is "Escalation of contract price", I suggest:

> Documentation of one or more approved escalations of the contract price during the project lifecycle.

**Comment by EvelynDinora** [comment]
It is fine by me.
