### ISSUE TITLE
documentType codelist: add 'qualityAssuranceReport' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#272]
The reactive disclosure section of the CoST IDS includes the following element:

> **Quality assurance reports**
> Documentation identifying deficiencies in designs, specifications, standards, methods, procedures and practices, and identifying best practices.

## Proposal

Add a 'qualityAssuranceReport' code to the `documentType` codelist with the following title and description:

> **Quality assurance report**
> Documentation identifying deficiencies in designs, specifications, standards, methods, procedures and practices, and identifying best practices.

**Comment by jpmckinney** [comment]
Looks good, assuming the quoted description is from an authoritative source.

**Comment by duncandewhurst** [comment]
The description is based on the New York State Department of Transport's definition of a 'project quality assurance report' ([section II.A](https://www.dot.ny.gov/portal/pls/portal/mexis_app.pa_ei_eb_admin_app.show_pdf?id=10331)). CoST confirmed the description is appropriate.

**Comment by jpmckinney** [comment]
For this and other issues, can you quote the relevant text? It's much easier to review, and in future we'll be able to point back to the quoted text, even if the link no longer works.

**Comment by duncandewhurst** [comment]
> The PQAR is a formal means for the Regional Construction Group to provide written feedback on project designs as a result of the experience gained during construction. The intent is to improve project quality (future design procedures, contract documents and construction practices) by (1) identifying deficiencies in designs, specifications, standards, methods, procedures and practices so they may be corrected/improved, (2) identifying best practices for more widespread distribution, and (3) revising guidance for construction staff.

**Comment by jpmckinney** [comment]
Thanks! Looks good.
