### ISSUE TITLE
Transactions (disbursement records) and payment certificates

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#273]
The reactive disclosure section of the CoST IDS has the following element:

> Disbursement records or payment certificates

CoST clarified that disbursement records match the OCDS concept of transactions and that payment certificates are:

> A document certifying that the noted work has been completed and payment to the contractor is approved

## Proposal

Add a `transactions` array to `ContractingProcess/summary` and reuse the OCDS `Transaction` object.

Add a 'paymentCertificate' code to the `documentType` codelist, with the following title and description:

> **Payment certificate**
> A document certifying that the noted work has been completed and payment to the contractor is approved

**Comment by jpmckinney** [comment]
The first part of the description of 'paymentCertificate' overlaps, with 'completionCertificate', no?

> A completion certificate issued by a relevant authority providing evidence that works were completed to a certain level of quality. Completion certificates might only be relevant for particular kinds of contracting processes.

Adding a `transactions` array sounds good, and I guess the guidance will explain when/which transactions to put in the summary vs individual contracting processes.

**Comment by duncandewhurst** [comment]
> The first part of the description of 'paymentCertificate' overlaps, with 'completionCertificate', no?
> 
> > A completion certificate issued by a relevant authority providing evidence that works were completed to a certain level of quality. Completion certificates might only be relevant for particular kinds of contracting processes.

I think the difference may be that a completion certificate relates to the completion of the whole project, whereas a payment certificate relates to the completion of the works specified on a contractors estimate or invoice, of which there might be many during the course of a project. @evelyndinora - please can you clarify?

> Adding a `transactions` array sounds good, and I guess the guidance will explain when/which transactions to put in the summary vs individual contracting processes.

The aim would be to avoid CoST programmes which are implementing OC4IDS also having to publish very sparse OCDS data in order to meet the requirements of the CoST IDS, but we can add a caveat along the lines of "if you collect detailed contracting data, for example from a procurement system, you should consider publishing it using OCDS"

**Comment by EvelynDinora** [comment]
@duncandewhurst you are right with your assumption: a completion certificate relates to the completion of the whole project, whereas a payment certificate relates to the completion of the works or services specified on a contractors estimate or invoice, of which there might be many during the course of a project.

**Comment by duncandewhurst** [comment]
Thanks, Evelyn! @jpmckinney are you happy to have separate codes on that basis?

**Comment by jpmckinney** [comment]
Yes, but is there any change we can make to the codes' descriptions to make the distinction clearer?

**Comment by duncandewhurst** [comment]
How about the following. I also replaced 'contractor' with 'supplier' to align with the terminology used elsewhere in OC4IDS and put the first clause in present tense to match the second clause:

> **Payment certificate**
> A document certifying that the work *specified on a supplier's estimate or invoice is complete* and that payment to the supplier is approved.

We could also update the completion certificate description as follows, in order to:

* make the distinction clearer
* align with the structure of the payment certificate description
* to remove the repetition of the code title
* put the description in the present tense

> **Completion certificate**
> A document issued by a relevant authority certifying that the work specified in the contract is complete to a certain level of quality. Completion certificates might only be relevant for particular kinds of contracting processes.

But I think that would be best done in OCDS.

**Comment by jpmckinney** [comment]
Sounds good - let's go with your suggested paymentCertificate description. Can you open an OCDS issue for completionCertificate?
