### ISSUE TITLE
documentType codelist: Add 'incorporationCertificate' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#274]
The reactive disclosure section of the CoST IDS has the following element:

> Registration and ownership of firms

CoST clarified this requirement covers both data and documents. The requirement can be met by providing an organization identifier (data) and a copy of the certificate of incorporation (document).

## Proposal

Add a 'incorporationCertificate' code to the `documentType` codelist, with the following title and description:

> **Certificate of incorporation**
> An official document that proves that a company has been legally created and officially exists.

**Comment by jpmckinney** [comment]
Certificates of incorporation are more of a Commonwealth term. The broader term is Articles of Association. We might build a description based on https://www.investopedia.com/terms/a/articles-of-association.asp

**Comment by duncandewhurst** [comment]
Hmm, in the UK the two terms have different meanings:

* [Articles of association](https://www.gov.uk/limited-company-formation/memorandum-and-articles-of-association) are written rules about running the company (same as the investopedia link)
* The [certificate of incorporation (1.19)](https://www.gov.uk/government/publications/incorporation-and-names/incorporation-and-names) is evidence that the company is registered and states the following:
  * the name and registered number of the company
  * the date of its incorporation
  * whether it is a limited or unlimited company, and if it is limited whether it is limited by shares or limited by guarantee
  * whether it is a private or a public company
  * whether the company’s registered office is situated in England and Wales, Wales, Scotland or Northern Ireland

[This article](https://www.informdirect.co.uk/company-formation/certificate-of-incorporation-what-is-it/) also discusses the differences:

> Beyond stating the type of company, the certificate also doesn’t provide any information on the rules that govern the management of the company. The detailed rules that define how the company should be managed are instead within the Articles of Association.

**Comment by jpmckinney** [comment]
In jurisdictions without certificates, the articles are often used as evidence.

We can leave the code as 'incorporationCertificate', but change the description to:

> A document issued by the relevant government registry as confirmation of the due incorporation and valid existence of the organization. ~~Depending on the jurisdiction, this might be a certificate of incorporation, articles of incorporation, articles of association, or similar.~~

based on https://en.wikipedia.org/wiki/Certificate_of_incorporation That way, if a registry doesn't issue certificates, some other evidence could be used with this code to satisfy the same need.

**Comment by jpmckinney** [comment]
Hmm, I'm getting different results from different sources. Wikipedia seems to conflate the terms too much:

* https://en.wikipedia.org/wiki/Certificate_of_incorporation
* https://en.wikipedia.org/wiki/Articles_of_incorporation
* https://en.wikipedia.org/wiki/Articles_of_association

We can just go with the first sentence from my comment above. It could just be that Wikipedia has a Commonwealth bias with respect to its English content, such that it only discusses Commonwealth certificates.

Edit: Not sure which made the error first, but Investopedia also has the confusing "[Articles of incorporation](https://www.investopedia.com/terms/a/articlesofincorporation.asp) are also referred to as the "corporate charter," "articles of association," or "certificate of incorporation.""
