### ISSUE TITLE
documentType codelist: Add 'contractAmendment' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#275]
The reactive disclosure section of the CoST IDS has the following element:

> **Contract amendments**
> Documentation of the amended contract terms.

## Proposal

Add a 'contractAmendment' code to the `documentType` codelist, with the following title and description:

> **Contract amendment**
> Documentation of the amended contract terms.

**Comment by jpmckinney** [comment]
Looks good, assuming the quoted description is from an authoritative source.

**Comment by duncandewhurst** [comment]
I proposed the description based on a contract amendment being "a change or an addition to the terms of a contract" ([Investopedia](https://www.investopedia.com/terms/a/amendment.asp)) and "a separate legal document that changes the terms of an existing contract" ([LegalNature](https://www.legalnature.com/categories/business/contract-amendment)), and following the 'documentation of...' pattern used elsewhere in the documentType codelist.

CoST confirmed the description is appropriate, but happy to adjust if needed.

**Comment by jpmckinney** [comment]
I prefer a description that explains the title rather than repeating the same words. Also, a contract amendment as defined by those two sources and "documentation of" an amendment might not be the same thing. So maybe:

> A legal document that changes or adds to the terms of an existing contract.
