### ISSUE TITLE
Implementation progress reports

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#277]
The reactive disclosure section of the CoST IDS has the following element:

> Implementation progress reports

CoST clarified that this element can be satisfied with either documents or structured data and that progress reports relate to the project as a whole rather than individual contracting processes.

## Research

Based on reviewing examples from from [Afghanistan](https://ageops.net/en/procurement-procedure/contract/progress/DABS%252F007%252FICB), [Honduras](https://fondovial.sisocs.org/index.php?r=ciudadano/FichaTecnica&control=Contratacion&id=781), [Ukraine](https://costportal.mtu.gov.ua/tblpub/PROJECTS.php?hname=dbo_PROJECTS_dbo_PROJECTS_TECH_DETAILS_handler&fk0=13524&master_viewmode=0), [Guatemala](http://proyectos.costguatemala.org/public/costProyectos/42), [Nuevo Leon](http://si.nl.gob.mx/transparencia/proyecto/oc4ids-gx3fo2-000213) and [Buenos Aires](https://www.buenosaires.gob.ar/baobras/viaducto-san-martin), the common approaches to publishing data on implementation progress are:

* A single % figure representing the current financial progress of the project (Ukraine, Nuevo Leon and Buenos Aires - though in the latter case it isn't clear if the progress is physical or financial)
* A breakdown of planned and actual physical and financial progress by date (Afghanistan and Honduras)
* Documents (Honduras and Guatemala).

The structure of the [OCDS metrics extension](https://extensions.open-contracting.org/en/extensions/metrics/master/) can be used to model both the single figure and the detail breakdown. See [tabular examples](https://docs.google.com/spreadsheets/d/1dhXpsXnho_jfdlurhAyHBuVDB54ZnDqcrsm_U48yH6k/edit#gid=0) for Honduras and Nuevo Leon and the document shared in CRM-3772#note-12 for Afghanistan.

The [document type codelist](https://standard.open-contracting.org/infrastructure/latest/en/reference/codelists/#documenttype) already contains codes for financial progress reports and physical progress reports.
 
The following data elements relate to implementation progress reporting but are only captured by one publisher:

* Project status relative to schedule (Ukraine)
* A publication date, 'description of problems' and 'description of topics' for each progress report (Honduras)
* 'Approved estimates', 'Paid estimates' and payments (Guatemala - [description of estimates](http://www.contraloriadf.gob.mx/contraloria/cursos/OBRAS/paginas/est.php))
* Guarantees (Guatemala)

The structure of the OCDS metrics extension can be used to model the additional fields from Honduras and Guatemala, with the exception of guarantees which relate to individual contracting processes and can be modelled using the [OCDS guarantees extension](https://extensions.open-contracting.org/en/extensions/guarantees/master/).

Project status relative to schedule could be disclosed using a free-text `statusDetails` field.

Neuvo Leon also publishes fields calculated from their OCDS data for the total value of awards, the total value of contracts and the total value of transactions.

## Proposal

Add the following fields to the `Project` object, reusing the [OCDS metrics extension](https://extensions.open-contracting.org/en/extensions/metrics/master/):

| Path | Title | Description | Type |
| -- | -- | -- | -- |
| forecasts | Forecasts | Forecast metrics for this project, such as planned physical or financial progress over time | Array of [Metric](https://extensions.open-contracting.org/en/extensions/metrics/master/schema/#metric) objects |
| metrics | Metrics | Actual metrics for this project, such as the actual physical or financial progress over time | Array of [Metric](https://extensions.open-contracting.org/en/extensions/metrics/master/schema/#metric) objects |

Document guidance on how to summary progress figures and a breakdown of planned and actual progress by date, including guidance on setting `forecasts/id` and `metrics/id` to identify what type of progress is being reported.

## Example 1: Summary progress figure

```json
"metrics": [
  {
    "id": "financialProgress",
    "title": "Current financial progress (%)",
    "observations": [
      {
        "id": "1",
        "measure": "4.04",
        "unit": {
          "name": "percent",
          "id": "P1",
          "scheme": "UNCEFACT"
        },
        "period": {
          "startDate": "2017-03-31T23:59:59Z",
          "endDate": "2017-03-31T23:59:59Z"
        }
      }
    ]
  }
]
```

* Publishers which maintain a progress history can add a new observation each time there is a progress update, otherwise they can publish a single observation and update it each time there is a progress update
* `period` reflects the date on which the progress was measured/updated

## Example 2: Planned progress over time

```json
{
  "forecasts": [
    {
      "id": "physicalProgress",
      "title": "Planned physical progress (%)",
      "observations": [
        {
          "id": "1",
          "measure": "4.04",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          },
          "period": {
            "startDate": "2017-03-31T23:59:59Z",
            "endDate": "2017-03-31T23:59:59Z"
          }
        },
        {
          "id": "2",
          "measure": "7.98",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          },
          "period": {
            "startDate": "2017-04-30T23:59:59Z",
            "endDate": "2017-04-30T23:59:59Z"
          }
        },
        {
          "id": "3",
          "measure": "8.38",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          },
          "period": {
            "startDate": "2017-05-31T23:59:59Z",
            "endDate": "2017-05-31T23:59:59Z"
          }
        }
      ]
    }
  ]
}
```

## Example 3: Actual progress over time

```json
{
  "metrics": [
    {
      "id": "physicalProgress",
      "title": "Actual physical progress (%)",
      "observations": [
        {
          "id": "1",
          "measure": "4.04",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          },
          "period": {
            "startDate": "2017-03-31T23:59:59Z",
            "endDate": "2017-03-31T23:59:59Z"
          }
        },
        {
          "id": "2",
          "measure": "7.98",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          },
          "period": {
            "startDate": "2017-04-30T23:59:59Z",
            "endDate": "2017-04-30T23:59:59Z"
          }
        },
        {
          "id": "3",
          "measure": "8.38",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          },
          "period": {
            "startDate": "2017-05-31T23:59:59Z",
            "endDate": "2017-05-31T23:59:59Z"
          }
        }
      ]
    }
  ]
}
```

**Comment by jpmckinney** [comment]
Sounds good to me!
