### ISSUE TITLE
Update worked example to include new fields and codes for CoST IDS reactive disclosures

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#278]

**Comment by duncandewhurst** [comment]
I've pushed a branch with the latest version of the reactive disclosure element mappings which you can use as a reference: https://standard.open-contracting.org/staging/infrastructure/220-reactive-mappings/en/cost/ if you spot any issues please comment on the PR: https://github.com/open-contracting/infrastructure/pull/295

Some of the issues for new fields include example data which you can reuse: https://github.com/open-contracting/infrastructure/issues?q=is%3Aissue+label%3AIDS+is%3Aclosed

**Comment by pindec** [comment]
Great, thanks @duncandewhurst.
