### ISSUE TITLE
Connecting OC for Infrastructure and OCDS for PPPs

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#28]
Given that PPPs are a popular mode for delivering infrastructure projects we should consider how data published using OCDS for PPPs and data published using OC for Infrastructure can be connected.

This is out of scope for the initial development of OC for Infrastructure but could be a key issue for supporting implementation and future development of the work.

Noting that in Honduras there are separate platforms for [transparency of PPPs](http://app.sisocs.org/index.php?r=Ciudadano/index) and [transparency of infrastructure projects](https://sisocs.org/) so we should also check that there is in fact demand for publishing and using joined up data.

**Comment by EvelynDinora** [comment]
I think is a good idea to think how to connect both. From the Honduras' experience we found it difficult since the project cycle is different. Also the type of data and information produced differs from a traditional infrastructure project and a PPP. Happy to start thinking how to do it despite the mentioned issues.

**Comment by duncandewhurst** [comment]
In 0.9.3, we added some content to the Getting Started documentation that addresses this issue: https://standard.open-contracting.org/infrastructure/latest/en/projects/#how-do-ppps-fit-in.

There are also [several open issues](https://github.com/open-contracting/infrastructure/issues?q=is%3Aopen+is%3Aissue+label%3Appp) on modelling PPPs in OC4IDS.

I think we can follow up on those specific issues and close this overarching issue. It can be reopened if needed.
