### ISSUE TITLE
borrow-schema.py pulls in deprecated fields from OCDS

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#280]
@jpmckinney https://github.com/open-contracting-extensions/public-private-partnerships/commit/6ac22611d2b85c40d065d353de0c8ba407e7912d seems to have introduced deprecated fields from OCDS into the OCDS for PPPs schema and so `borrow-schema.py` now pulls these into the OC4IDS schema.

Was that intentional? If so I can update `borrow-schema.py` to remove deprecated fields, otherwise we should update OCDS for PPPs to remove the deprecated fields before running `borrow-schema.py`.

For posterity, this relates to #277 in which I've updated `borrow-schema.py` to pull in the `Metrics` and `Observation` definitions from OCDS for PPPs.

**Comment by jpmckinney** [comment]
Yes, it was intentional (extensions shouldn't remove fields, only a new major version of OCDS should), so let's update the script here.
