### ISSUE TITLE
Classification object missing uri property

### ISSUE THREAD

**Issue by pindec** [open-contracting/infrastructure#284]
OCDS `Classification` objects have `uri` properties:

```json
"properties": {
        "scheme": {},
        "id": {},
        "description": {},
        "uri": {
          "title": "URI",
          "description": "A URI to uniquely identify the classification code.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      }
```

OC4IDS `Classification` objects do not, even though the `Classification/description` says "It is useful to also publish a text label and/or URI that users can draw on to interpret the classification":
```json
"properties": {
        "scheme": {},
        "id": {},
        "description": {}
      }
```

This means some data is lost during ocdskit convert-to-oc4ids for OCDS for PPPs where `project.planning.sector` data is present (see [ocdskit#163](https://github.com/open-contracting/ocdskit/issues/163)).

**Comment by duncandewhurst** [comment]
Good spot. Looks like `borrow-schema.py` drops `uri` when copying the Classification definition from OCDS: https://github.com/open-contracting/infrastructure/blob/e0d8490d084a708e951c75c208ecd275ca5e673c/schema/borrow-schema.py#L280

We should either reinstate it or update `description` to remove 'and/or URI'.

@jpmckinney do you have a view?

**Comment by jpmckinney** [comment]
It seems Tim decided to omit it according to this issue #3, and I didn't have a strong feeling about at the time. Now, I think it's better to have alignment with OCDS, so would prefer to reinstate it.
