### ISSUE TITLE
Add a Value.date field

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#286]
See https://github.com/open-contracting/standard/issues/988

Value dates came up in the context of infrastructure when looking at the [RICS ICMS](https://www.rics.org/uk/upholding-professional-standards/sector-standards/construction/icms-international-construction-measurement-standards/) which includes a 'base date of costs' field.

Edit: Noting that a field added to OCDS would eventually appear in OC4IDS via OCDS for PPPs and `borrow-schema.py` but we might choose to add it sooner based on demand.

**Comment by duncandewhurst** [comment]
To determine if this field is needed, we can undertake a similar analysis to the one in https://github.com/open-contracting/standard/issues/988#issuecomment-881673538

**Comment by neelima-j** [comment]
In OC4IDS value appears in 
budget (with the corresponding date fields of `requestDate` and `approvalDate`), 
budgetBreakdown (period `startDate` and `endDate`), 
forecasts (observations/0/period `startDate` and `endDate`),
metric (observations/period),
documents/0/accessDetails may contain fee information. The corresponding date fields are `datePublished` and `dateModified`. 
 
In contractingProcesses/0/summary value appears in :
contractValue (with the corresponding date in `contractPeriod`), 
finalValue (The date corresponding to finalValue has to be found from either `contractPeriod` or `modifications\0\date`),
modification (`date`, `newContractPeriod`),
transactions (`date`), and 

tender - There is no date field immediately associated with tender/costEstimate. 

- A reasonable range for the date is after the project starts (request or approval) and before the contract corresponding to the tender starts. 

- An estimate may not be useful according to the [RICS definition of base date of cost](https://www.rics.org/globalassets/rics-website/media/upholding-professional-standards/sector-standards/construction/nrm-1-order-of-cost-estimating-and-cost-planning-2nd-edition-rics.pdf) which needs a specific date ( _the date on which rates and prices contained within cost analyses or benchmark analyses are taken as a basis for calculations._)

- While base dates are important for costing, [RICS data standard](https://github.com/RICS-Data-Standard/RDS/blob/main/JSON/RICS%20Data%20Standard%20Version%203.3.3.pdf)  seems permissive about how the date is captured. (_To accommodate the differing quality and availability of date and time data this component allows dates to be captured as either time; date and time; date; year and month; year; or in extremis, as a simple text string._).  'year and month' or 'year' can be extracted from current OC4IDS

- Therefore, is there demand to add a date field to tender/costEstimate?

**Comment by duncandewhurst** [comment]
Thanks, @neelima-j!

> Therefore, is there demand to add a date field to tender/costEstimate?

I think that we can add the `tender.datePublished` field mentioned in https://github.com/open-contracting/standard/issues/988 to meet this need.
