### ISSUE TITLE
Move content describing the use of the schema from the worked example to the schema reference

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#299]
From https://github.com/open-contracting/infrastructure/pull/298#pullrequestreview-615814396

e.g.

> The parties array is used to provide details about organizations involved in the infrastructure project and their roles. Organization references elsewhere in the data refer back to entries in this section.

At the same time, we can also rephrase to use active voice.

**Comment by duncandewhurst** [comment]
@jpmckinney are you happy with the proposal in this issue?

To be clear, the idea is to review the text on the [worked example](https://standard.open-contracting.org/infrastructure/latest/en/guidance/example/) page to identify content that would be useful to include in the [schema reference page](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#organization), which currently lacks much beyond the schema tables.

This might involve breaking the large tables on the schema reference page (project and contractingProcessSummary) into smaller chunks.

**Comment by jpmckinney** [comment]
Sounds fine to me.
