### ISSUE TITLE
How to sync definitions in project-schema.json with OCDS

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#3]
[project-schema.json](https://github.com/open-contracting/infrastructure/blob/profile-draft/schema/project-level/project-schema.json) re-uses many object definitions and field descriptions from OCDS and extensions. Some extensions are referred to (e.g. budget breakdown), whereas others are not (e.g. documentation details, location, contract register).

1. I see that `uri` is missing from `Classification`, `details` from `Organization`, etc. and that `address` is added to `Location`, `id` to `ReleaseListEntry` (compared to linked releases in record packages), many to `ContractingProcess`, etc. It would be useful to list changes, to consider as proposals for OCDS or extensions, to avoid unnecessary misalignment.
2. Where they are identical, is it anticipated that scripts will be authored to ensure that, as definitions are improved in OCDS and extensions, those changes can be reviewed and merged into the project schema? I think it's important to align as much as possible, in order to not confuse publishers and users of both specifications.

**Comment by jpmckinney** [comment]
I see there's a relevant script: https://github.com/open-contracting/infrastructure/blob/profile-draft/schema/borrow-schema.py Nonetheless, I think there can/should be a clear policy as to how the project schema relates to OCDS and extensions.

As a side note, the script refers to a 'Infrastructure Project Transparency Schema/Standard', which should be changed to 'Infrastructure Project Level Data Specification' to match the documentation.

**Comment by timgdavies** [comment]
I'll add a bit more text to borrow-schema.py to explain what is going on in there. 

I've added this to a 1.0 milestone, as policy and governance development are out of scope of the current alpha/beta work.

**Comment by jpmckinney** [comment]
Pre-1.0, it may still be useful to document what was re-used and to identify and explain any differences, to inform later policy and governance work.

**Comment by jpmckinney** [comment]
I reviewed borrow-schema.py in https://github.com/open-contracting/infrastructure/commit/eb71212d0d8a512d35e0167ea100f10a6f75cd2a and I'm satisfied that it now addresses my concerns. The updates to the script resulted in no change to the output.
