### ISSUE TITLE
META: Timeline and milestones

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#303]
Is there a rough timeline for an OC4IDS release? I see the project board is just about done: https://github.com/open-contracting/infrastructure/projects/2 I figure we want to add the [bug](https://github.com/open-contracting/infrastructure/labels/bug) and [build process](https://github.com/open-contracting/infrastructure/labels/build%20process) issues. The only milestone is 1.0, but I don't know if that's what we're targeting, or if we should make a 0.9.3.

Once I have a timeline, I can prioritize some of the build process issues accordingly.

**Comment by duncandewhurst** [comment]
I'm keen to get the reactive disclosures work deployed, so let's target a 0.9.3 with the additions you suggest. We can then discuss the roadmap for 1.0.

Timeline-wise, the worked example updates should be done by this week but the bug fixes will probably need to wait until next week. So if you could tackle the build issues by the end of next week we should be good to do the release in w/c 12th April.

**Comment by jpmckinney** [comment]
I added issues to the 0.9.3 milestone: https://github.com/open-contracting/infrastructure/milestone/6

Any other untagged issues to include? https://github.com/open-contracting/infrastructure/issues?page=1&q=is%3Aopen+is%3Aissue+no%3Amilestone

**Comment by duncandewhurst** [comment]
Great, thanks.

No others to include. I prefer to keep the schema, codelists and docs changes in this release to just those required for the reactive disclosures (plus bug fixes).
