### ISSUE TITLE
Ambiguous wording around worked example file implying it's always complete w.r.t. latest schema

### ISSUE THREAD

**Issue by pindec** [open-contracting/infrastructure#316]
The [worked example page](https://github.com/open-contracting/infrastructure/blob/0.9-dev/docs/guidance/example.md) could be interpreted to imply that the example contains all possible fields from the schema:

> This worked example is a fully completed OC4IDS JSON file representing a fictional, completed infrastructure project to upgrade a motorway in the UK.

However, this is not necessarily the case: we don't programmatically check that the [example file](https://github.com/open-contracting/infrastructure/blob/0.9-dev/docs/examples/example.json) contains all possible fields. The [blank.json file](https://github.com/open-contracting/infrastructure/blob/0.9-dev/docs/examples/blank.json) instead should contain them all since it is generated from the schema.

A publisher assumed that for the example file, "fully completed" meant "contains all possible OC4IDS fields", and used it as a starting point for implementation. 

It would be better to:
* alter the wording to say "a filled-in example file" rather than "a fully completed OC4IDS JSON file"
*  add a tip box to flag the blank.json file for publishers to use instead as a starting point for implementation (as in the [evaluating page](https://github.com/open-contracting/infrastructure/blob/0.9-dev/docs/guidance/evaluating.md)).

**Comment by jpmckinney** [comment]
Is this for 0.9.3 or later?

**Comment by pindec** [comment]
Either - the issue came up with a publisher the other day. 

The PR would be straightforward, so I can add for 0.9.3 if appropriate.

**Comment by jpmckinney** [comment]
Okay, happy to merge a PR for 0.9.3 :)
