### ISSUE TITLE
Distinguishing between real and projected costs

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#322]
Similar to the issue discussed in #140, OC4IDS currently lacks a means to separately publish the budget for a project and the projected cost.

The CoST IDS has the following elements, which have some semantic overlap:

CoST IDS element | CoST IDS description | OC4IDS mapping
-- | -- | --
Project Budget | Specify the projected costs/allocated budget for the project (currency and amount). The budget includes land / property acquisition, environmental mitigation measures, H&S provisions, client, consultant & contractor costs, VAT etc. | `budget/amount`
Project completion cost | State projected or actual completion cost (currency and amount) | `completion/finalValue`

According to the following descriptions, `completion/finalValue` can only be used for the actual cost at completion:

OC4IDS field | OC4IDS description
-- | --
`completion` | This information is provided at project completion, and reflects the final timing and values relating to the project. The reason for any variation (not already explained) between the anticipated project scope, period and value should be detailed.
`completion/finalValue` | The total cost of this project at completion (compare with project budget).

CoST West Lombok capture the project budget and the projected completion cost as separate data points, and other CoST programmes are likely to do the same.

One possible solution, discussed in https://github.com/open-contracting/infrastructure/issues/287#issuecomment-782992594, is to update the description of `budget` to preserve the initial value and to capture the projected costs using `costMeasurements`.

Adding to 1.0 milestone to address along with #140.

**Comment by duncandewhurst** [comment]
CoST's [Assurance Manual](https://infrastructuretransparency.org/resource/assurance-manual/) (page 36) mentions looking at time and cost variations for in-progress projects.

**Comment by duncandewhurst** [comment]
> CoST West Lombok capture the project budget and the projected completion cost as separate data points, and other CoST programmes are likely to do the same.
> 
> One possible solution, discussed in [#287 (comment)](https://github.com/open-contracting/infrastructure/issues/287#issuecomment-782992594), is to update the description of `budget` to preserve the initial value and to capture the projected costs using `costMeasurements`.

This issue has come up again in CoST Uganda, so it would be good to agree on an approach here so that implementers have a place to put the projected completion cost.

Building on the suggestion above, putting the projected value in cost measurements would look like:

```json
{
  "costMeasurements": [
    {
      "id": "1",
      "costGroups": [
        {
          "id": "1",
          "costs": [
            {
              "id": "1",
              "value": {
                "amount": 1000000,
                "currency": "NGN"
              }
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by jpmckinney** [comment]
Does #287 have a way to distinguish projected from real costs?

**Comment by duncandewhurst** [comment]
Yep, ICMS has a `costReportStatusEnum` that we discussed putting in `costMeasurements.stage`:

- 'pre-constructionForecast'
- 'atTender'
- 'duringConstruction'
- 'actualCostsOfConstructionPost-completion'
- 'renewalForecastDuringUse'
-  'endOfLifeForecast'

**Comment by jpmckinney** [comment]
Is this resolved by #287?

**Comment by duncandewhurst** [comment]
I think the original need is addressed (distinguishing between budgets and projected costs) but since we decided to omit `CostMeasurement.stage` I think your question in https://github.com/open-contracting/infrastructure/issues/322#issuecomment-1071167285 about distinguishing between projected and real costs remains unresolved.

**Comment by jpmckinney** [comment]
Ah, right, and the relevant comment from #287 is https://github.com/open-contracting/infrastructure/issues/287#issuecomment-1809221831:

> I think the costCategory codelist (referenced in CostGroup.category) is sufficient to express what is being measured and comparing costMeasurement.date to the start and end dates for each stage (proposed in https://github.com/open-contracting/infrastructure/issues/252) should be sufficient to determine what stage the cost measurement was reported at.... so perhaps we don't need costMeasurement.atStage at all?

If we're happy with using dates to determine real vs projections, then I think this issue can be closed?

**Comment by duncandewhurst** [comment]
Hmm, when I wrote that I was thinking about the subject of the cost measurement (the stages included in the cost measurement) and the timing of the cost measurement (the stage at which the cost measurement was prepared), rather than whether the measured costs are real or projected.

I'm not sure that dates are sufficient to determine real vs projected for all cases and I would expect that many cost measurements might include both (real costs so far, projected costs to the end of the cost measurement). For example, a pre-construction forecast might cover both projected construction costs and real costs for site acquisition and the client's administrative, finance, legal and marketing expenses.

I suppose that we could add a field so that publishers can declare whether a cost measurement includes real costs, projected costs or both, but ICMS doesn't seem too concerned with making that distinction in structured data so I'm happy to close this issue until we learn of a use case.

**Comment by jpmckinney** [comment]
Aha. Re-reading the issue, I'm not sure why I asked about real costs in https://github.com/open-contracting/infrastructure/issues/322#issuecomment-1071167285, so if we resolved the original issue description, I think we can close.

**Comment by duncandewhurst** [comment]
Sounds good :-)
