### ISSUE TITLE
LinkedRelease.tag required in the JSON schema but not in the schema reference documentation

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#328]
`tag` is [required in the schema](https://github.com/open-contracting/infrastructure/blob/b1e2f048a1c77d79a1f0894475265e3a6d4ac73e/schema/project-level/project-schema.json#L518) and is shown in bold in the [schema browser ](https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/reference/browser/), as expected. However, in the [schema reference](https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/reference/schema/#linkedrelease), tag is not required.

cc @odscrachel

**Comment by jpmckinney** [comment]
Can you also report the bug on https://github.com/OpenDataServices/sphinxcontrib-opendataservices-jsonschema ?

**Comment by Bjwebb** [comment]
@duncandewhurst How does this look? https://standard.open-contracting.org/staging/infrastructure/tmp-328-tag-not-required-git-requirement/en/reference/schema/#linkedrelease

**Comment by duncandewhurst** [comment]
Looks great. Thank you!
