### ISSUE TITLE
Schema fixes in follow-up to #29

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#33]
* [x] Update `process-level.csv` to follow the updated schema, notably the additional nesting of fields under `tender`
* [ ] Update `smp.json` and `project.json` to follow the updated schema, i.e. that they are valid and have no additional fields
* [x] Fix remaining occurrences of `releaseList` with `releases`. `releaseList` shouldn't appear at all under `LinkedRelease` in the jsonschema directive.
* [x] Add ContractingProcessSummary to reference.md; when doing so, collapse `summary` under ContractingProcess, and collapse `documents` under ContractingProcessSummary

**Comment by duncandewhurst** [comment]
The source Google Sheet for the mapping has been updated to reflect the updated schema, once #34 and #35 are complete `process-level.csv` can be updated.

@pindec is working on updates to the sample data.

**Comment by duncandewhurst** [comment]
Closing in favour of #47
