### ISSUE TITLE
Link to extension explorer for OCDS extensions

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/infrastructure#330]
Carrying on from Duncan's ticket in OCDS 

> The [BudgetBreakdown reference](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#budgetbreakdown) includes links to the Github pages for the Budget Breakdown and Budgets and Spend extensions.
> 
> We should instead link to the extension explorer pages for these extensions and any other extensions referenced in the documentation.

**Comment by jpmckinney** [comment]
Issue from OCDS: https://github.com/open-contracting/standard/issues/1096

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/infrastructure/pull/332
