### ISSUE TITLE
Indicate required field in schema browser with red asterisk 

### ISSUE THREAD

**Issue by pindec** [open-contracting/infrastructure#333]
The [schema browser](https://standard.open-contracting.org/infrastructure/latest/en/reference/browser/#) currently shows required fields in bold. 
![image](https://user-images.githubusercontent.com/1897475/123234011-7b319600-d4d2-11eb-81ed-d6cad2b93522.png)

Adding a red asterisk to required fields as well would make it more obvious, as with the [OCDS schema browser](https://standard.open-contracting.org/latest/en/schema/release/): 
![image](https://user-images.githubusercontent.com/1897475/123233859-55a48c80-d4d2-11eb-857d-930770e0588e.png)

**Comment by jpmckinney** [comment]
This is done on the dev branch: https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/reference/browser/
