### ISSUE TITLE
Add description field to budget

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#336]
The CoST IDS mapping includes the following mapping for funding sources:

![image](https://user-images.githubusercontent.com/19265814/125536444-646b6810-4cf5-455a-89c9-1b9e6e9fa426.png)

However, CoST West Lombok's platform captures the funding sources for a project in a single free-text field, which may combine multiple sources. For example:

Source of Funds | Translation | Notes
-- | -- | --
APBD Kabupaten Lombok Barat dan Hibah DFAT Australia | West Lombok District Budget and Australia DFAT Grant | APBDs are sub-national or local government budgets. DFAT is the Australian Government Department of Foreign Affairs and Trade.
(DAK Reguler Bidang Jalan) yang dituangkan dalam APBD Kabupaten Lombok Barat | (Regular DAK for Roads) as outlined in the APBD of West Lombok Regency | DAK is the Specific Allocation Fund, a policy instrument that enables central government to make ‘specific’ fiscal transfers to regional and district governments for physical facilities and infrastructure

We can recommend that, going forward, CoST West Lombok should capture a list of funding sources for each project, which can be modelled using `budget.budgetBreakdown` and/or the `parties` section. We can also recommend that CoST West Lombok manually cleanse historical data to split out the funding sources for each project. However, this issue is likely to occur with other CoST programmes, which typically implement many of the elements of the CoST IDS as free-text fields in their systems.

OCDS's approach, at the contracting process level, is to have a `description` field on the `Budget` object with the following description:

> A short free text description of the budget source. May be used to provide the title of the budget line, or the programme used to fund this project.

**Proposal**

Add a `description` field to `budget` with the following description:

> A short free-text description of the budget source(s). May be used to provide the title of the budget line, or the programme used to fund this project.

**Alternative**

Another option is to add a single `BudgetBreakdown` object to `budget.budgetBreakdown` and set its `.description` to the free-text description of the funding sources. However, semantically, this is not a breakdown of the budget.

**References:**

* [Overview of Indonesia's Budgeting Process](https://seknasfitra.org/analisis/tentang-anggaran/?lang=en)
* [Australian Government Department of Foreign Affairs and Trade](https://www.dfat.gov.au/)
* [A Regulatory Analysis of The Specific Allocation Fund (DAK) and Horizontal Equalization in Indonesia](https://smeru.or.id/en/content/regulatory-analysis-specific-allocation-fund-dak-and-horizontal-equalization-indonesia)
* [DAK Fisik: Encouraging Government to Provide Quality Basic Services](https://kompak.or.id/en/article/dak-fisik-encouraging-government-provide-quality-basic-services)

**Comment by duncandewhurst** [comment]
@jpmckinney are you happy with the proposal in this issue?

**Comment by jpmckinney** [comment]
Yes. I think the description of `budget.description` in the OCDS 1.2-dev branch has changed in a recent PR, so please refer to that in case any corresponding changes need to be made to the proposal.

**Comment by duncandewhurst** [comment]
Will do. Thanks!
