### ISSUE TITLE
Project identifiers: Update schema description to clarify normative statements, move prefix documentation to schema reference section

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#351]
The description of `id` could be improved to make it clearer (through the use of normative keywords) that the identifier must be unique and must begin with a registered project identifier prefix.

Also, the [prefix documentation and list of registered prefixes](https://standard.open-contracting.org/infrastructure/latest/en/guidance/identifiers/#project-identifier-prefixes) should be moved to the reference section of the documentation, since the list of registered prefixes is normative.

Current description:

> A unique identifier or reference number for this infrastructure project, composed of a project identifier prefix and a local project identifier. For more information, see the [project identifier guidance](https://standard.open-contracting.org/infrastructure/0.9/en/guidance/identifiers/#project-identifier-prefixes).

Proposed description:

> An identifier for this infrastructure project. The identifier must be globally unique and must begin with a registered project identifier prefix. For more information, see the [project identifier guidance](https://standard.open-contracting.org/infrastructure/0.9/en/guidance/identifiers/#project-identifier-prefixes).

cc @neelima-j

**Comment by jpmckinney** [comment]
👍
