### ISSUE TITLE
Clarify definition of parties to include entities in `contractingProcesses/summary`

### ISSUE THREAD

**Issue by neelima-j** [open-contracting/infrastructure#354]
The schema defines parties as "_organizations, economic operators and other participants who are involved in the project and their roles, e.g. buyer, procuring entity, supplier etc."_ 

It isn't explicitly stated that the organizations in `contractingProcesses/summary` are to be included in the parties array, but this can be inferred.

For example, [SISOCS Honduras](https://admin.sisocs.costhonduras.hn/api/v1/all)  does not list any parties from `contractingProcesses/summary`, but **does** include the project level organizations. 

Should this be clarified?

**Comment by jpmckinney** [comment]
> [SISOCS Honduras](https://admin.sisocs.costhonduras.hn/api/v1/all) does not list any parties from contractingProcesses/summary

When I did a quick look at the first example, they are all there except the "Banco Centroamericano de Integración Económica (BCIE)", which is a payer. The `roles` don't 100% match ("INVEST" should have many more roles), but that is a common data quality issue.

**Comment by neelima-j** [comment]
From the 12 collections in the database from 2022, cost_malawi and cost_jalisco have cases where a contracting process has a party that is not mentioned in the parties array.   

Of these, cost_jalisco's error is due to party id being absent, not a mapping omission. 

cost_malawi's parties arrays are haphazard with differing ids for the same entity, leading to the collection being flagged in the query. Several parties from contracting processes are included in the parties array. 

Also, the [worked example](https://standard.open-contracting.org/infrastructure/latest/en/guidance/example/#worked-example) shows what the parties array should contain. 

Therefore we cannot draw a conclusion that the definition needs clarification. 
@duncandewhurst Would you recommend this issue be closed?

**Comment by duncandewhurst** [comment]
I think this is sufficiently covered by the description of `contractingProcesses/summary/suppliers`, which has:

> The full details of each supplier should be added to the project-level parties array with a role of 'supplier'.

and `contractingProcesses/summary/suppliers/id`, which has:

> This must match the id of an entry in the parties section.
