### ISSUE TITLE
Guidance: When to publish

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/infrastructure#357]
We recently had feedback from CoST that a publisher thought that they had to wait until the project was finished before publishing their OC4IDS data, I checked our guidance and I think we could make it more explicit that you can publish throughout the project lifecycle. We could add guidance about this under [publish your data](https://standard.open-contracting.org/infrastructure/latest/en/guidance/publishing/#publish-your-data).

**Comment by duncandewhurst** [comment]
Sounds good! Once https://github.com/open-contracting/infrastructure/pull/355 is merged, please go ahead and create a PR.
