### ISSUE TITLE
additionalClassifications: Clarify semantics and rename

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#373]
`additionalClassifications` is described as:

> One or more additional project classifications may be provided to describe the social or economic focus of the project. This classification may take place against a locally developed codelist, or a globally established codelist.

The semantics aren't very clear. The field description doesn't explain what a project classification is and leaves an open question of what else can the field be used for if not to describe the social or economic focus of the project.

'Purpose' (the socio-economic purpose of the project) from the CoST IDS is mapped to this field (in addition to `purpose`) and the only discussion that I can find or recall about this field describes its use in that context: https://github.com/open-contracting/infrastructure/issues/15. I don't know why the field description uses 'focus' in place of 'purpose'.

I suggest that we update the field description to clarify its semantics, to align with the language from the CoST IDS and to reference `purpose`:

> Classifications of the social or economic purpose of the project. Classifications may use local or global codelists. See also the `purpose` field.

I think that we should also rename the field to `purposeClassifications` as there's no primary `classification` or `purposeClassification` field.

**Comment by duncandewhurst** [comment]
Before deciding on renaming, we can check the OC4IDS database to see if this field is used by any publishers.

**Comment by jpmckinney** [comment]
Typically `additionalClassifications` is deliberately loose, semantically, since the `scheme` provides the narrower semantics. As such, `additionalClassifications` can classify according to purpose, or other use cases (I guess we might be lacking a bit on this front). We only narrow the semantics when there is a prioritized use case for easily selecting a specific classification, and in that case it is usually a singular Classification object rather than an array.

Do we have any other classification use cases?

**Comment by duncandewhurst** [comment]
> Typically `additionalClassifications` is deliberately loose, semantically, since the `scheme` provides the narrower semantics. As such, `additionalClassifications` can classify according to purpose, or other use cases (I guess we might be lacking a bit on this front). 

That makes sense. In which case, I think that we should update the field description to clarify that it can be used for classifications other than socioeconomic purpose. The current description isn't clear either way. Does that sound good?

> We only narrow the semantics when there is a prioritized use case for easily selecting a specific classification, and in that case it is usually a singular Classification object rather than an array.

I don't think we want to specify a singular classification against a specific scheme because:
* We've seen demand in OCDS to classify against both SDGs and SDG targets: https://github.com/open-contracting/standard/issues/1098
* In the initial research and development process, we didn't identify a suitable global classification for socioeconomic purpose: https://github.com/open-contracting/infrastructure/issues/15

> Do we have any other classification use cases?

Not as far as I'm aware. I checked the OC4IDS Database and no publishers are using this field at present: [OC4IDS `additionalClassifications` check](https://colab.research.google.com/drive/1hsXCs2hTZm8hTGUTboaLf7zk_t9weaTD).

**Comment by jpmckinney** [comment]
I think broadening the semantics is a good first step. Since no one is using the field, I don't think we need to create fields with narrower semantics yet.

**Comment by duncandewhurst** [comment]
How about:

> Classifications of the project according to its social and economic purpose or other use cases. Classifications may use local or global codelists. See also the `purpose` field.

**Comment by jpmckinney** [comment]
I suggest for the first part:

> Classifications of the project: for example, according to its social and economic purpose.

Do we need the sentence about global/local codelists? We don't typically include it.

**Comment by duncandewhurst** [comment]
Sounds good! I don't think we need the extra sentence.
