### ISSUE TITLE
Link to schema in /docs/projects/schema.md broken

### ISSUE THREAD

**Issue by pindec** [open-contracting/infrastructure#38]
The [schema file is available here] link in [/docs/projects/schema.md](https://github.com/open-contracting/infrastructure/blob/master/docs/projects/schema.md) 404s.

It points to https://open-contracting.github.io/infrastructure/projects/schema/_static/project-level/project-schema.json

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/infrastructure/commit/fae9560f166fc858177dd3c223db2ebe1801698b
