### ISSUE TITLE
CoST IDS to OCDS mapping: Link in csv-table-no-translate is not rendered

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#383]
In the [rendered table](https://standard.open-contracting.org/infrastructure/latest/en/cost/#completion):

![image](https://user-images.githubusercontent.com/19265814/218882524-df55c36f-fee0-4723-aa8f-e75ec4c82c7f.png)

In the [underlying CSV file](https://github.com/open-contracting/infrastructure/blob/0.9-dev/mapping/reactive-project-level-completion.csv#L2):

```
**Data** See [implementation progress reports](#implementation-progress-reports)
```

Reporting here, but I guess this might be an issue for https://github.com/OpenDataServices/sphinxcontrib-opendataservices/issues.

A workaround would be to replace the link with 'See the guidance on implementation progress reports below'.

**Comment by jpmckinney** [comment]
Why are we using `csv-table-no-translate` instead of `csv-table` anyhow? I think this table wants to translate every cell.

**Comment by duncandewhurst** [comment]
Good question. The contents of the CSV mapping files are indeed translated. I'll replace `csv-table-no-translate` with `csv-table` as part of https://github.com/open-contracting/infrastructure/issues/423.

**Comment by duncandewhurst** [comment]
It seems like the reason is that `csv-table-no-translate` provides an `included_cols` option, which is used to display either the mapping to OC4IDS column or the mapping from OCDS column depending on whether the CSV file is rendered in the CoST IDS to OC4IDS mapping or the OCDS to OC4IDS mapping.

`csv-table` has no equivalent option for filtering columns so I think the solution is to have separate CSV files for each mapping. Sound good?

**Comment by jpmckinney** [comment]
Hmm, to avoid divergence in the first two repeated columns (CoST IDS element, CoST IDS draft definition), maybe `setup()` in `conf.py` needs to generate the separate CSVs (e.g. after the `translate()` calls) from the current CSV?

**Comment by duncandewhurst** [comment]
Sure, that sounds good. Would you be able to make the changes? I'm not exactly sure to where `setup()` would need to write the new files.

**Comment by jpmckinney** [comment]
I won't get to it until 2024 if I do it. They need to be written to `build_dir`, like the translations of `mapping` files.

Btw, I'm not sure if the lines with `static_dir` are necessary – I'm not sure how they arose in #32

**Comment by duncandewhurst** [comment]
Done in https://github.com/open-contracting/infrastructure/pull/459/commits/f817310daf4b08cb8f6e85ecef2f3ce1d8eee71b

**Comment by jpmckinney** [comment]
Closing as described as done (above commit is part of #459)
