### ISSUE TITLE
Language switcher is broken

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/infrastructure#385]
Language toggle is broken at https://standard.open-contracting.org/infrastructure/latest/en/, it gives a 404 for Spanish and English https://standard.open-contracting.org/infrastructure/latest/es/%3f. 

The sites are still there if you manually modify the url to remove the '**%3f**' ie https://standard.open-contracting.org/infrastructure/latest/es/ 

This issue is also affecting the version switcher.

**Comment by duncandewhurst** [comment]
Issue also affects the main OCDS docs site.

**Comment by jpmckinney** [comment]
Fixed - seems like a recent version of Apache was escaping `?` where it wasn't previously.
