### ISSUE TITLE
Update project status codelist and getting started documentation to incorporate maintenance and decommissioning

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#391]
The latest review of OC4IDS has revealed the need to identifying additional stages related to the end of an infrastructure project, names operation and decommissioning. In addition this review has highlighted some inconsistencies with how existing stages are sometimes referred to:

- implementation is sometimes referred to as construction
- procurement is sometimes referred to as tender management

In the case of the additional codes the International Coalition for Sustainable Infrastructure’s [Infrastructure Pathways](https://infrastructure-pathways.org/) and the [RICS ICMS](https://www.rics.org/content/dam/ricsglobal/documents/standards/icms-3-explained.pdf) provide descriptions that can be adapted for use in OC4IDS:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-0371dd13-7fff-dcb4-e522-5c6f7e506e5c">

Stage | Infrastructure Pathways | RICS ICMS
-- | -- | --
Operation | Operations and Maintenance: In this phase, infrastructure owners and operators, including governments, have an opportunity to incorporate climate resilience into the use of infrastructure, through rethinking traditional approaches to inspections, maintenance, day-to-day operations and emergency response to tackle climate change impacts. There are opportunities to influence the resilience of both infrastructure that was originally designed with resilience in mind and infrastructure that was not, including retrofit strategies to enhance resilience. | Operation costs are costs incurred or carbon emitted in running andmanaging a constructed asset, including administrative support services, insurances, energy and environmental/ regulatory inspection costs. Operational costs include operator’s site overheads and taxes and levies, though these are excluded from operational carbon emissions because they are considered to be negligible.Maintenance costs are the total costs and carbon emissions associatedwith labour, material and other resources used to ensure that a constructed asset remains in a state in which it can fulfil its required functions. They include corrective and preventative maintenance, such as cleaning, services, repainting, repairing or replacing parts that are not classed as renewal and that the client wishes to be included in the maintenance budget.
Decommissioning | End-of-Life: At the end of an infrastructure asset’s useful life or when it has become obsolete or redundant, owners and operators have opportunities to maximize the utility of its materials, components and equipment as well as the land it occupies. While these actions do not enhance the resilience of the infrastructure itself, they support broader societal well-being and resilience. | End of life costs are the net costs or fees (after deducting the salvagevalue and other income due to disposal) and/or carbon emissions associated with disposal of an asset at the end of its service life, including those resulting from:• disposal inspection (for costs only, not carbon emissions)• decommissioning and decontamination• demolition and reclamation• reinstatement• asset transfer obligations• recycling (for costs only, not carbon emissions, since credits for recycling are consideredto lie outwith the project boundaries)• recovery• disposal of components and materials and• transport and regulatory costs.Costs include all constructors’ site overheads, risk allowances and taxes and levies, though carbon emissions associated with inspection, and taxes and levies are considered negligible and should not be reported.

</div>

We propose updating the [projectStatus](https://standard.open-contracting.org/infrastructure/latest/en/reference/codelists/#projectstatus) codelist as follows:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-dec34e2d-7fff-d167-e2c4-1bf657cbd86f">

Code | Title | Description | Change
-- | -- | -- | --
identification | Identification | Identification refers to the decision to develop a project within the budget and programme of a project owner (the public entity responsible for executing the budget). **This stage is also called definition.** | Changed
preparation | Preparation | Preparation covers the feasibility study, environmental and social impact assessment, general scoping of the project, establishing the packaging and procurement strategy, preliminary statutory requirements on environmental and land impacts, and the resulting budget authorization. | No change
implementation | implementation | Implementation covers the procurement and implementation of the group of works or services (such as design and supervision) to be delivered under the project, including works or services performed by the procuring entity. This differs from the definition of 'implementation' in OCDS, which covers the implementation but not the procurement. **This stage is also called construction.** | Changed
completion | Completion | Completion covers the handover of the assets and close-out activities with details of the final scope, cost, and delivery time **before maintenance**. | Changed
maintenance | Maintenance | **Maintenance covers any preventative or corrective maintenance and the day-to-day running of the assets. This stage is also called operation.** | New
decommissioning | Decommissioning | **Decommissioning covers the disposal of the assets at the end of their service life. This stage is also called end of life.** | New
completed | Completed | Close-out activities were completed, and this project is inactive. | No change, but deprecated in favour of ‘maintenance’
decommissioned | Decommissioned | **Decommissioning is complete.** | New
cancelled | Cancelled | This project was cancelled before close-out activities were completed, and is inactive. Cancellation can occur anytime after identification **and before maintenance**. | Changed

</div>

where 'identification', 'preparation' and 'implementation' are unchanged but included in the above table for completeness and to show how all codes will look together.

cc @EvelynDinora

**Comment by jpmckinney** [comment]
For the alternative names, we can add a last sentence, like in OCDS, e.g.:

> Implementation covers the procurement (also known as tender management) ... This phase is also called construction.

Note: 'completed' is also unchanged (it's just deprecated).

I updated the table to make the changes clearer (please do so for new issues).

**Comment by jpmckinney** [comment]
Instead of doubling up the names, I think we should just add a sentence at the end, like in OCDS:

> This phase is also called maintenance.
> This phase is also called end of life.

We can then simplify 'decommissioned' to "Decommissioning is complete."

Suggest changing:

* their life -> their service life
* up to the point at which the assets are operational -> , before operation
* the preventative and corrective maintenance required to ensure that the assets remain functional -> any preventative or corrective maintenance [maintenance implies a maintenance of function]

**Comment by duncandewhurst** [comment]
Noting that we'll also need to update the getting started documentation from ['What is project-level data?'](https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/projects/#what-is-project-level-data) onwards to include the new stages. We can use whatever wording we settle on for the code descriptions.

**Comment by duncandewhurst** [comment]
I've updated the proposal with the changes suggested in https://github.com/open-contracting/infrastructure/issues/391#issuecomment-1764896238 and https://github.com/open-contracting/infrastructure/issues/391#issuecomment-1764927602, replacing 'phase' with 'stage' in line with the terminology used in https://standard.open-contracting.org/infrastructure/latest/en/projects/#what-is-the-scope-of-oc4ids and elsewhere.

**Comment by duncandewhurst** [comment]
I've also added "This stage is also called definition." to the description of `identification` as that synonym came up in https://github.com/open-contracting/infrastructure/issues/252

**Comment by duncandewhurst** [comment]
@evelyndinora, following up on our call, are you happy with the proposed status codelist in this issue or would you prefer to the replace 'operation' with 'maintenance'? If we do that, I think the description of the code should still include operation since the project will still be operational during the maintenance stage, e.g.

> Maintenance covers any preventative or corrective maintenance and the day-to-day running of the assets. This stage is also called operation.

**Comment by EvelynDinora** [comment]
@duncandewhurst yes, please, replace "operation" with maintenance and keep the description as it is. I am happy with the proposed code list. Many thanks!

**Comment by EvelynDinora** [comment]
@duncandewhurst I meant like this:Maintenance covers any preventative or corrective maintenance and the day-to-day running of the assets. This stage is also called operation.

**Comment by duncandewhurst** [comment]
Thanks, Evelyn. I've updated the proposal in the issue description.

**Comment by odscjen** [comment]
moving to Agreed

**Comment by duncandewhurst** [comment]
@jpmckinney just checking that you're happy with the revised proposal in the issue description (renaming 'operation' to 'maintenance')?

**Comment by jpmckinney** [comment]
Sure - I can see most infrastructure being maintained rather than operated.
