### ISSUE TITLE
budgetBreakdown - deprecate and introduce a budgetBreakdowns array

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#392]
The summer 2023 IDS/OC4IDS review has surfaced the need to disaggregate the project breakdown but different dimensions,

- Funding source for preparation, implementation and operation (source party per stage)
- Budget for preparation, implementation and operation (amount per stage)
- Budget projections per year (amount per year). 
- Project preparation costs (amount per stage) [Climate finance module]

As the `budgetBreakdown` object stands this would produce confusing data with the sum of the budget breakdowns not equalling the total project value and make it difficult for users to establish which items in the array related to one another.

Suggesting that we deal with this by deprecating the `budgetBreakdown` object and introduce a `budgetBreakdowns` array. Each item in the array would be an object with an `id`, a `description` and a `budgetBreakdown` array whose items are expected to sum to the total project budget. This introduces an extra level of nesting but clearly separates different breakdowns.

e.g.

```json
{
 "budget": {
   "budgetBreakdowns": [
     {
       "id": "1",
       "description": "Breakdown by stage",
       "budgetBreakdown": [
         {
           "id": "1",
           "description": "Preparation budget",
           "amount": {
             "amount": 5000000,
             "currency": "USD"
           },
           "period": {
             "startDate": "2024-01-01T00:00:00Z",
             "endDate": "2024-06-30T00:00:00Z"
           }
         },
         {
           "id": "2",
           "description": "Implementation budget",
           "amount": {
             "amount": 30000000,
             "currency": "USD"
           },
           "period": {
             "startDate": "2024-07-01T00:00:00Z",
             "endDate": "2025-06-30T00:00:00Z"
           }
         }
       ]
     },
     {
       "id": "2",
       "description": "Breakdown by year of implementation",
       "budgetBreakdown": [
         {
           "id": "1",
           "description": "2024 budget",
           "amount": {
             "amount": 20000000,
             "currency": "USD"
           },
           "period": {
             "startDate": "2024-01-01T00:00:00Z",
             "endDate": "2024-12-31T00:00:00Z"
           }
         },
         {
           "id": "2",
           "description": "2025 budget",
           "amount": {
             "amount": 15000000,
             "currency": "USD"
           },
           "period": {
             "startDate": "2025-01-01T00:00:00Z",
             "endDate": "2025-12-31T00:00:00Z"
           }
         }
       ]
     }
   ]
 }
}
```

cc @EvelynDinora

**Comment by jpmckinney** [comment]
+1
