### ISSUE TITLE
Update project definition to cover maintenance and decommissioning

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#394]
OC4IDS defines an infrastructure project as:

> the development of a set of infrastructure assets in a specified location, generally the responsibility of a single procuring entity and budget authority: for example, a highway overpass or a university campus.

I think we'll need to update this to cover operation and decommissioning (see #391).

In particular, we'll need to consider the case where the first OC4IDS data published about a project describes its decommissioning.

cc @evelyndinora

Edit: The definition will need updating in the `description` property of `project-schema.json` and in the ['What is a project?'](https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/projects/#what-is-a-project) section of the getting started documentation.

**Comment by duncandewhurst** [comment]
@EvelynDinora suggested the following in the [mapping document](https://engineersagainstpoverty.sharepoint.com/:w:/r/sites/OC4IDSReview/_layouts/15/Doc.aspx?sourcedoc=%7B85630C49-30BE-4C73-AF68-BAD7A642FC06%7D&file=OC4IDS%20mapping%20and%20clarification%20questions.docx&action=default&mobileredirect=true) (changes in italics):

> the development, *maintenance and disposal* of a set of infrastructure assets in a specified location, generally the responsibility of a single procuring entity and budget authority: for example, a highway overpass or a university campus.

I think that the definition should:

* align with the new project stages proposed in the OC4IDS review, i.e. replace 'maintenance' with 'operation' and 'disposal' with 'decommissioning'.
* explain what 'development' means. It's not currently defined anywhere, but presumably, it was intended to cover the existing project stages: identification, preparation, implementation and completion.
* direct readers to the [What is project-level data?](https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/projects/#what-is-project-level-data) section of the getting started documentation, which explains what each stage covers.  

With those changes:

> the development, *operation and decommissioning* of a set of infrastructure assets in a specified location, generally the responsibility of a single procuring entity and budget authority: for example, a highway overpass or a university campus. *Development covers project identification, preparation, implementation and completion. For more information, see [What is project-level data?](https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/projects/#what-is-project-level-data)*

We'll also need to update the getting started documentation to include the new stages: https://github.com/open-contracting/infrastructure/issues/391#issuecomment-1780099467

**Comment by jpmckinney** [comment]
I think maybe omit the link to the documentation. The schema should ideally be self-sufficient, and I think the proposed changes are otherwise fine.

**Comment by duncandewhurst** [comment]
@evelyndinora following up to our call - was your suggestion to replace 'operation' with 'maintenance' in the definition of project? e.g.

> the development, ~~operation~~ **maintenance** and decommissioning of a set of infrastructure assets in a specified location, generally the responsibility of a single procuring entity and budget authority: for example, a highway overpass or a university campus. Development covers project identification, preparation, implementation and completion.

**Comment by duncandewhurst** [comment]
@EvelynDinora, just checking that you saw my previous comment?

**Comment by EvelynDinora** [comment]
@duncandewhurst, yes, i thought i responded, yes, i am happy with it. I explained our conversation summary to Maria and she is happy with it, too.

**Comment by duncandewhurst** [comment]
Great. Thanks!

@jpmckinney are you happy with the revised definition in https://github.com/open-contracting/infrastructure/issues/394#issuecomment-1804609666?

**Comment by jpmckinney** [comment]
Yes. Matches #391.
