### ISSUE TITLE
Add sustainability modules to mapping documentation

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#395]
# Background

The CoST IDS/OC4IDS review proposes adding the following sustainability-related modules:

- Economic and fiscal
- Environmental and climate
- Climate finance
- Social
- Institutional

These modules are intended to be optional and additional to the ‘core’ CoST IDS.

# Terminology

In order to avoid confusion with the OC4IDS (and OCDS) concept of an extension, this proposal uses the term ‘module’, rather than ‘extension’, to refer to the groupings of disclosures proposed in the OC4IDS review.

For consistency with the existing documentation relating to the CoST IDS, this proposal uses the term ‘element’, rather than ‘data point’, to refer to the individual disclosures within each module.

# Current state

Currently, the OC4IDS documentation includes a [mapping from CoST IDS elements to OC4IDS fields and codes](https://standard.open-contracting.org/infrastructure/latest/en/cost/#cost-ids-to-oc4ids-mapping). The mapping is structured according to the structure of the CoST IDS, with the mapping divided into separate tables by scope (project or contracting process), phase (identification, preparation etc.) and disclosure type (proactive or reactive).

The CoST IDS to OC4IDS mapping is documented on the same [page](https://standard.open-contracting.org/infrastructure/latest/en/cost/#) as the OCDS to OC4IDS mapping and a list of common operations referred to in both mappings.

The top-level structure of the mapping-related content is as follows

- CoST IDS & OCDS Mapping
  - Common operations
  - CoST IDS to OC4IDS Mapping
  - OCDS to OC4IDS Mapping

# Proposal

To meet the need of presenting the sustainability modules as optional and additional to the ‘core’ CoST IDS, I propose moving the existing mapping under a sub-page titled ‘Core standard’ and presenting the sustainability modules on a separate sub-page titled ‘Sustainability modules’

To aid comprehension, I propose including an illustrative JSON example for each mapping.

To meet the needs of the World Bank and GIZ, who expressed a preference for documentation in PDF format, I propose providing instructions for downloading the page in PDF format ([example output](https://drive.google.com/file/d/1kHocGE4yv2fkYoSKBRjBI-kbdLvyqCqF/view?usp=drive_link)) in an admonition.

For example, the mapping for the economic and fiscal module would be presented as follows (note that the final presentation of the individual elements and mappings may differ as this will need to be generated programmatically):

![image](https://github.com/open-contracting/infrastructure/assets/19265814/005c4091-0321-4831-9d87-151b87fb9bc2)

The proposed structure of the mapping content is as follows (new content shown in *italics*):

- CoST IDS & OCDS Mapping
  - Common operations
  - CoST IDS to OC4IDS Mapping
    - Core standard (existing OC4IDS mapping content)
    - _Sustainability modules_
       - _Economic and fiscal_
       - _Environmental and climate_
       - _Climate finance_
       - _Social_
       - _Institutional_
   - OCDS to OC4IDS Mapping
 
# Discussion

@jpmckinney, @evelyndinora - please share your feedback on:

1. Using ‘module’ to describe the groupings of disclosures
2. Using ‘elements’ to describe the individual disclosures
3. The structure of the mapping documentation (i.e. presenting the sustainability modules separately from the main CoST IDS mapping)
4. The presentation of the mapping documentation
5. The approach to providing a downloadable PDF
6. Whether the mapping documentation should include any other content
7. Whether there are any other branding requirements (logos etc.) for the mapping documentation

**Comment by jpmckinney** [comment]
1. OK
2. OK, matches existing usage of "CoST IDS element"
3. OK
4. OK
5. OK
6. No opinion
7. No opinion

**Comment by EvelynDinora** [comment]
Responding as James did:
1. OK
2. OK
3. OK
4. OK
5. OK
6. I don't think so, it is fine the way you are proposing 
7. This should be discussed with OCP at executive level. Let me raised this issue with Petter and John.

**Comment by duncandewhurst** [comment]
Thanks, both!

**Comment by duncandewhurst** [comment]
@jpmckinney, regarding technical implementation, my plan is to take a similar approach to the OCDS for eForms and to generate the sustainability modules mapping documentation from a structured source file using a pre-commit script, rather than rendering a CSV file as a table like in the main CoST IDS mapping. That way, we'll have more flexibility over presentation and it'll be easier to maintain the JSON examples. Does that sound good to you?

If so, was there a particular reason for using YAML rather than JSON as the format for the eForms mapping source file?

**Comment by jpmckinney** [comment]
Sounds good.

YAML required less fastidious quoting and escaping (though it still had some issues, in this respect), and requires fewer non-content characters.
