### ISSUE TITLE
partyRole codelist: Add independentMonitor code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#396]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Independent monitoring </summary>

## Independent monitoring

**Module:** Institutional
**Indicator:** Anti-corruption impact

### Disclosure format

> Identify the entities acting as independent monitors of the project (E.g. [free text])

### OC4IDS mapping

> Project Level: Add an entry to `parties` with 'independentMonitor' included in its `.roles`.

</details>

# Proposal

Add an organisation role for independent monitors.

Add the following codes:

Codelist | Code | Title | Description
-- | -- | -- | --
partyRole | independentMonitor | Independent monitor | An independent organisation appointed to monitor whether a project is being carried out in accordance with applicable anti-corruption laws and regulations.

</div>

# Example

```json
{
 "parties": [
   {
 	"id": "1",
 	"name": "Transparency International New Zealand",
 	"roles": [
   	"independentMonitor"
 	]
   }
 ]
}
```
# Sources

* [PACS Standard 11: Independent Monitoring](https://giaccentre.org/pacs_ps11/)

cc @evelyndinora

**Comment by jpmckinney** [comment]
👍 Just use American spelling (organization).

**Comment by odscjen** [comment]
modellling agreed and approved by CoST offline so moving to Agreed, cc @evelyndinora
