### ISSUE TITLE
protected areas: Add WPDA_ID code to locationGazetteers and protectedAreas boolean field in Environmental object

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#397]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Protected area </summary>

## Protected area

**Module:** Environmental
**Indicator:** Biodiversity impact

### Disclosure format

> Identify whether the project is located in a protected area. Use the project location/coordinates at the [WDPA - World Database of Protected Areas](https://www.arcgis.com/apps/mapviewer/index.html?layers=ae78aeb913a343d69e950b53e29076f7) to disclose the information.

### OC4IDS mapping

> Project level: If the project is located in a protected area: 

 > 1. Set `.environment.inprotectedArea` to true. 
 > 2. Add a `Location` object to the `.locations` array, set its `.id` incrementally and set its `.gazetteer.scheme` to ‘WDPA_ID’ 
 > 3. For each protected area in which the project is located, add the area’s WDPA_ID to the `.gazetteer.identifiers` array. 
> If the project is not located in a protected area, set `.environment.inprotectedArea` to false. 

</details>

# Proposal

Add a boolean field to identifier if the project is taking place in a protected area and if it is add a code to locationGazetteers to allow the use of `location` to give the location of the protected area.

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-89d58d6f-7fff-a9c6-b344-d0bf40874058">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
environment.inprotectedArea  | In protected area | Whether the project is located in a protected area. | boolean  | -   

</div>

Add the following codes:

Codelist | Code | Title | Description | Category | Source
-- | -- | -- | -- | -- | --
locationGazetteers | WPDA_ID | World Database of Protected Areas | The World Database of Protected Areas (WDPA) is the most comprehensive global database of marine and terrestrial protected areas, updated on a monthly basis. It is a joint project between UN Environment Programme and the International Union for Conservation of Nature (IUCN). The compilation and management of the WDPA is carried out by UN Environment Programme World Conservation Monitoring Centre (UNEP-WCMC), in collaboration with governments, non-governmental organisations, academia and industry. | Universal | https://data-gis.unep-wcmc.org/server/rest/services/ProtectedSites/The_World_Database_of_Protected_Areas/FeatureServer

</div>

# Example

```json
{ 
 "environment": { 
   "inProtectedArea": true 
 }, 
 "locations": [ 
   { 
     "id": "1", 
     "gazetteer": { 
       "scheme": "WDPA_ID", 
       "identifiers": [ 
         "555566673" 
       ] 
     } 
   } 
 ] 
} 
```
This relates to the larger creation of an `Environment` object issue https://github.com/open-contracting/infrastructure/issues/393
cc @evelyndinora

**Comment by EvelynDinora** [comment]
Great!

**Comment by jpmckinney** [comment]
At https://github.com/open-contracting/infrastructure/issues/393#issuecomment-1764936248 I suggest `inProtectedArea`

**Comment by odscjen** [comment]
Thanks @jpmckinney, I'd missed that in the other issue when writing up this one, I've edited the description now to use that name
