### ISSUE TITLE
environmental impact: classificationScheme code and array of classification objects

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#398]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Environmental impact category </summary>

## Environmental impact category

**Module:** Environment and climate
**Indicator:** Environmental impact

### Disclosure format
> Indicate the category that reflects the magnitude of environmental impact. Consider the following to rate the project: - Category A: projects with potential significant adverse environmental or social risks and/or impacts that are diverse, irreversible, or unprecedented. - Category B: projects with potential limited adverse environmental or social risks and/or impacts that are few in number, generally site-specific, largely reversible, and readily addressed through mitigation measures. - Category C: projects with minimal or no adverse environmental or social risks and/or impacts.  (Select from a list: A/B/C - Specify list as IFC's Environmental and Social Categorization).  If the analysis was not developed, select the option “assessment not conducted in project appraisal”.

### OC4IDS mapping

> Project level:  1. If an environmental impact assessment was conducted, set `.environment.hasImpactAssessment` to true. If an environmental impact assessment was not conducted, set `environmental.hasImpactAssessment` to false. 2. Add a `Classification` object to the `.environment.impactClassifications` array, set its `.scheme` to “ifc-environmental-social” and set its `.id` to the letter for the category into which the project falls. 

</details>

# Proposal

Add a boolean `hasImpactAssessment` field to a new `environment` object (summarised in [this issue](https://github.com/open-contracting/infrastructure/issues/393)), create array of `Classification` objects called `impactCategories` to hold the categorization of the impact, and add the code “ifc-environmental-social” to the classificationScheme codelist to allow the classification of the environmental impact of the project

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-0329bcce-7fff-2997-e2d3-37aa80250545">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
environmental.hasImpactAssessment | Has impact assessment | Whether an environmental impact assessment has been conducted. | boolean | -
environmental.impactCategories | Impact categories | The categories of the environmental impact of the project. | array of `Classification` objects | -

</div>

Add the following codes:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-42c35945-7fff-2295-4e2d-68ecabfd8fc2">

Codelist | Code | Title | Description
-- | -- | -- | --
classificationScheme | ifc-environmental-social | International Finance Corporation’s Policy on environmental and social sustainability | As part of the review of environmental and social risks and impacts of a  proposed investment,IFC uses a process of environmental and social categorization to reflect the magnitude of risks and impacts

</div>

# Example

```json

{ 
 "environment": { 
   "hasImpactAssessment": true, 
   "impactCategories": [ 
 	{ 
   	"scheme": "ifc-environmental-social", 
   	"id": "a" 
 	} 
   ] 
 } 
} 

```
# Sources

International Finance Corporation’s Policy on Environmental and Social Sustainability (paragraph 40) https://www.ifc.org/content/dam/ifc/doc/mgrt/sp-english-2012.pdf

cc @evelyndinora

**Comment by jpmckinney** [comment]
👍 but impactCategorizations > impactCategories (categorization means more the "scheme" that contains categories)

**Comment by odscjen** [comment]
good catch, that's what I get for changing field names at the end of the day!

**Comment by odscjen** [comment]
moving to Agreed as this was marked as approved by CoST in offline discussions
