### ISSUE TITLE
beneficialOwners: incorporate beneficialOwners information using OCDS extension

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#399]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Beneficial ownership </summary>

## Beneficial ownership

**Module:** Institutional
**Indicator:** Access to Information

### Disclosure format

> ​​D​isclose the ​beneficial owners​ of the contractors and suppliers appointed in the project (E.g. [​name, identifier​]).  

### OC4IDS mapping

> Use modelling from[ OCDS Beneficial Owners extension](https://extensions.open-contracting.org/en/extensions/beneficialOwners/master/) 

</details>

# Proposal

Add a `beneficialOwners` object to the `parties` array following the modelling from the [OCDS Beneficial Owners](https://extensions.open-contracting.org/en/extensions/beneficialOwners/master/) extension.

# Example

```json
{
  "parties": [
    {
      "id": "AHL",
      "name": "Alpha Holdings Ltd",
      "beneficialOwners": [
        {
          "id": "1",
          "name": "Juan Perez",
          "identifier": {
            "scheme": "PRY-IDCARD",
            "id": "12345"
          },
          "nationalities": [
            "PY"
          ],
          "address": {
            "streetAddress": "Avenida Eusebio Ayala 1347",
            "locality": "Asunción",
            "region": "Gran Asunción",
            "postalCode": "1001",
            "countryName": "Paraguay"
          },
          "email": "jperez@example.com",
          "faxNumber": "+595210000001",
          "telephone": "+595210000000"
        }
      ]
    }
  ]
}

```

cc @evelyndinora

**Comment by odscjen** [comment]
@jpmckinney any comments of objections to this proposal?

**Comment by jpmckinney** [comment]
👍

**Comment by duncandewhurst** [comment]
Moving to agreed as this change was already discussed with CoST.
