### ISSUE TITLE
sustainability criteria: capture if sustainability was a criteria of the award decisions

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#400]
This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Sustainability criteria </summary>

## Sustainability criteria

**Module:** Institutional
**Indicator:** Award criteria

### Disclosure format

> Identify the presence of sustainability and non-price attributes in the award ​​criteria. 

### OC4IDS mapping

> Contracting process level: Add a `Sustainability` object to the `.summary.tender.sustainability` array and add ‘awardCriteria’ to its `.strategies` array. 

</details>

# Proposal

Add a `sustainability` array to `contractingProcesses.summary.tender` using the OCDS [Sustainability extension](https://extensions.open-contracting.org/en/extensions/sustainability/master/) model.

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-0fb5c5e5-7fff-4d90-31c6-115c6e1b72bd">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
tender.sustainability | Sustainability | Information about how the contracting process incorporates sustainable public procurement. | object | -
Sustainability.strategies | Strategies | The strategies used to pursue the sustainability goal(s), using the sustainabilityStrategy codelist | array of strings | sustainabilityStrategy

</div>

# Example

```json
{
  "contractingProcesses": [
    {
      "id": "1",
      "summary": {
        "tender": {
          "sustainability": [
            {
              "strategies": [
                "awardCritera"
              ]
            }
          ]
        }
      }
    }
  ]
}

```
cc @evelyndinora

**Comment by odscjen** [comment]
@jpmckinney any comments or objections to this proposal?

**Comment by jpmckinney** [comment]
👍

**Comment by duncandewhurst** [comment]
Moving to agreed as this change was already discussed with CoST.

**Comment by duncandewhurst** [comment]
Noting that `manage.py update` does not copy the `Tender` definition from OCDS so the proposed changes can be made by directly editing `project-schema.json`.
