### ISSUE TITLE
climate measures: list climate measures planned using climateMeasures codelist and object in environment

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#402]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>
<summary> Climate measures </summary>

## Climate measures

**Module:** Environmental and climate
**Indicator:** climate risk

### Disclosure format

> Clarify whether the project design considered climate change mitigation and/or adaptation measures,. disclosing the design demonstrating how the measures were incorporated. This can comprise, without limitation the following: 

- use of lower-emission sources of energy 
- use of lower-emission materials 
- use of recycled and reused materials 
- regenerative design 
- retrofitting design 
- use of carbon capture technology 
- assessment of extreme weather events 
- assessment of precipitation patterns 
- assessment of rising temperatures 
- assessment of rising sea levels 
- others (explain)  

And [Document]). 

### OC4IDS mapping

> Project level:  For each measure add a `ClimateMeasure` object to the `environment.climateMeasures` array, setting it’s `.type` according to the matching code in the open climateMeasuresType codelist and mapping the further explanation to its `.description`. If there is an accompanying document publish in `documents`, with `.documentType` set to 'climateMeasures’ and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 

</details>

# Proposal

Create a `climateMeasure` object comprising a `type` and `description`. An array of these measures will be created as `climateMeasures` within the new `environment` object (see https://github.com/open-contracting/infrastructure/issues/393). `climateMeasure.type` will take from an open codelist, climateMeasures.

“climateMeasures” will be added to the documentType codelist to identify accompanying documentation the publisher may have.

Research is still required to fully define the climateMeasures codelist.

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-5ed1576f-7fff-d7d0-c7e8-a45343122f92">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
environment.climateMeasures | Climate measures | The measures adopted by the project to adapt to or mitigate against climate change. | array of `ClimateMeasures` objects | -
ClimateMeasure | Climate measure | A measure adopted by the project to adapt to or mitigate against climate change. | object | -
ClimateMeasure.type | Type | The type of climate measure, using the open climateMeasures codelist. | string | climateMeasures
ClimateMeasure.description | Description | A short description of the climate measure. |   | -

</div>

Add the following codes:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-f3ab20bc-7fff-e3a7-246c-90989f6a3463">

Codelist | Code | Title | Description
-- | -- | -- | --
climateMeasures | TBD | TBD | Use of lower-emission sources of energy
climateMeasures | TBD | TBD | Use of lower emission material
climateMeasures | TBD | TBD | Use of recycled and/or reused materials
climateMeasures | regenerativeDesign | Regenerative design | TBD
climateMeasures | TBD | TBD | Use of carbon capture technology
climateMeasures | TBD | TBD | Assessment of extreme weather events
climateMeasures | TBD | TBD | Assessment of precipitation patterns
climateMeasures | TBD | TBD | Assessment of rising temperatures
climateMeasures | TBD | TBD | Assessment of rising sea levels
documentType | climateMeasures | Climate measures | Documentation detailing measures to be taken by the project to adapt to or mitigate against climate change.

</div>

# Example

```json

{ 
 "environment": { 
   "climateMeasures": [ 
 	{ 
   	"type": "regenerativeDesign", 
   	"description": "Regenerative design measures for the project include..." 
 	} 
   ] 
 }, 
 "documents": [ 
   { 
 	"id": "1", 
 	"documentType": "climateMeasures", 
 	"url": "http://example.com/climateMeasures.pdf" 
   } 
 ] 
} 

```

# Sources

* [WWF infrastructure - State of the practice report](https://wwfint.awsassets.panda.org/downloads/wwf_infrastructure_full_report_2018.pdf)
* [WWF KPMG Measuring sustainability in infrastructure investment](https://wwfeu.awsassets.panda.org/downloads/kpmg_full_report.pdf)
* [Testing industry attitudes toward a common reporting approach for ESG data use in infrastructure investment](https://www.guggenheiminvestments.com/GuggenheimInvestments/media/PDF/2022-KPMG-ESG-Data-Report.pdf)
* [Key assessment indicators for teh sustainability of infrastructure projects](https://www.researchgate.net/publication/265623124_Key_Assessment_Indicators_for_the_Sustainability_of_Infrastructure_Projects)

cc @evelyndinora

**Comment by odscjen** [comment]
[SuRe ST01 standard](https://sure-standard.org/wp-content/uploads/2021/07/ST01_Normative_Standard_v2.0_clean.pdf)

Theme E1: Climate
Criterion E1.1. Climate Change Mitigation
Mentions the following measures a project may take to reduce project related GHG emissions:
* adoption of renewable energy sources
* energy effeciency improvements
* reduction of fugitive emissions
* reduction of embodied energy
* afforestation and reduction in deforestation
* changes in project siting that reduce GHG emissions required for service delivery

Criterion E1.2 Climate Change Adaptation
Doesn't mention measures that can be taken, instead is very high level "The project shall conduct an assessment based on the best practicable available information and ensure that the project is designed and build to withstand the future climate conditions as identified by the IPCC."

**Comment by odscjen** [comment]
[ENVISION framework from the Institute for Sustainable Infrastsructure](https://sustainableinfrastructure.org/wp-content/uploads/EnvisionV3.9.7.2018.pdf)
Section CR: Climate and Resilience lists credits implementers of the framework can get. From this I've extracted the following measures:
* Reduce embodied carbon of primary materials used of the life of the project (CR1.1) - includes embodied carbon due to production, transportation and replacement/repair of materials
* "The project reduces emissions through the use of best available control systems or best management practices." - refers to Air pollutant emissions, CR1.3 Enhanced
* "The project eliminates air pollutant sources in the design, chooses a non-polluting alternative," - CR1.3 Conserving/Restorative
* "Systems are in place for the ongoing monitoring of any direct sources of air pollution." CR1.3 Enhanced +
* "The project team assesses whether volatile organic compounds harmful to human health are material to the project and, if so, implement strategies to reduce their use during construction and/or within occupied spaces of the completed project." - CR1.3 Superior +
* "The project includes the direct removal of previously existing air pollutant sources, or captures and safely stores/disposes of air pollutants for a net positive impact." CR1.3 Restorative
* The project is designed/sited so as to avoid or mitigate site-related risks. CR2.1 
* A comprehensive climate change vulnerability assessment is carried out. CR2.2
* A comprehensive multihazard risk and resilience assessment is carried out. CR2.3
* Project incorporates elements to increase the durability and ability to withstand hazards of the asset. Mentions ongoing monitoring and maintenance. CR2.5

Section RA: Resource allocation 
* "Reduce the use of virgin natural resources and avoid sending useful materials to landfills by specifying reused materials, including structures, and material with recycled content." RA 1.2 Use recycled materials

**Comment by odscjen** [comment]
Suggestion for codes following codelist research

Codelist | Code | Title | Description
-- | -- | -- | --
climateMeasures | embodiedEnergyReduction | Reduction of embodied energy | Measures that reduce the sum of energy required to produce, transport and repair or replace the materials used by the project.
climateMeasures | embodiedEmissionReduction | Reduction of embodied emissions | Measures that reduce the sum of emissions generated by the production, transportation and replacements or repair of materials used by the project.
climateMeasures | fugitiveEmissionReduction | Reduction of fugitive emissions | Measures that reduce greenhouse gas emissions and air pollutants from intentional or unintentional releases, such as methane during transport of natural gas or HFC emission from refrigeration equipment.
climateMeasures | renewableEnergySources | Use of renewable energy sources | The project adopts renewable energy sources and minimizes the use of fossil fuels as an energy source.
climateMeasures | carbonCapture | Use of carbon capture technology | The project incorporates carbon capture and storage technologies.
climateMeasures | recycledMaterials | Use of recycled and/or reused materials | Measures that “reduce the use of virgin natural resources and avoid sending useful materials to landfills by specifying reused materials, including structures, and material with recycled content."
climateMeasures | regenerativeDesign | Regenerative design | The project has used a regenerative design approach. “Regenerative design is a system of technologies and strategies, based on an understanding of the inner working of ecosystems that generates designs to regenerate rather than deplete underlying life support systems and resources within socio-ecological wholes”
climateMeasures | locationAnalysis | Location analysis | An assessment of the project location has been undertaken to avoid or mitigate against site specific future climate related risks.
climateMeasures | climateRiskAnalysis | Climate risk analysis | Assessments have been carried out based on the best practicable available information to ensure the project is designed and built to withstand future climate conditions, taking into account elements including rising sea levels, rising temperatures, extreme weather events and changing precipitation patterns.
documentType | climateMeasures | Climate measures | Documentation detailing measures to be taken by the project to adapt to or mitigate against climate change.

## Sources
* Fugitive emissions [GRESB Performance Greenhouse Gas Emissions](https://documents.gresb.com/generated_files/infrastructure/2023/asset/reference_guide/complete.html#performance-energy)
* [Embodied energy](https://en.wikipedia.org/wiki/Embodied_energy)
* recycledMaterials [ENVISION RA 1.2](https://sustainableinfrastructure.org/wp-content/uploads/EnvisionV3.9.7.2018.pdf) pg 96
* regenerativeDesign {RIBA Built for the Environment report](https://www.architecture.com/knowledge-and-resources/resources-landing-page/built-for-the-environment-report#available-resources) pg 66, endnote 21
* siteAnalysis based on ENVISION CR 2.1 
* climateRiskAnalysis based on SuRe E1.2 and encompassing the specified elements from the initial CoST suggested list.

## Changes
* Changed items which referred to “lower” to “reduction” to better match other reporting standards which refer to reduction.
* The assessment points have been combined into a single climateRiskAnalysis point as I found no evidence that these would be separate issues but that a climate risk assessment would consider all of these things as applicable to the project. Also added an additional site specific one as this was included in both the ENVISION and SuRe standards. These are slightly different as the siting one is about avoiding or mitigating against risks but the climateRiskAnalysis is about ensuring mitigating and adapting to the risks that can’t be avoided/mitigated by choosing a different site.

cc @evelyndinora, @jpmckinney, @mgraca-prado

**Comment by jpmckinney** [comment]
Looks good to me!

**Comment by odscjen** [comment]
@EvelynDinora @mgraca-prado and comments, clarifications or objections to the codelist codes and descriptions suggested in https://github.com/open-contracting/infrastructure/issues/402#issuecomment-1786940326

**Comment by EvelynDinora** [comment]
@odscjen happy with the proposal.

**Comment by mgraca-prado** [comment]
@odscjen 

Just to make this consistent with the conservation measures, should we replace the word 'siting' for location in the below?

climateMeasures | **siting**Analysis | **Site** analysis | An assessment of the project **siting** has been undertaken to avoid or mitigate against site specific future climate related risks.

**Comment by odscjen** [comment]
@mgraca-prado sounds good to me, @jpmckinney does that make more sense?

**Comment by odscjen** [comment]
good point @mgraca-prado I've updated that in the table above

**Comment by odscjen** [comment]
Having made that change suggested by Maria I'm moving this to Agreed
