### ISSUE TITLE
Labor obligations: record labor obligations included in contracts in new social object

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#404]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Labour obligations </summary>

## Labour obligations

**Module:** Social
**Indicator:** Labour compliance

### Disclosure format
> Disclose labour obligations in the construction contract. This can include, without limitation, the following:  

- Minimum wage 
- Overtime 
- Prohibition of forced labour 
- Prohibition of child labour 
- Equal opportunity 
- Non-discrimination 
- Freedom of association 
- Grievance mechanism 
- Working at height 
- Underground work 
- Handling of materials/equipment 
- Monitoring of accidents 
- Traffic management 
- Accommodation 
- Protective equipment 
- Others (explain) 

> Contracting process level: Publish a summary of the labor obligations: 
1. For each labor obligation in the contract, add a code from the laborObligations codelist to the`.summary.social.laborObligations.obligations` array. 
2. Optionally, add a further explanation of the labor obligations to `.summary.social.laborObligations.description`. Publish the bidding documents that specify labor obligations: Add a document to `.summary.documents`, set its `.id` incrementally, set its `.documentType` to ‘biddingDocuments’ and set its `.url` to the URL at which the documents are available. Publish the signed contract that includes labor obligations:  Add a document to `.summary.documents`, set its `.id` incrementally, set its `.documentType` to ‘contractSigned’ and set its `.url` to the URL at which the signed contract that includes labor obligations is accessible. 

</details>

# Proposal

Create an `laborObligations` object within the new `social` object (see overarching [issue](https://github.com/open-contracting/infrastructure/issues/403)). This shall include an `obligations` array of codes taken from the open ‘laborObligations’ codelist, and a `description` field. 

Research is still required to fully define the codelist

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-6c7fc696-7fff-bbe9-c51b-a9feb3a2b98b">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
social.laborObligations | Labor obligations | Information about labor obligations stipulated in the construction contract(s). | object | -
laborObligations.obligations | Obligations | The labor obligations stipulated in the construction contract(s), using the open laborObligations codelist. | array of strings | laborObligations
laborObligations.description | Description | A short description of the labor obligations | string | -

</div>

Add the following codes:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-b8bcb924-7fff-8b4a-55b7-2cc2c640397a">

Codelist | Code | Title | Description
-- | -- | -- | --
laborObligations | minimumWage | Minimum wage | TBD
laborObligations | overtime | Overtime | TBD
laborObligations | prohibitionForcedLabor | Prohibition of forced labor | TBD
laborObligations | prohibitionChildLabor | Prohibition of child labor | TBD
laborObligations | equalOpportunities | Equal opportunities | TBD
laborObligations | nondiscrimination | Non-discrimination | TBD
laborObligations | grievanceMechanism | Grievance mechanism | TBD
laborObligations | workingAtHeight | Working at height | TBD
laborObligations | undergroundWork | Underground work | TBD
laborObligations | handling | Handling of materials/equipment | TBD
laborObligations | accidentMonitoring | Monitoring of accidents | TBD
laborObligations | trafficManagement | Traffic management | TBD
laborObligations | accommodation | Accommodation | TBD
laborObligations | protectivePersonalEquipment | Protective personal equipment | TBD

</div>

# Example

```json

{ 
 "contractingProcesses": [ 
   { 
 	"id": "1", 
 	"summary": { 
   	"social": { 
     	"laborObligations": { 
       	"obligations": [ 
         	"minimumWage", 
         	"paidOvertime" 
       	], 
       	"description": "The contract's labor obligations include a minimum wage of $20 per hour and an overtime limit of 10 hours per week." 
     	} 
   	} 
     } 
   }
 ]
}

```

# Sources
* [SuRE - Standard for Sustainable and Resilient Infrastructure](https://sure-standard.org/wp-content/uploads/2021/07/ST01_Normative_Standard_v2.0_clean.pdf)
* [World Bank Environmental and Social framework](https://thedocs.worldbank.org/en/doc/837721522762050108-0290022018/original/ESFFramework.pdf)
* [Equator principles](https://equator-principles.com/app/uploads/The-Equator-Principles_EP4_July2020.pdf) - specifically for Grievance mechanisms
* [GRESB 2023 Infrastructure Asset Standard and Reference Guide](https://documents.gresb.com/generated_files/infrastructure/2023/asset/reference_guide/complete.html#performance-health-and-safety)

cc @evelyndinora

**Comment by jpmckinney** [comment]
Maybe:

* forcedLaborProhibition
* childLaborProhibition
* materialsEquipmentHandling

Why was paid overtime changed to just overtime?

**Comment by odscjen** [comment]
> Why was paid overtime changed to just overtime?

Because I'd changed it from overtime to paid overtime initially and realised that it wasn't clear that this was what was intended when this code was originally suggested by CoST. It could have also been meant to reflect agreements around limiting overtime hours, e.g. in the [SuRe standard](https://sure-standard.org/wp-content/uploads/2021/07/ST01_Normative_Standard_v2.0_clean.pdf) Criterion S2.7 Working Hours and Leave asks for evidence that there is a:
> Relevant clause in the employment policy detailing working hours and weekly rest (working hours not exceeding 48 hours a week on a regular basis, and overtime limited to 12 hours a week on a voluntary basis).

@evelyndinora was the overtime point relating to limiting hours or ensuring they are paid?

**Comment by EvelynDinora** [comment]
@odscjen It is ensuring they are paid, but both are important to ensure good practice in working conditions

**Comment by odscjen** [comment]
Based on the previous comments and further research suggesting the following codelists with descriptions. These descriptions still need altered to ensure they use non-normative language.

Codelist | Code | Title | Description
-- | -- | -- | --
laborObligations | minimumWage | Minimum wage | A minimum wage that an employer must pay their labor force for work performed, which cannot be reduced by collective or individual agreements or contracts.
laborObligations | paidOvertime | Paid overtime | Agreement that hours worked in addition to regular working hours will be paid at an specified level.
laborObligations | weeklyRestProtection | Weekly rest protection | Regular working hours and voluntary overtime are both capped to protect a minimum level of weekly rest.
laborObligations | forcedLaborProhibition | Prohibition of forced labor | The project shall not resort to any form of forced labor and will comply with all applicable national and international laws regarding forced or compulsory labor.
laborObligations | childLaborProhibition | Prohibition of child labor | The project shall not resort to any form of child labor and will comply with all applicable national and international laws regarding employment of minors.
laborObligations | equalOpportunities | Equal opportunities | Employment opportunities will not be based on personal characteristics unrelated to job requirements.
laborObligations | nondiscrimination | Non-discrimination | The project will not discriminate against any employees with respect to any aspects of employment, such as hiring, wages, access to training, job assignment, promotion, or termination of employment.
laborObligations | grievanceMechanism | Grievance mechanism | The project will provide accessible and transparent grievance mechanisms to enable all workers to raise workplace concerns.
laborObligations | workingAtHeight | Working at height | Adequate fall prevention and protection measures will be implemented wherever workers are expected to work at height.
laborObligations | undergroundWork | Underground work | ~The project will provide adequate occupational health and safety equipment, information and services appropriate for underground work in compliance with the Safety and Health in Mines Convention, 1995.~ The project will provide adequate occupational health and safety equipment, information and services appropriate for underground and excavation work such as drilling, blasting, rock bolting and soft soil work.
laborObligations | materialsEquipmentHandling | Handling of materials/equipment | The project will ensure that all workers engaged in handling of materials or equipment as part of their employment will receive at no cost to themselves adequate training and appropriate protective equipment.
laborObligations | accidentMonitoring | Monitoring of accidents | The project commits to monitor, document and report on all occupational accidents, diseases and incidents.
laborObligations | trafficManagement | Traffic management | The project will adopt road safety initiatives proportional to its scope and nature that are protective of project workers and other road users.
laborObligations | accommodation | Accommodation | The project will provide accommodation services to workers that accommodate their physical, social and cultural needs and protect and promote their health, safety and well-being.
laborObligations | protectivePersonalEquipment | Protective personal equipment | The project will provide access to, training in, and maintenance of appropriate personal protective equipment at no additional cost to its workers.

## Sources
* minimumWage [ILO](https://www.ilo.org/global/topics/wages/minimum-wages/definition/WCMS_439072/lang--en/index.htm#1) 
* Forced labor and child labor prohibitions ( S2.4), weeklyRestProtection (S2.7) [SuRe](https://sure-standard.org/wp-content/uploads/2021/07/ST01_Normative_Standard_v2.0_clean.pdf)
* equal opportunities, non-discrimination, materials equipment handling, accident monitoring, accommodation [The World Bank Environmental and Social Standards - ESS2 Labor and Working Conditions](https://thedocs.worldbank.org/en/doc/837721522762050108-0290022018/original/ESFFramework.pdf#page=45&zoom=80)
* grievance mechanisms [The World Bank Environmental and Social Standards - ESS2 Labor and Working Conditions](https://thedocs.worldbank.org/en/doc/837721522762050108-0290022018/original/ESFFramework.pdf#page=45&zoom=80) and [SuRe criterion S2.6 Employee Grievance Mechanism](https://sure-standard.org/wp-content/uploads/2021/07/ST01_Normative_Standard_v2.0_clean.pdf)
* working underground [ILO guide to international labour standards](https://www.ilo.org/wcmsp5/groups/public/---ed_norm/---normes/documents/publication/wcms_246944.pdf) convention no. 176
* traffic management (section 3.4), PPE, working at height (section 2.3)  [IFC general EHS guidelines ](https://www.ifc.org/content/dam/ifc/doc/2000/2007-general-ehs-guidelines-en.pdf) 

## Discussion
* The only mention I could find of specifics relating to working underground was specifically related to Mines. @EvelynDinora , @mgraca-prado is there some other type of underground work that should be covered here?

**Comment by mgraca-prado** [comment]
Hi Duncan,  @duncandewhurst 
The reference to underground work aims at also including broad excavation works such as drilling, blasting,rock bolting or soft soil work. Maybe we could leave the definition a bit wide than mining, What do you think?

Source:
https://www.lawinsider.com/dictionary/underground-work

https://www.labor.nc.gov/underground-construction#:~:text=Underground%20construction%20refers%20to%20the,electrical%20transmission%20and%20distribution%20lines.

**Comment by duncandewhurst** [comment]
That sounds good to me, I think that we can replace the reference to the mines convention with that clarification:

> The project will provide adequate occupational health and safety equipment, information and services appropriate for underground and excavation work such as drilling, blasting, rock bolting and soft soil work.

**Comment by odscjen** [comment]
Thanks @mgraca-prado I've updated the table in https://github.com/open-contracting/infrastructure/issues/404#issuecomment-1787459859 with Duncan's suggestion based on your clarification.

@mgraca-prado @jpmckinney @EvelynDinora any objections or clarifications to the rest of the list or can we move this into the Agreed column?

**Comment by jpmckinney** [comment]
LGTM. Just make sure to use non-normative words instead of shall, must, etc. in the code descriptions when making the PR. Most codes just use "will", instead.

**Comment by EvelynDinora** [comment]
@odscjen Agree with James, and no objections from our side.

**Comment by odscjen** [comment]
Great, thanks both, I'll move this to Agreed now and add a note to the proposal to update the descriptions with non-normative language as part of the PR
