### ISSUE TITLE
construction materials: record tests undertaken as part of construction

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#405]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Construction materials testing </summary>

## Construction materials testing

**Module:** Social
**Indicator:** Health and safety

### Disclosure format

> Disclose materials tests performed during implementation [document]. These can include, without limitation, the following:  

- Foundations 
- Pavements 
- Soil 
- Steel structure 
- Asphalt 
- Retaining walls 
- Concrete 
- Masonry 
- Roofs 
- Compression 
- Compaction 
- Thickness 
- Others (explain) 

 [Free text to add not mentioned tests] 

### OC4IDS mapping

> Project level: Publish a summary of the material tests: 1. For each material test, add a code from the materialTests codelist to the`.social.healthAndSafety.materialTests.tests` array. 2. Optionally, add a further explanation of the material tests to `.social.healthAndSafety.materialTests.description`.  Publish test results: For each test result, add a document, set `.documentType` to ‘materialTestResults’ and set `.url` to the URL at which the document is accessible.

</details>

# Proposal

Add a `.materialsTest` object comprising a `.type` array of codes from the open materialTests codelist and a `.description`. Add a `materialTests` array of `materialTest` objects to `social.healthAndSafety`. Add the code ‘materialTestResults` to documentType codelist. (see the overarching social object [issue](#403) for how this fits in with other social obligations related fields.)

Research is still required to fully define the codelist.

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-e5c2c57e-7fff-5562-02cc-5fb934675589">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
social.healthAndSafety.materialTests | Construction materials tests | Information about tests conducted on materials used in the construction of the asset. | object | -
.materialTests.tests | Materials tests | The construction materials or elements that were tested. | array of strings | materialsTests
.materialTests.description | Description | A short description of the tests conducted on the construction materials or elements. | string | -

</div>

Add the following codes:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-428a2474-7fff-d5aa-4a75-4339f4dce8a8">

Codelist | Code | Title | Description
-- | -- | -- | --
materialsTests | TBD | Foundations | TBD
materialsTests | TBD | Pavements | TBD
materialsTests | TBD | Soil | TBD
materialsTests | TBD | Steel structure | TBD
materialsTests | TBD | Asphalt | TBD
materialsTests | TBD | Retaining walls | TBD
materialsTests | TBD | Concrete | TBD
materialsTests | TBD | Masonry | TBD
materialsTests | TBD | Roofs | TBD
materialsTests | TBD | Compression | TBD
materialsTests | TBD | Compaction | TBD
materialsTests | TBD | Thickness | TBD
documentType | materialTests | Material tests | Documentation detailing the results of tests conducted on construction materials.

</div>

# Example

```json

{ 
 "social": { 
   "healthAndSafety": { 
 	"materialTests": { 
   	"tests": [ 
     	"retainingWalls", 
     	"roofs" 
   	], 
   	"description": "Tests were conducted of the main retaining wall and of the roof of each structure according to..." 
 	} 
   } 
 }, 
 "documents": [ 
   { 
 	"id": "1", 
 	"documentType": "materialTestResults", 
 	"url": "http://example.com/materialTestResults.pdf" 
   } 
 ] 
} 

```

# Sources

cc @evelyndinora

**Comment by jpmckinney** [comment]
I think the codes can be singular.

**Comment by odscjen** [comment]
@jpmckinney just to check what you mean there, do you mean that the code for e.g. "Foundations" can be "foundation"?

**Comment by jpmckinney** [comment]
I think both the code and title can be singular, as is already the case with soil.

**Comment by odscjen** [comment]
The initially suggested list is made up of 3 different types of thing:
1. types of material, e.g. soil, asphalt, concrete, masonry
2. elements of a construction, e.g. roofs, retaining walls, steel structures, foundations, pavements
3. types of test, e.g. thickness, compression, compaction

Given the modelling proposed I think this is an issue, for example if a user gave the following:

```json
{
  "social": {
    "healthAndSafety": {
      "materialTests": {
	"tests": [
	  "retainingWall",
	  "concrete",
          "soil",
	  "thickness"
	 ]
      }
    }
  }
}
```
it ambiguous how these codes relate to each other. Was the “thickness” test conducted on both “concrete” AND “soil” or just one of the materials? Or maybe it was only conducted on the “retainingWall” and not the other elements that may also be made of “concrete”? By combining all of these things in a single list it risks making it seem like a project has conducted far more tests than they actually have. Expecting the `.description` field to provide all of this clarity feels very optimistic given the volume of tests a construction project can expect to perform.

I see 2 potential solutions:

1. the list is restricted to 1 of the 3 types, i.e. elements of the construction OR construction material types OR test types, with the associated documents providing all the rest of the information about the other 2 parts of the test.
2. we use the same sort of modelling as in https://github.com/open-contracting/infrastructure/issues/402 and make `materialsTests` an array of `materialTest` objects each of which has a `tests` array of strings and a `description`. A `materialTest` object would describe a single test and in the documentation we’d need to instruct users to combine test codes appropriately to describe the test undertaken, e.g. “concrete”, “retainingWall”, “thickness”.

The 2nd option is complex, possibly too complex but does allow all of the information to be presented in a structured format. The 1st option is significantly simplier but more restrictive (although all of the information can still be shared in the associated documents)

What do you think @duncandewhurst @evelyndinora @mgraca-prado

**Comment by jpmckinney** [comment]
Good catch. It would help to know how this information is typically tracked or monitored. It seems a bit strange to me that some source system would only have tracked that a "thickness test" had been performed.

**Comment by odscjen** [comment]
@EvelynDinora @mgraca-prado any thoughts on this? Do you have access to any datasets that demonstrate how this information is currently currently being captured? Or could you ask Hamish (I think I remember in a previous chat Maria you said that this data point was his suggestion)?

**Comment by EvelynDinora** [comment]
@odscjen let me check with Hamish. I will come back to you ASAP

**Comment by mgraca-prado** [comment]
Hi @odscjen and @EvelynDinora , 
There are many standard codes for testing of construction materials such as ASTM international, Eurocodes, IS Codes, BS Codes,etc.  See here: https://theconstructor.org/building/codes-material-testing/25284/
To simplify the data point, maybe we could create the following categories (the list was created based on the key tests referred to in the link above) and requesting the PE to identify the applicable standard (plus document disclosure of the tests performed)?
List of materials tests:
Asphalt
Aggregate and rock
Bricks
Cement 
Concrete
Coarse and fine aggregate
Masonry
Metallic materials
Mortar
Plywood
Timber
Resin and polymer
Soil
Stone
Other (explain)

**Comment by odscjen** [comment]
ah ha, thanks @mgraca-prado that's really useful.

So to keep this simple (and to avoid having to keep any codelists up-to-date with multiple construction standards that aren't open) we could make the codelist "constructionMaterial" and use the list of materials Maria has listed in the previous comment. And then in the mapping instruct the publisher to list the specific standard tests they've conducted.

e.g.

```json
{
  "social": {
    "healthAndSafety": {
      "materialTests": {
        "materials": [
          "masonry",
          "concrete",
          "aggregateAndRock"
        ],
        "description": "ASTM C617, ASTM C1231, ASTM C88"
      }
    }
  }
}
```

With the mapping guidance
> Project level: Publish a summary of the material tests: 
> 1. For each material tested, add a code from the constructionMaterial codelist to the `.social.healthAndSafety.materialTests.materials` array. 
> 2. Add a further explanation of the material tests to `.social.healthAndSafety.materialTests.description` including the code of the relevant international or national standard the test conformed to. 

> Publish test results: For each test result, add a document, set `.documentType` to ‘materialTestResults’ and set `.url` to the URL at which the document is accessible.

@jpmckinney @mgraca-prado @EvelynDinora how does that sound?

**Comment by odscjen** [comment]
constructionMaterials.csv open codelist

 Code | Title | Description
 -- | -- | --
asphalt | Asphalt | A composite of bitumen and aggregate, used to surface, for example roads, airports and parking lots.
aggregate | Aggregate | Coarse to fine-grained particulate mineral material, including sand, gravel, crushed stone, slag and recycled concrete.
brick | Brick | Mass-produced rectangular unit, used to construct, for example, paving, walls and other building elements. Commonly used in masonry.
cement | Cement | Substance used for binding and hardening other construction materials.
concrete | Concrete | A composite of cement, water and aggregate.
metal | Metal | Metal, including steel, aluminium, iron, copper, lead and other alloys and naturally occurring metals.
mortar | Mortar | A composite paste, used to seal and bind masonry units.
plywood | Plywood | A composite manufactured material composed of thin layers of wood veneer glued together.
timber | Timber | Wood processed into uniform sizes and shapes.
resinAndPolymer | Resin and polymer | Natural or synthetic material made up of large repeatable molecular chains, including epoxy resin, plastic, rubber, vinyl and sealant.
soil | Soil | The upper layer of the earth's surface composed of organic matter, minerals, liquids, organisms and gases. Also known as earth.
stone | Stone | Naturally occurring mineral material that has been quarried, extracted and worked to create a solid unit. Commonly used in masonry.

Sources for definitions
* asphalt - https://en.wikipedia.org/wiki/Asphalt_concrete
* aggregate - https://en.wikipedia.org/wiki/Construction_aggregate
* brick - https://www.designingbuildings.co.uk/wiki/Brick
* cement - https://www.designingbuildings.co.uk/wiki/Cement
* concrete - https://www.designingbuildings.co.uk/wiki/Concrete
* metal - https://www.designingbuildings.co.uk/wiki/Metal_in_construction
* mortar - https://en.wikipedia.org/wiki/Mortar_(masonry)
* plywood - https://en.wikipedia.org/wiki/Plywood
* timber - https://en.wikipedia.org/wiki/Lumber
* resinAndPolymer - https://www.designingbuildings.co.uk/wiki/Polymers_in_construction, https://www.designingbuildings.co.uk/wiki/Resin, https://en.wikipedia.org/wiki/Polymer, https://en.wikipedia.org/wiki/Resin
* soil - https://en.wikipedia.org/wiki/Soil
* stone - https://en.wikipedia.org/wiki/Rock_(geology)

Notes
* Made a single `aggregate` code instead of having one for fine grain and one for coarse + rock
* removed Rock from aggregates and combined it with Stone
* removed masonry as it's not so much a material as the craft of building structures using material units, most commonly brick or stone, both of which have their own code.

**Comment by odscjen** [comment]
@jpmckinney @EvelynDinora just checking if either of you have any comments or objections to the altered modelling suggested in https://github.com/open-contracting/infrastructure/issues/405#issuecomment-1814095291?

Or to the code descriptions in https://github.com/open-contracting/infrastructure/issues/405#issuecomment-1816258238 (also @mgraca-prado for these)

**Comment by jpmckinney** [comment]
Looks good. I suggest removing "or dirt" from soil. Although Wikipedia says so, it's easy to find sources that distinguish the two: basically, things can grow in soil, but not necessarily dirt (depending on its definition). But, if we need to cover dirt, I suppose we could keep it in the definition.

Cement, as defined, can include mortar. Not sure if anything to do about that.

Other small changes:

- Remove: used in a wide range of construction projects
- Remove: used in construction projects
- Remove: for use as a construction material
- aggregates used to surface -> aggregate, used to surface, for example,
- unit used to construct paving, walls and other building elements.  -> unit, used to construct, for example, paving and walls.
- Change to "Metal, including" at the start of the metal description, just to make it a noun phrase, even if a repetitive one
- A composite paste using -> A composite paste, used
- Wood that has been processed -> Wood processed

**Comment by odscjen** [comment]
Thanks @jpmckinney I've updated the descriptions according to your suggestions.

I've left cement as is. In the case were the publisher is using cement as a mortar hopefully the standard they've based their test on will make it clear which code they should use.

**Comment by odscjen** [comment]
had a thumbs up from Maria and the ok from James (with suggestions which have now been applied) so I'm moving this to Agreed.

**Comment by odscjen** [comment]
waiting for https://github.com/open-contracting/infrastructure/pull/428 to be merged before starting PR for this.

**Comment by duncandewhurst** [comment]
> waiting for #428 to be merged before starting PR for this.

Good to go :-)
