### ISSUE TITLE
labor budget: specify the amount set aside in the contract to cover labor costs

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#406]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Labor budget </summary>

## Labor budget

**Module:** Social
**Indicator:** Labor compliance

### Disclosure format

> Disclose the amount allocated by the main contractor to cover for labour costs (E.g. [value]). 

### OC4IDS mapping

> Contract level: Publish the amount and currency of the labor budget in `.summary.social.laborBudget`. 

</details>

# Proposal

Add a `Value` object, `laborBudget` to the new `social` object (see #403).

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-450302af-7fff-3230-8cd4-ef9d69553192">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
social.laborBudget | Labor budget | The budget allocated in the contract for labor costs. | `Value` object | -

</div>

# Example

```json

{ 
 "contractingProcesses": [ 
   { 
 	"id": "1", 
 	"summary": { 
   	"social": { 
     	"laborBudget": { 
       	"amount": 10000000, 
       	"currency": "USD" 
     	} 
   	} 
 	} 
   } 
 ] 
} 

```

## Discussion
* Assuming that the use case for this data point is to do with making sure that labour costs are appropriate, it’s difficult to see what the value of this data point is without also knowing at least the number of person-hours the amount is supposed to cover. This need can be met through comparison or procurement and contract documents so this data point possibly isn’t needed.
* Answer - Over time this data point will allow a comparison of the contracts where there is no labour budget specified vs. contracts where a labour budget exits. This will be very useful information to be assessed in combination with the following data point (health and safety – workers’ accidents). I see a value here from a policy perspective. From interviews some contractors do specify this in their contracts, labor in general covering e.g. PPE costs, overtime, salaries, accomodation. Not a common thing in the contracts. Want to emphasis where there is money protected for labor issues, not really about checking for if a contractor is paying their laborers well, or comparing across projects.

cc @evelyndinora

**Comment by odscjen** [comment]
@jpmckinney any thoughts or objections to this proposal?

**Comment by jpmckinney** [comment]
Looks good!

**Comment by odscjen** [comment]
Previously agreed this offline with CoST so moving to Agreed cc @evelyndinora @mgraca-prado
