### ISSUE TITLE
land compensation budget: specify budgte set aside for land compensation claims

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#407]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Land compensation budget </summary>

## Land compensation budget

**Module:** Social
**Indicator:** Land issues

### Disclosure format

> Disclose budget allocated to fund land compensation (E.g. [value]). 

### OC4IDS mapping

> Project Level: Set `.social.landCompensationBudget` to the amount and currency of the budget allocated for land compensation. 

</details>

# Proposal

Add `Value` object to new `social` object (see #403) titled `landCompensationBudget`.

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-f7d4070d-7fff-6723-31e7-b59de769f878">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
social.landCompensationBudget | Land compensation budget | The budget allocated in the contract for compensation of land. | `Value` object | -

</div>

# Example

```json

{ 
 "social": { 
   "landCompensationBudget": { 
 	"amount": 1000000, 
 	"currency": "USD" 
   } 
 } 
} 

```
cc @evelyndinora

**Comment by odscjen** [comment]
@jpmckinney any objections or thoughts on this proposal?

**Comment by jpmckinney** [comment]
Looks good!

Align field description with #406 (I think "allocated" can also come after "budget" in #406, and here if the "in the contract" phrasing is used).

**Comment by odscjen** [comment]
updated description and as modelling previously agreed with CoST moving to Agreed cc @evelyndinora @mgraca-prado

**Comment by odscjen** [comment]
wait until https://github.com/open-contracting/infrastructure/pull/428 has been merged before creating PR as it contains the parent `social` object.
