### ISSUE TITLE
identify projects overlap with Indigenous land

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#408]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Indigenous land </summary>

## Indigenous land

**Module:** Social
**Indicator:** Indigenous populations

### Disclosure format

> Identify whether the project is located or cut through indigenous land. Use the information at the LandMark – Global Platform of Indigenous and Community Lands on both databases Indigenous Lands Acknowledged by Government and Not Acknowledged by Government (customary tenure or with formal land claim submitted) to disclose the information. 

### OC4IDS mapping

> Project level:  If the project is located or cut through indigenous land: 1. Set `.social.indigenousLand` to `true` 2 Add a `Location` object to the `.locations` array, set its `.id` incrementally and set its description to “Indigenous land: <Name> (<Category>)” substituting <Name>  and <Category> for the name and land category from the Landmark database. If the project is not located or cut through indigenous land, set `.social.indigenousLand` to `false`. 

</details>

# Proposal

Add a boolean `inIndigenousLand` field to the new `social` object (see #403).

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-83213628-7fff-4c47-b46d-453ca5a86454">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
social.inIndigenousLand | In Indigenous land | Whether the project is located in or cuts through Indigenous land. | boolean | -

</div>

# Example

```json

{ 
 "social": { 
   "inIndigenousLand": true 
 }, 
 "locations": [ 
   { 
 	"id": "1", 
 	"description": "Indigenous land: Section 1 Block III Rowallan Survey District (Maori Freehold Land)" 
   } 
 ] 
} 

```

# Sources

* [LandMark: The Global Platform of Indigenous and Community Lands](https://www.landmarkmap.org/data/)

cc @evelyndinora

**Comment by odscjen** [comment]
@jpmckinney do you have any objections to this proposal?

**Comment by jpmckinney** [comment]
Looks good!

**Comment by odscjen** [comment]
previously agreed with CoST offline so moving to Agreed cc @evelyndinora @mgraca-prado

**Comment by odscjen** [comment]
wait until https://github.com/open-contracting/infrastructure/pull/428 has been merged before creating PR as it contains the parent `social` object.
