### ISSUE TITLE
Public consultation meetings: recording details of public consultation meetings during preparation stage

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#409]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Public consultation meetings </summary>

## Public consultation meetings

**Module:** Social
**Indicator:** Public participation

### Disclosure format

> Disclose the occurrence of public meetings with communities and impacted groups including meeting invite, the number of the participants, dates and location of these meetings. 

### OC4IDS mapping

> ​Project Level:  For each meeting: 
1. Publish the meeting invite. Add a document, set its `.documentType` to ‘consultationMeetingInvitation’ and its `.url` to the URL at which the meeting invite is available. 
2. Publish the meeting details. Add a `Meeting` object to the `.social.consultationMeetings` array and set: 
 - `.id` incrementally - `.date` to the date of the meeting 
 - `.address` to the address of the meeting 
 - `.numberOfParticipants` to the number of people that participated in the meeting. 
3. Publish the meeting minutes. Add a document, set its `.documentType` to ‘consultationMeetingMinutes’ and its `.url` to the URL at which the meeting minutes are available. 

</details>

# Proposal

Create a `Meeting` object to be used in the `social.consultationMeetings` array to hold details of public meetings. This object will contain an `id`, a `description` a `location` object and a `numberOfParticipants`. Also add 2 new codes to documentType codelist to allow reference to consultationMeetingInvitation and consultationMeetingMinutes. See #403  for the overarching `Social` object.

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-a7a6ee9d-7fff-7fe7-7ff5-8c5a1e37e684">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
social.consultationMeetings | Public consultation meetings | Information about public consultation meetings held during the project preparation stage. | array of `Meeting` objects | -
Meeting | Meeting | The details of a meeting. | object | -
Meeting.id | ID | A locally unique identifier for the meeting. | string | -
Meeting.date | Date | The date of the meeting | string (date-time) | -
Meeting.location | Location | The location of the meeting | `Location` object | -
Meeting.numberOfParticipants | Participant count | The number of people in attendance at the meeting | number | -

</div>

Add the following codes:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-f2ca25d3-7fff-be43-d452-99f74373688f">

Codelist | Code | Title | Description
-- | -- | -- | --
documentType | consultationMeetingInvitation | Consultation meeting invitation | A document detailing the occurrence of a public consultation meeting relating to the project.
documentType | minutes.consultationMeeting | Consultation meeting minutes | A record of the issues discussed, agreements reached and decisions taken at a public consultation meeting.

</div>

# Example

```json

{ 
 "social": { 
   "consultationMeetings": [ 
 	{ 
   	"id": "1", 
   	"date": "2024-01-01T00:00:00Z", 
   	"address": { 
     	"streetAddress": "1600 Amphitheatre Pkwy", 
     	"locality": "Mountain View", 
     	"region": "CA", 
     	"postalCode": "94043", 
     	"countryName": "United States" 
   	}, 
   	"numberOfParticipants": 12 
 	} 
   ] 
 }, 
 "documents": [ 
   { 
 	"id": "1", 
 	"documentType": "consultationMeetingInvitation", 
 	"url": "http://example.com/consultationMeetingInvitation.pdf" 
   }, 
   { 
 	"id": "2", 
 	"documentType": "consultationMeetingMinutes", 
 	"url": "http://example.com/consultationMeetingMinutes.pdf" 
   } 
 ] 
} 

```

## Discussion

Qu - Are there any use cases that depend on comparing this level of detail across projects? Or would it be enough to just require that the publishers provide documents with these details?
Ans - Seeing patterns of meetings is useful. "How many projects did a consultation process” “Is there a difference in consultation based on funding” Publish the invite first, then what took place (agenda, minutes, location). Use case is being able to see if particular types of projects or particular publishers are having or not having these meetings and which communities are actually engaging in them. Possibly don’t need full details as data but good to have more than just documents for each meeting. Also important to have the options. 

* There’s already a ‘minutes’ code in documentType with the description “Minutes of pre-bid meetings, or other relevant meetings.” Can we reuse this rather than creating ‘consultationMeetingMinutes’? @evelyndinora The use of the `document.description` can make it clear what the type of meeting being minuted was.

cc @evelyndinora

**Comment by jpmckinney** [comment]
OC(4I)DS typically uses the construction numberOfParticipants, not participantCount.

consultationMeetingInvite -> consultationMeetingInvitation

**Comment by duncandewhurst** [comment]
I suggest the following updates to field descriptions so that the `Meeting` definition can be reused to model lobbying meetings (see https://github.com/open-contracting/infrastructure/issues/412):

* `Meeting`: The details of a ~~public consultation~~ meeting.
* `Meeting.numberOfParticipants`: The number of ~~members of the public~~ people in attendance at the meeting.

We should also align the description of 'consultationMeetingMinutes' with the description of 'lobbyingMeetingMinutes' (can just replace 'lobbying' with 'public consultation'):

> A record of the issues discussed, agreements reached and decisions taken at a lobbying meeting.

**Comment by odscjen** [comment]
Thanks both, I've updated the table and example as per your suggestions

**Comment by odscjen** [comment]
@EvelynDinora @mgraca-prado do either of you have an objection to using the existing "minutes" documentType code instead of creating a specific "consultationMeetingMinutes" code for this issue?

**Comment by duncandewhurst** [comment]
I've updated the proposal in the issue description to reflect the suggestion in https://github.com/open-contracting/infrastructure/issues/412#issuecomment-1778245273 (changed 'consultationMeetingMinutes' to 'minutes.consultationMeeting').

**Comment by mgraca-prado** [comment]
@duncandewhurst , Agreed with the proposed change to minutes.consultationMeeting

**Comment by jpmckinney** [comment]
Noting typo (constulationMeetings).

**Comment by duncandewhurst** [comment]
Typo corrected!

**Comment by odscjen** [comment]
sounds like this is now agreed so I'm moving it into the Agreed column

**Comment by odscjen** [comment]
`Meeting` object added in PR https://github.com/open-contracting/infrastructure/pull/428
