### ISSUE TITLE
Indicating alignment with sustainability related policies

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#410]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Policy coherence </summary>

## Policy coherence

**Module:** Institutional
**Indicator:** Investment transparency

### Disclosure format

> Disclose documentation that evidences that the project is part of, or aligned with existing plans and policies, providing further details on the project’s policy alignment.   Consider alignment with: 

- SDGs 
- National plan or strategy 
- Infrastructure plan or strategy 
- Sector plan or strategy 
- Procuring entity plan or strategy 
- Paris Agreement  
- Nationally Determined Contributions (NDCs) 
- National Adaptation Plans 
- Medium-term fiscal frameworks/targets 
- [free text] 

### OC4IDS mapping

> Project level: For each plan or policy to which the project is aligned, add a code from the policyAlignment codelist to the `.policyAlignment.policies` array. Add a further explanation of the project’s policy alignment to `.policyAlignment.description`.  
For each United Nations Sustainable Development Goal to which the project is aligned, add a `Classification` object to the `.additionalClassifications` array, set its `.scheme` to ‘sdg’, set its `.id` to the goal’s number and set its `.description` to the goal’s title. 
For each United Nations Sustainable Development Goal Target to which the project is aligned, add a `Classification` object to the `.additionalClassifications` array, set its `.scheme` to ‘sdgTarget’, set its `.id` to the target’s number and set its `.description` to the target’s title.  
If further documentation of the project’s policy alignment is available, add a document with `.documentType` set to ‘policyAlignment’, `url` set to the URL at which the documentation can be accessed. 
</details>

# Proposal

Add a `policyAlignment` object to include a `description` field and a `policies` array. The `policies` array will take codes from the **open** policyAlignment codelist. The code "policyAlignment" will be added to the open documentType codelist to allow for inclusion and identification of documentation that details this alignment.

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-33a91544-7fff-8151-1799-851d551c5014">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
policyAlignment | Policy alignment | Information about how the project aligns with international, national and/or sectoral policies. | object | -
policyAlignment.policies | Policies | The policies the project is in alignment with, using the open policyAlignment codelist. | array of strings | policyAlignment
policyAlignment.description | Description | A short description of how the project aligns with the policies listed in `.policies`. | string | -

</div>

Add the following codes:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-5f17ab22-7fff-15b3-12fc-43dd3ce4345f">

Codelist | Code | Title | Description
-- | -- | -- | --
policyAlignment | SDG | Sustainable development goals | The Sustainable Development Goals are a collection of 17 interlinked goals set by the United Nations General Assembly and designed to be a "blueprint to achieve a better and more sustainable future for all".
policyAlignment | nationalPlan | National plan or strategy | National plans set out high-level goals and objectives, and the strategies by which these will be achieved. These are used to guide public investment at a national level.
policyAlignment | infrastructurePlan | Infrastructure plan or strategy | Infrastructure plans set out high-level goals and objectives, and the strategies by which these will be achieved. These are used to guide public investment in infrastructure.
policyAlignment | sectorPlan | Sector plan or strategy | Sector plans set out high-level goals and objectives, and the strategies by which these will be achieved. These are used to guide public investment in the named sector. 
policyAlignment | procurementPlan | Procurement plan or strategy | Procurement plans set out the goods, services and works a procuring entity plans to procure over the defined time period.
policyAlignment | parisAgreement | Paris agreement | "The Paris Agreement is a legally binding international treaty on climate change. It was adopted by 196 Parties at the UN Climate Change Conference (COP21) in Paris, France, on 12 December 2015."
policyAlignment | nationallyDeterminedContributions | Nationally determined contributions | "A Nationally Determined Contribution (NDC) is a climate action plan to cut emissions and adapt to climate impacts. Each Party to the Paris Agreement is required to establish an NDC and update it every five years."
policyAlignment | nationalAdaptationPlans | National adaptation plans | "The National Adaptation Plan (NAPs) process was established under the Cancun Adaptation Framework (2010) in order to prepare countries for addressing climate risk in the medium term. The main objectives of the NAPs are to reduce vulnerability to climate change, and to mainstream climate change adaptation in all levels of planning."
policyAlignment | mediumTermFiscalFramework | Medium-term fiscal framework | A medium-term fiscal framework is a multiyear budget tool that combines expenditure ceilings, resource forecasts and baselines of ongoing expenditures.
documentType | policyAlignment | Policy alignment | Documentation detailing how a project aligns with an international, national, sector, or procuring entity policy, plan or strategy.

</div>

# Example

```json

{ 
  "policyAlignment": { 
   "policies": [ 
 	"infrastructurePlan" 
   ], 
   "description": "The project is intended to contribute towards the goals set out in the 2021 Australian Infrastructure Plan." 
 }, 
 "documents": [ 
   { 
 	"id": "1", 
 	"documentType": "policyAlignment", 
 	"url": "http://example.com/infrastructurePlanAlignment.pdf" 
   } 
 ] 
} 

```
# Sources
* Paris agreement - https://unfccc.int/process-and-meetings/the-paris-agreement
* National, sector plans - [IMF PIMA Handbook chapter 5](https://www.elibrary.imf.org/display/book/9781513571829/CH005.)
* NDC's - https://www.un.org/en/climatechange/all-about-ndcs
* NAPs - https://unccelearn.org/course/view.php?id=141&page=overview
* MTEFs - https://www.oecd-ilibrary.org/sites/5b0d4f77-en/index.html?itemId=/content/component/5b0d4f77-en, https://www.oecd.org/gov/budgeting/medium-term-expenditure-frameworks/

# Discussion
* As NDC's are a core part of the Paris Agreement and the main way in which countries who have signed up to the Paris Agreement show they are abiding by it are both codes necessary? @evelyndinora

cc @evelyndinora

**Comment by odscjen** [comment]
Some definitions relating to national and sectoral plans/policies/strategies

term | definition | source | link
-- | -- | -- | --
Industrial/sectorial policy | Industrial policy (or sectoral policy) refers to government interventions to support particular industries or sectors, that are considered strategically important, or to promote cross-industry innovation or exports. Interventions can take many forms, including R&D, preferential financing, skills training, trade policies, tax and regulatory reforms, and direct subsidies. For certain authors or in certain contexts, industrial and sectoral policies may have slightly different meanings. | International Labour Organization | [ILO Productivity ecosystems for decent work - Glossary](https://www.ilo.org/wcmsp5/groups/public/---ed_emp/---emp_ent/documents/publication/wcms_873800.pdf)
National and sectoral planning | Public investment should be guided by strategies that set out the goals and objectives to be achieved through public investment spending and plans for how to realize these. The strategies should set out the direction and high-level ambition or aspirations for future public investment, informed by current gaps and trends (for example, population, technology, environmental) that would shape future infrastructure needs and demands. The plans should explain how public investment goals and objectives will be achieved through a broad portfolio of projects that complement each and prioritize individual major projects. These goals and objectives are nonfinancial in nature, but plans should be subject to broad constraints in terms of the economic viability of addressing the underlying infrastructure needs. Plans should not be expected to go into much detail about major projects and will of ten not include any information on specific smaller projects. Public investment spending contributes to the capital stock and is often driven by gaps in this stock, and thus plans should make some reference to the existing nonfinancial fixed assets. | IMF | [PIMA Handbook chapter 5](https://www.elibrary.imf.org/display/book/9781513571829/CH005.)

**Comment by odscjen** [comment]
@EvelynDinora, @mgraca-prado, @jpmckinney any comments, clarifications or objections to this proposal and the codelist codes and descriptions?

As NDC's are a core part of the Paris Agreement and the main way in which countries who have signed up to the Paris Agreement show they are abiding by it are both codes necessary? @EvelynDinora

**Comment by jpmckinney** [comment]
Where does procuringEntityPlan come from? Does it different from a "procurement plan"? The latter is typically more like a "buyer plan" ("procurement plan" is the typical term).

Otherwise, LGTM

**Comment by odscjen** [comment]
This was one of the initial codes suggested by CoST. I couldn't find a good definition of it but I did find the phrase mentioned in various places. My interpretation of it was:

The "procurement plan" would be the plan for the specific procurement process being discussed.

The "procuring entity plan" is the high level plan the procuring entity has regarding what procurement they plan on making over a specific period of time. So it's similar to the national plans only on a smaller scale, i.e. it's not about what the entire country plans on tackling, it's just what the particular procuring entity plans on doing (at a high level). 

But actually I think you're right and going on some definitions for "procurement plan" e.g. https://www.finance.gov.mv/procurement-plan then actually that's what I was thinking the procuringEntityPlan was, so I'm going to change that.

@evelyndinora is that right, any other comments?

**Comment by EvelynDinora** [comment]
@odscjen yes, that is correct. Thanks

**Comment by odscjen** [comment]
Thanks all, I'm moving this to Agreed now
