### ISSUE TITLE
documentType: new sustainability related codes

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#411]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Procurement strategy </summary>

## Procurement strategy

**Module:** Economic and fiscal
**Indicator:** Procurement viability 

### Disclosure format

> Disclose the procurement strategy risk assessment. This tends to be part of the decision-making strategy and likely includes discussions regarding capabilities, the delivery model and the rationale for the risk allocation decision. (E.g. [Document]).

### OC4IDS mapping
> Project Level: Publish in documents, with `.documentType` set to '​￼​procurementStrategyRiskAssessment' and include a short description and/or a link to a document providing details. 

Relevant feedback from OECD regarding this data point:

"Procurement strategy risk (already included) 

One item that was not touched upon (perhaps through the way the discussion or questionnaires were framed) is that it is not at all discussed how the procurement strategy for an infrastructure project is determined.  

In my understanding the standard already requires revealing the procurement plan (but that may merely refer to the choice of the tendering procedure). It does not inquire on what basis decisions are made regarding: 
* Inhouse capabilities (what will be bought on the market and what insourced – pertains primarily to the capabilities of the client to be a competent buyer) 
* The packaging decision – on what grounds is a project packaged into a single contract and when are there multiple contracts 
* The risk allocation decision – on what grounds is the delivery model for a particular package chosen – when a DBB, DB, EPC, when a PPP 

These issues are hugely important and can make or break the outcomes of the project just as the preceding phases of project appraisal. "
</details>

<details>

<summary>Life cycle cost calculation methodology </summary>

##  Life cycle cost calculation methodology

**Module:** Economic and fiscal
**Indicator:** Economic viability  

### Disclosure format

> Disclose the methodology used to calculate the life-cycle cost. The methodology ought to specify whether income and externalities are included in the calculation and the common date, discount rate and period of analysis used. 

### OC4IDS mapping
> Project Level: Publish in documents, with `.documentType` set to 'lifecycleCostCalculationMethodology' and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 
</details>

<details>

<summary>Cost benefit analysis </summary>

##  Cost benefit analysis

**Module:** Economic and fiscal
**Indicator:** Economic viability  

### Disclosure format

> Disclose the project cost-benefit analysis. This information tends to be part of the appraisal documents. (E.g. [Document]).  

### OC4IDS mapping
> Project Level: Publish in `documents`, with `.documentType` set to 'costBenefitAnalysis' and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 
</details>

<details>

<summary>Value for money </summary>

##  Value for money

**Module:** Economic and fiscal
**Indicator:** Economic viability  

### Disclosure format

> A summary of the value for money analysis carried out for the project, along with supporting figures, calculations and business case, based on projected or actual procurement outcomes. This tends to include considerations of economy, efficiency, effectiveness and equity, and is part of the appraisal documents. (E.g. [Document]). 

### OC4IDS mapping
> Project Level: Publish in `documents`, with `.documentType` set to 'valueForMoneyAnalysis` and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 
</details>

<details>

<summary>Environmental exemptions </summary>

##  Environmental exemptions

**Module:** Environmental and climate
**Indicator:** Environmental impact

### Disclosure format

> Disclose all exemptions and/or amnesties obtained for the project. (E.g. [Document]). This can be planning, environmental, construction and/or operational related. 

### OC4IDS mapping
> Project Level: Publish in `documents`, with `.documentType` set to 'environmentalExemption` and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 
</details>

<details>

<summary> Climate and disaster risk assessment</summary>

##  Climate and disaster risk assessment

**Module:** Environmental and climate
**Indicator:** Climate and disaster risk

### Disclosure format

> Clarify the type of climate and disaster risks to which the project is exposed to (E.g. [document or free text to list and explain risks]). This tends to be part of the appraisal documents

### OC4IDS mapping
> Project Level: Publish in `documents`, with `.documentType` set to 'climateAndDisasterRiskAssessment’ and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 
</details>

<details>

<summary> Forecast of Greenhouse Gas Emissions </summary>

##  Forecast of Greenhouse Gas Emissions

**Module:** Environmental and climate
**Indicator:** Climate risk

### Disclosure format

> Disclose ​the forecast ​greenhouse gas emissions related to the project, informing the calculation, the methodology applied and where the calculation can be found (E.g. [amount] and [free text for methodology clarification]). ​Click here to enter text.​ 

### OC4IDS mapping
> Project-level: 1. Add a `Metric` object to the `.forecasts` array. 2. Set the metric’s `.title` to “Greenhouse gas emissions (carbon dioxide equivalent)” and map the methodology clarification to its `.description`. 3. Add an `Observation` object to the metric’s `.observations` array and: -  Map the amount of greenhouse gas emissions in tonnes of CO2 equivalent to the observation’s `.measure` -  Set the `.unit.name` to “Tonne (metric ton)”, `.unit.scheme` to ‘UNCEFACT’ and `.unit.id` to “TNE” - Set `.period` to the period covered by the forecast. 4. If supporting documentation is available, publish in documents, with `.documentType` set to 'GhgEmissionForecast’ and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 
</details>

<details>

<summary> Environmental certifications </summary>

##  Environmental certifications

**Module:** Environmental and climate
**Indicator:** Climate management

### Disclosure format

> Disclose environmental and/or climate related certifications issued for contractors and subcontractors such as ISO 14001 for environmental management (E.g. [Document]).  

### OC4IDS mapping
> Contracting process level: Publish in `documents`, with `.documentType` set to 'contractorEnvironmentalCertification’ and include a short description and/or a link to a document providing details. 
</details>

<details>

<summary> Decommissioning plans </summary>

##  Decommissioning plans

**Module:** Environmental and climate
**Indicator:** Climate management

### Disclosure format

> Disclose the decommissioning plans for the project assets [document]

### OC4IDS mapping
> Project level: Publish in `documents`, with `.documentType` set to 'decommissioningPlans’ and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 
</details>

<details>

<summary> Inclusive design and implementation </summary>

##  Inclusive design and implementation

**Module:** Social
**Indicator:** Gender and inclusion

### Disclosure format

> Clarify whether gender, people with disabilities and vulnerable and disadvantaged populations were considered in the project design (e.g. “free text to explain how the design meets inclusion goals” and document to support – the project design) and project implementation (e.g. “free text to explain implementation practices targeting inclusion goals” and document to support – contractor policy and procedures). 

### OC4IDS mapping
> Project-level: 1. Add a document, set its `.documentType` to ‘inclusiveDesign’ and add an explanation of how the project design meets inclusion goals to its `.description`. If supporting documentation is available, add its URL to `.url`. 2. Add a document, set its `.documentType` to ‘inclusiveImplementation’ and add an explanation of how the project  implementation practices target inclusion goals to its `.description`. If supporting documentation is available, add its URL to `.url`.  
</details>

<details>

<summary> Health and safety certifications </summary>

##  Health and safety certifications

**Module:** Social
**Indicator:** Health and safety

### Disclosure format

> Disclose labour related certifications issued in relation to project contractors and subcontractors such as ISO 45001 for Health and Safety (E.g. [Document]). 

### OC4IDS mapping
> Contracting process level: Publish in `.summary.documents`, with `.documentType` set to 'contractorHealthAndSafetyCertification’ and include a short description and/or a link to a document providing details. 
</details>

<details>
<summary> Building inspections </summary>
##  Building inspections

**Module:** Social
**Indicator:** Health and safety

### Disclosure format

> Disclose building inspections during project implementation (E.g. [Document]). 

### OC4IDS mapping
> Project Level: Publish in `documents`, with `.documentType` set to 'buildingInspectionReport’ and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 
</details>

<details>
<summary> Freedom of information requests </summary>
##  Freedom of information requests

**Module:** Institutional
**Indicator:** Access to information

### Disclosure format

> Disclose​ Freedom of​ Information ​(FoI) ​requests that have been presented in relation to the project [E.g. Document].​ Note that FoI requests can also be known as access to information requests.​ 

### OC4IDS mapping
>Project level:  For each freedom of information request, add a document, set `.documentType` to ‘foiRequest’ and set `.url` to the URL at which the request is available. 
</details>

<details>
<summary> Answers to freedom of information requests </summary>
##  Answers to freedom of information requests

**Module:** Institutional
**Indicator:** Access to information

### Disclosure format

> Disclose the responses provided by authorities to​Freedom of I​nformation​ (FoI)​ request​s​ related to the project (Eg. [Document]).​ Note that FoI requests may also be known as acccess to information requests. ​ 

### OC4IDS mapping
>Project level:  For each freedom of information request, add a document, set `.documentType` to ‘foiRequestResponse’ and set `.url` to the URL at which the request is available.
</details>

<details>
<summary> Anti-corruption certification </summary>
##  Anti-corruption certifications

**Module:** Institutional
**Indicator:** Anti-corruption impact

### Disclosure format

> Disclose anti-corruption certifications of the project, such as ISO 37001 on Anti-Bribery Management Systems Standard (E.g. [Document]).  

### OC4IDS mapping
>Project Level: Publish in documents, with .documentType set to 'antiCorruptionCertification’ and include a short description and/or a link to a document providing details. 
</details>

<details>
<summary> Climate transformation </summary>

##  Climate transformation

**Module:** Climate finance
**Indicator:** Model of change

### Disclosure format

> Clarify the theory of change, systemic transition or transformation that is intended [free text to explain].  

### OC4IDS mapping
> Project level: Publish in documents, with `.documentType` set to ‘climateTransformation' and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 
</details>

<details>
<summary>Oversight reports (implementation) </summary>

##  Oversight reports (implementation)

**Module:** Climate finance
**Indicator:** Anti-corruption impact

### Disclosure format

> [document] 

### OC4IDS mapping

> Project level: Publish in documents, with `.documentType` set to ‘oversightReport' and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 

@EvelynDinora provided some further clarification on the meaning of oversight in this context, sourced from [Oversight and Evaluation in the UN System - United Nations Evaluation Group](https://www.unevaluation.org/document/detail/88):

> oversight refers to a key activity of the governance and management of an organization, which ensures that an organization and its component units perform in compliance with legislative mandates and policy, with full accountability for its finances, as well as for the efficiency, effectiveness and impact of its work, with adherence to standards of professionalism, integrity and ethics, while adequately managing and minimizing risk. This is applicable to a PE or the project owner or the contracting authority. 

</details>

<details>
<summary>Impact measurement (Operation)</summary>

##  Impact measurement (Operation)

**Module:** Climate finance
**Indicator:** Long-term project impact

### Disclosure format

> Clarify the methodology or system to measure the long-term impact of the project solution (E.g. [free text].  

### OC4IDS mapping

> Project level: Publish in documents, with `.documentType` set to ‘impactMethodology' and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 

</details>

<details>
<summary>Carbon footprint (Operation)</summary>

##  Carbon footprint (Operation)

**Module:** Climate finance
**Indicator:** Long-term project impact

### Disclosure format

> Disclose the carbon footprint of the project [value, tons CO2 equivalent, free text to describe the methodology used to measure the carbon footprint]

### OC4IDS mapping

> Project-level:   
> 
> 1. Add a `Metric` object to the `.metrics` array.  
> 2. Set the metric’s `.title` to “Greenhouse gas emissions (carbon dioxide equivalent) - operation” and map the methodology clarification to its `.description`.  
> 3. Add an `Observation` object to the metric’s `.observations` array and:  
> -  Map the amount of greenhouse gas emissions in tonnes of CO2 equivalent to the observation’s `.measure`  
> -  Set the `.unit.name` to “Tonne (metric ton)”, `.unit.scheme` to ‘UNCEFACT’ and `.unit.id` to “TNE”  
> - Set `.period` to the period covered by the calculation.  
> 4. If supporting documentation is available, publish in documents, with `.documentType` set to 'ghgEmissions’ and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 

</details>

<details>
<summary>Carbon decommission savings (Decommission)</summary>

##  Carbon decommission savings (Decommission)

**Module:** Climate finance
**Indicator:** Climate management

### Disclosure format

> Disclose the evaluation of CO2 savings as a result of decommissioning [value, tons CO2 equivalent] 

### OC4IDS mapping

> Project-level:   
> 
> 1. Add a `Metric` object to the `.forecast` array.  
> 2. Set the metric’s `.title` to “Greenhouse gas emissions reduction (carbon dioxide equivalent)” and map the methodology clarification to its `.description`.  
> 3. Add an `Observation` object to the metric’s `.observations` array and:  
> -  Map the amount of greenhouse gas emissions in tonnes of CO2 equivalent to the observation’s `.measure`  
> -  Set the `.unit.name` to “Tonne (metric ton)”, `.unit.scheme` to ‘UNCEFACT’ and `.unit.id` to “TNE”  
> - Set `.period` to the period covered by the calculation.  
> 4. If supporting documentation is available, publish in documents, with `.documentType` set to 'ghgEmissionsReduction’ and include a short description and/or a link to a document providing details. If the details are part of a more general document indicate the relevant section of the document using `.pageStart` and `.pageEnd`. 

</details>

# Proposal

To accommodate the above fields we’ll add the following new codes to documentType.

Add the following codes:

Codelist | Code | Title | Description
-- | -- | -- | --
documentType | procurementStrategyRiskAssessment | Procurement strategy risk assessment | Documentation of the strategic risk assessment carried out for this contracting process addressing in-house capabilities, contract packaging decisions and risk allocation decisions.
documentType | lifeCycleCostMethodology | Life cycle cost methodology | Documentation of the methodology for calculating the life cycle cost of the assets.
documentType | costBenefitAnalysis | Cost-benefit analysis | Documentation of the economic cost-benefit analysis carried out for the project.
documentType | valueForMoneyAnalysis | Value for money analysis | Documentation of the value for money analysis carried out for the project, including considerations of economy, efficiency, effectiveness and equity.
documentType | environmentalExemption | Environmental exemption | Documentation of any environmental exemptions or amnesties granted to the project by a relevant authority.
documentType | climateAndDisasterRiskAssessment | Climate and disaster risk assessment | Documentation of assessments of the project and resulting assets risk in relation to climate change and natural disasters.
documentType | climateTransformation | Climate transformation | Documentation of the theory of change, systemic transition or transformation in relation to the climate that is intended as an outcome of the project.
documentType | decommissioningPlans | Decommissioning plans | Documentation of planning for decommissioning of the assets at the end of their lifetime.
documentType | impactMethodology | Impact methodology | Documentation of the methodology for measuring the long-term impact of the project.
documentType | inclusiveDesign | Inclusive design | Documentation of how issues relating to gender, people with disabilities and vulnerable and disadvantaged populations were incorporated into the project's design.
documentType | inclusiveImplementation | Inclusive implementation | Documentation of how issues relating to gender, people with disabilities and vulnerable and disadvantaged populations were incorporated into the project's implementation.
documenttype | supplierEnvironmentalCertification | Supplier environmental certification | A certificate issued by a relevant authority confirming the supplier conforms to relevant environmental policies.
documentType | supplierHealthAndSafetyCertification | Supplier health and safety certification | A certificate issued by a relevant authority confirming the supplier conforms to relevant health and safety policies.
documentType | antiCorruptionCertification | Anti-corruption certification | A certificate issued by a relevant authority confirming the named party conforms to an anti-corruption standard, such as the ISO 37001 on Anti-Bribery Management Systems Standard.
documentType | oversightReport | Oversight report | Documentation of checks that the governance and management of the project owner or procuring entity comply with all relevant legislative mandates and policies.
documentType | informationRequest | Freedom of information request | A request for information in relation to the project submitted under relevant freedom of information legislation.
documentType | informationRequestResponse | Freedom of information request response | The formal response in answer to a request for information in relation to the project submitted under relevant freedom of information legislation.
documentType | buildingInspectionReport | Building inspection report | Documentation of checks that the assets meet [building code](https://en.wikipedia.org/wiki/Building_code) requirements.
documentType | ghgEmissionsForecast | Greenhouse gas emissions forecast | Documentation of the forecast greenhouse gases that the project will emit, including the methodology and calculation method used.
documentType | ghgEmissionsReduction | Greenhouse gas emissions reduction forecast | Documentation of the forecast reduction in greenhouse gas emissions resulting from the project, including the methodology and calculation method used.
documentType | ghgEmissions | Greenhouse gas emissions | Documentation of the actual greenhouse gases that the project emitted, including the methodology and calculation method used.

# Example

```json

{ 
 "documents": [ 
   { 
 	"id": "1", 
 	"documentType": "antiCorruptionCertification", 
 	"url": "http://example.com/ISO37001Certification.pdf" 
   } 
 ] 
} 
```

# Sources

* [Title (page number)](URL)

## Discussion
`buildingInspectionReport` - is this necessary or is this covered by `technicalAuditReport` which is defined as “Documentation of checks that construction work has been undertaken as specified.” @evelyndinora

cc @evelyndinora @mgraca-prado

**Comment by jpmckinney** [comment]
* GhgEmissionsForecast -> ghgEmissionsForecast
* contractorHealthAndSategyCerfication -> contractorHealthAndSafetyCertification
* foi... -> information...

**Comment by EvelynDinora** [comment]
@odscjen the building inspection report is specific for buildings not for all type of infrastructure projects

**Comment by odscjen** [comment]
@EvelynDinora would this be a better description then:

Documentation of checks that the building has been constructed as specified.

**Comment by odscjen** [comment]
Or

Documentation of checks that building work has been undertaken as specified. This type of check is specific to infrastructure projects that result in the construction of a building.

**Comment by duncandewhurst** [comment]
I've updated the background and proposal to add the new document types proposed in the climate finance module ('climateTransformation', 'oversightReport', 'impactMethodology', 'ghgEmissions', 'ghgEmissionsReduction').

I also updated the description of 'ghgEmissionsForecast' to remove the reference to the implementation stage, since my understanding is that emissions during the operation stage are also important:

> Documentation detailing the forecast greenhouse gases that the project will emit ~~during implementation~~, including the methodology and calculation method used.

**Comment by odscjen** [comment]
All codes now have draft descriptions. @EvelynDinora @mgraca-prado can you confirm if these descriptions are adequate? I've not updated the `buildingInspection` code as still waiting feedback on earlier suggestion https://github.com/open-contracting/infrastructure/issues/411#issuecomment-1785731908 or https://github.com/open-contracting/infrastructure/issues/411#issuecomment-1785734007

**Comment by EvelynDinora** [comment]
@odscjen Yes, I confirm they are adequate including the proposal for builidng inspections (just adding a detail): Documentation of checks that building work  meets [building code](https://en.wikipedia.org/wiki/Building_code) requirements and has been undertaken as specified. This type of check is specific to infrastructure projects that result in the construction of a building.

**Comment by odscjen** [comment]
Great, thanks @EvelynDinora I've updated the table with your buildingInspectionReport description.

@jpmckinney are you happy for me to move this to Agreed on the project board now or do you have any objections or updates you'd like to see to the definitions?

**Comment by odscjen** [comment]
@jpmckinney a gentle prod to see if you've any further comments or objections to the code descriptions (I don't think they'd been added when you last commented on this issue)

**Comment by jpmckinney** [comment]
Thank you for the prod, I missed this notification.

Larger edits:

> Documentation of checks that building work meets [building code](https://en.wikipedia.org/wiki/Building_code) requirements and has been undertaken as specified. This type of check is specific to infrastructure projects that result in the construction of a building.

> Documentation of checks that building assets meet building codes. [no hyperlink]

The last sentence is unnecessary, as projects without building assets are obviously irrelevant to this code. The second clause of the first sentence is unnecessary, as an asset needs to be built to be inspected (i.e. work must have been undertaken by the time of the inspection).

"The formal response issued by the project" -> "the project" is not an agent. I would just remove "issued by the project", and maybe add "in relation to the project" like in the informationRequest code.

climateTransformation's description doesn't mention climate.

Small edits:

Codes, titles and descriptions:

- contractor -> we typically use the word "supplier"

Descriptions:

- Documentation detailing/confirming/covering -> Documentation of
- double spaces -> single space (occurs between at least "relevant  health")
- inhouse -> in-house
- project asset -> asset (we typically don't prefix this term)
- asset -> assets (it's usually plural in our documentation)
- cost benefit analysis -> cost-benefit analysis (hyphenate title as well)
- exemptions of amnesties -> should this be "or"?
- contracting authority -> this term is never used, so I would remove it
- conforms with -> conforms to (agents conform to, things conform with)
- project solution -> project (twice)
- methodology to be used to measure -> methodology for measuring
- emitted by the project -> that the project emitted (to align with construction in ghgEmissionsForecast)

Codes:

- Put the codes in some logical order (e.g. GHG next to each other)
- lifeCycleCostCalculationMethodology -> lifeCycleCostMethodology (same meaning, shorter code)
- contractorHealthAndSatefyCertification -> contractorHealthAndSafetyCertification (typo)

I can't find any usage of the phrase "Procurement strategy risk assessment" but I can find "Procurement strategy risk", so I guess it's okay.

**Comment by odscjen** [comment]
Great, thanks @jpmckinney. I've updated the proposal with all of your comments. There may be a couple of double spaces left but we'll pick them up in the actual PR.

moving to agreed now
