### ISSUE TITLE
Financing arrangements

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#413]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Financial instrument (preparation)  </summary>

## Financial instrument (preparation) 

**Module:** Climate finance
**Indicator:** Financial mechanism

### Disclosure format

> Disclose the financial instrument type from the list: 
> * loan 
> * concessional 
> * non-concessional 
> * grant 
> * equity 
> * guarantees 

### OC4IDS mapping

> Project level: For each instrument, add a `finance` object to the `budget.finance` array. Set the `.id` appropriately. Set the `.financeCategory` to the matching code from the financeCategory codelist. 

</details>

<details>

<summary> Amount of investment (Preparation)    </summary>

## Amount of investment (Preparation) 

**Module:** Climate finance
**Indicator:** Economic viability

### Disclosure format

> Disclose the quantum of the climate finance investment [value, currency].  

### OC4IDS mapping

> Project level: For each financing instrument, add the value and currency to the`.value` in the `finance` object in `budget.finance`  

</details>

<details>

<summary> Funding source (Preparation) </summary>

## Funding source (Preparation)

**Module:** Climate finance
**Indicator:** Economic viability

### Disclosure format

> Disclose who is providing the finance [party/organization/role]  

### OC4IDS mapping

> Project level: Add the organization to the `parties` array and add ‘funder’ to their `.roles` array. 
>
> Map the organization’s `.id` from the party array to `financingParty.id` in the `budget.finance`  

</details>

<details>

<summary> Green Climate Fund Accredited Entity (Preparation)  </summary>

## Green Climate Fund Accredited Entity (Preparation) 

**Module:** Climate finance
**Indicator:** Accessibility

### Disclosure format

> For projects financed by the Green Climate Fund, disclose the accredited entities through which GCF resources are accessed.

### OC4IDS mapping

> Project level: Add each accredited entity organization to the `parties` array and add ‘gcfAccreditedEntity’ to its `.roles` array.   

</details>

<details>

<summary> Ratio of co-finance (Preparation) </summary>

## Ratio of co-finance (Preparation)

**Module:** Climate finance
**Indicator:** Economic viability

### Disclosure format

> Disclose the ratio of co-finance. Select from a list to specify amounts.   
> 
> Eg:   
> 
> Domestic mobilisations [value or NA]  
> Private Finance [value or NA] 

### OC4IDS mapping

> Project level: For each co-financing arrangement add a new `finance` object to the `budget.finance` array. Map the value and currency to the objects `.value`. Add the financing party to the parties array and add `funder` to their `roles` array. Map the funders `id` and `name` to the `.financingParty` object in the `finance` object. 

</details>

<details>

<summary> Terms of climate finance (Preparation)</summary>

## Terms of climate finance (Preparation)

**Module:** Climate finance
**Indicator:** Economic viability

### Disclosure format

> This includes several financial terms:
> * Maturity (years)
> * Grace period (years)
> * annual principal repayment years (% of initial principle)
> * Interest (%)
> * Service fee (per annum)
> * Commitment fee (per annum)

### OC4IDS mapping

TBC

</details>

# Proposal

I'm creating this issue as a place to link the issues I've been opening to do with updating the OCDS finance extension so that we can reuse it to model a project's financing arrangements:

* https://github.com/open-contracting/ocds-extensions/issues/207
* https://github.com/open-contracting/ocds-extensions/issues/206
* https://github.com/open-contracting/ocds-extensions/issues/209
* https://github.com/open-contracting/ocds-extensions/issues/210

Once those issues are resolved, I'll update this issue with a full proposal and updated OC4IDS mappings.

**Comment by duncandewhurst** [comment]
A related issue:

* #420

**Comment by duncandewhurst** [comment]
Looking at the different procurement strategies set out in the diagram on page 124 of the [approved funding proposal](https://www.greenclimate.fund/sites/default/files/document/fp209-dbsa.pdf) for South Africa's Water Reuse Programme (WRP), I think that we'll need to add a finance array in two places:

* `budget.finance` to model financing arrangements for traditionally procured projects
* `contractingProcesses.summary.finance` to model financing arrangements for PPP contracts

![procurement strategies](https://github.com/open-contracting/infrastructure/assets/19265814/499458d4-7ba6-42f1-8e08-e4f220024366)

**Comment by duncandewhurst** [comment]
Noting that I don't yet understand how the 'public sector operators' and 'municipal entity (SPV)' options map to OC4IDS.

**Comment by duncandewhurst** [comment]
> Noting that I don't yet understand how the 'public sector operators' and 'municipal entity (SPV)' options map to OC4IDS - I'll open a separate issue on that.

* **Public Sector Operators:** From discussion with @EvelynDinora, this option is out of scope for OC4IDS as it relates only to the operation of the infrastructure asset.

* **Municipal entity (SPV)**: My understanding is that this option relates to the creation of an SPV that is wholly owned by the public sector, i.e. using a project financing approach without equity investment from the private sector and without a contracting process to appoint a private partner and establish a PPP SPV. I couldn't find much information about this option online, but it turns out that it is used in New Zealand. For example, the [Wellington Sludge Minimisation Facility](https://www.crowninfrastructure.govt.nz/infrastructure-financing/projects/#sludge-minimisation) is financed through an SPV that is wholly owned by Crown Infrastructure Partners (a publicly-owned company). Therefore, were a project like this to be published in OC4IDS, I think that the SPV's financing arrangements would map to `budget.finance`.

Updated diagram to reflect the above understanding:

![procurement strategies](https://github.com/open-contracting/infrastructure/assets/19265814/07ddf246-25b8-44a8-83d9-813b53f85b9f)

**Comment by duncandewhurst** [comment]
# Background

I've updated the proposal and OC4IDS mappings to reflect the agreement reached in the related issues linked in the issue description. I've also moved the discussion about the accredited entity type CoST IDS element to a separate [issue](https://github.com/open-contracting/infrastructure/issues/436) since the modelling for that is distinct from the proposal in this issue. 

@jpmckinney, please let me know if you're happy for me to prepare a PR.

@evelyndinora, based on our most recent call and on your feedback in the related issues, I think that you're happy with this proposal, but do let me know if not. cc @mgraca-prado

<details>

<summary> Financial instrument</summary>

## Financial instrument

**Module:** Climate finance
**Indicator:** Financial mechanism

### Disclosure format

> Disclose the financial instrument type from the list: 
> * loan 
> * concessional 
> * non-concessional 
> * grant 
> * equity 
> * guarantees 

### OC4IDS mapping

> 1. Get the `Finance` object in `.budget.finance` or `.contractingProcesses.summary.finance` that represent's the financing arrangement. If none exists yet, [add a financing arrangement](../common/md#add-a-financing-arrangement).
> 2. Set the the financing arrangement's properties according to the instrument type:
> Instrument type | `.assetClass` | `.type`
> -- | -- | --
> loan | 'debt' | 'loan'
> grant | | 'grant'
> equity | 'equity' | 'shares.listed' or 'shares.unlisted'
> guarantee | | 'guarantee'
> 3. If the instrument is a concessional loan, set `.concessional` to `true`.
> 4. If the instrument is a non-concessional loan, set `.concessional` to `false`. 
> 5. If the instrument is results-based, set `.resultsBased` to `true`.

</details>

<details>

<summary> Amount of investment</summary>

## Amount of investment 

**Module:** Climate finance
**Indicator:** Economic viability

### Disclosure format

> Disclose the quantum of the climate finance investment [value, currency].  

### OC4IDS mapping

> 1. Get the `Finance` object in `.budget.finance` or `.contractingProcesses.summary.finance` that represent's the financing arrangement. If none exists yet, [add a financing arrangement](../common/md#add-a-financing-arrangement).
> 2. Map to the financing arrangement's `.value`.

</details>

<details>

<summary> Funding source </summary>

## Funding source

**Module:** Climate finance
**Indicator:** Economic viability

### Disclosure format

> Disclose who is providing the finance [party/organization/role]  

### OC4IDS mapping

> 1. Get the `Finance` object in `.budget.finance` or `.contractingProcesses.summary.finance` that represent's the financing arrangement. If none exists yet, [add a financing arrangement](../common/md#add-a-financing-arrangement).
> 2. Map to the financing arrangement's `.source`.

</details>

<details>

<summary> Green Climate Fund Accredited Entity</summary>

## Green Climate Fund Accredited Entity

**Module:** Climate finance
**Indicator:** Accessibility

### Disclosure format

> For projects financed by the Green Climate Fund, disclose the accredited entities through which GCF resources are accessed.

### OC4IDS mapping

> 1. Get the `Finance` object in `.budget.finance` or `.contractingProcesses.summary.finance` that represent's the financing arrangement. If none exists yet, [add a financing arrangement](../common/md#add-a-financing-arrangement).
> 2. Get the `Organization` object in `.parties` that represents the party providing the finance. If none exists yet, [add an organization](../common.md#add-an-organization) and add 'funder' to its `.roles`.
> 3. Set the financing arrangement's `.financingParty` to the `.id` and `.name` of the organization.

</details>

<details>

<summary> Ratio of co-finance</summary>

## Ratio of co-finance

**Module:** Climate finance
**Indicator:** Economic viability

### Disclosure formathttps://extensions.open-contracting.org/en/extensions/organizationClassification/1.1/

> Disclose the ratio of co-finance. Select from a list to specify amounts.   
> 
> Eg:   
> 
> Domestic mobilisations [value or NA]  
> Private Finance [value or NA] 

### OC4IDS mapping

> The OC4IDS data model provides the information needed to calculate co-finance ratios by modelling a project's individual financing arrangements. For more information, see the mappings for [amount of investment](), [funding source](), [Green Climate Fund Accredited Entity]() and [Accredited Entity Type]().

</details>

<details>

<summary> Terms of climate finance</summary>

## Terms of climate finance

**Module:** Climate finance
**Indicator:** Economic viability

### Disclosure format

> This includes several financial terms:
> * Maturity (years)
> * Grace period (years)
> * annual principal repayment years (% of initial principle)
> * Interest (%)
> * Service fee (per annum)
> * Commitment fee (per annum)

### OC4IDS mapping

> 1. Get the `Finance` object in `.budget.finance` or `.contractingProcesses.summary.finance` that represent's the financing arrangement. If none exists yet, [add a financing arrangement](../common/md#add-a-financing-arrangement).
> 2. Map the terms to the financing arrangement's properties:
>  * Maturity: `.period`
>  * Grace period: Map the period over which payments will be made to `.paymentPeriod`. The grace period is the difference between `.period` and `.paymentPeriod`.
>  * Annual principal repayment years: `.description`
>  * Interest: `.interestRate`
>  * Service fee: `.description`
>  * Commitment fee: `.description`

</details>

# Proposal

Add the following fields and objects:

Path | Title | Description | Type (format) | Notes
-- | -- | -- | -- | --
`budget.finance` | Finance | Information about financing arrangements for this project. | Array of `Finance` objects. |
`ContractingProcessSummary.finance` | Finance | Information about financing arrangements for this contracting process. | Array of `Finance` objects
`Finance` | Financing arrangement | An arrangement between two parties for raising money. | Object | See the [OCDS finance extension](https://github.com/open-contracting-extensions/ocds_finance_extension/) for details.

Add the following codelists from the OCDS finance extension:

* [`assetClass.csv`](https://github.com/open-contracting-extensions/ocds_finance_extension/blob/master/codelists/assetClass.csv)
* [`debtRepaymentPriority.csv`](https://github.com/open-contracting-extensions/ocds_finance_extension/blob/master/codelists/debtRepaymentPriority.csv)
* [`financingArrangementType.csv`](https://github.com/open-contracting-extensions/ocds_finance_extension/blob/master/codelists/financingArrangementType.csv)
* [`financingPartyType.csv`](https://github.com/open-contracting-extensions/ocds_finance_extension/blob/master/codelists/financingPartyType.csv)

# Example

The following example is based on the low concessionality [GCF loan terms](https://www.greenclimate.fund/sites/default/files/document/financial-terms-conditions-grants-loans.pdf):

```json
{
  "budget": {
    "finance": [
      {
        "id": "1",
        "assetClass": "debt",
        "type": "loan",
        "concessional": true,
        "value": {
          "amount": 50000000,
          "currency": "USD"
        },
        "source": "Green Climate Fund",
        "financingParty": {
          "id": "1",
          "name": "Development Bank of South Africa"
        },
        "period": {
          "startDate": "2024-01-01T00:00:00Z",
          "endDate": "2043-12-31T00:00:00Z"
        },
        "paymentPeriod": {
          "startDate": "2029-01-01T00:00:00Z",
          "endDate": "2043-12-31T00:00:00Z"
        },
        "interestRate": {
          "margin": 0.0075
        },
        "description": "Annual principal repayment years 11–20 (% of initial principal): 6.7%. Service fee (per annum): 0.50%. Commitment fee (per annum): Up to 0.75%."
      }
    ]
  },
  "parties": [
    {
      "id": "1",
      "name": "Development Bank of South Africa",
      "roles": "funder"
    }
  ]
}
```

# Sources

* See related issues.

**Comment by jpmckinney** [comment]
Yes, sounds good. Maybe do https://github.com/open-contracting/ocds-extensions/issues/211 first (quick).
