### ISSUE TITLE
Carbon efficiency (abatement cost)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#416]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Carbon efficiency (Preparation) </summary>

## Data point title

**Module:** Climate finance
**Indicator:** Climate impact

### Disclosure format

> Disclose the cost per tonne of CO2 equivalent [value, currency].

### OC4IDS mapping

> Publish the cost in `environment.abatementCost`. If supporting documentation is available, publish in documents with `.documentType` set to 'abatementCostMethodology'.

</details>

# Proposal

Add the following fields to the `environment` object proposed in #393:

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
environment.abatementCost | Abatement cost | The lifetime abatement cost of the project, measured in cost per tonne of CO2 equivalent emissions. That is, the additional cost of reducing greenhouse gas emissions by one tonne compared to the most likely alternative scenario. | `Value` object |  

Add the following codes:

Codelist | Code | Title | Description
-- | -- | -- | --
documentType | abatementCostMethodology | Abatement cost methodology | The methodology used to calculate the project’s abatement cost.

# Example

```json
{
  "environment": {
    "abatementCost": {
      "amount": 12.29,
      "currency": "NZD"
    }
  },
  "documents": [
    {
      "id": "1",
      "documentType": "abatementCostMethodology",
      "url": "http://example.com/abatementCostMethodology.pdf"
    }
  ]
}
```

# Sources

* [What You Need to Know About Abatement Costs and Decarbonization - World Bank Climate Explainer Series](https://www.worldbank.org/en/news/feature/2023/04/20/what-you-need-to-know-about-abatement-costs-and-decarbonisation): Field name, title and description
* [Abatement cost methodology for assessing co-funding applications - Energy Efficiency and Conservation Authority, New Zealand](https://www.eeca.govt.nz/assets/EECA-Resources/Co-funding/GIDI-Files/GIDI-levelised-abatement-cost-methodology.pdf): Field description - concepts of additionality and lifetime abatement costs (page 5), example of abatement cost methodology (pages 18-22)
* [Green Infrastructure Finance: Framework Report - The World Bank](https://openknowledge.worldbank.org/server/api/core/bitstreams/a1cb7ad9-64c9-59c6-87b1-21df4e1a1974/content): Field description - concept of lifetime abatement cost (page 18)

cc @evelyndinora @mgraca-prado

**Comment by duncandewhurst** [comment]
@evelyndinora, @mgraca-prado, @jpmckinney are you happy with this proposal?

**Comment by jpmckinney** [comment]
Looks fine. I don't have the entire OC4IDS + modules in my head, so I'm wondering how this interacts with other cost fields. In how many places would a user have to look to find the various costs? Is there any existing place to put this cost, or is this the best place?

**Comment by duncandewhurst** [comment]
The other cost-related and budget-related sustainability elements are mapped to:

* `costMeasurements`:
  * Life cycle cost
  * Decommissioning cost forecast
* `budget`:
  * Funding source for preparation, implementation and operation
  * Budget for preparation, implementation and operation
  * Budget projections per year
* `social.landCompensationBudget`:
  * Land compensation budget
* `contractingProcesses.summary.social.laborBudget`:
  * Labor budget
* `budget.finance`:
  * Financial instrument
  * Amount of investment
  * Funding source
  * Green Climate Fund Accredited Entity
  * Accredited Entity Type
  * Ratio of co-finance
  * Terms of climate finance
 
Since the abatement cost is specifically about the costs of reducing carbon emissions, I figured it fit best under `environment`. It could instead be mapped to `costMeasurements.abatementCost` as it fits the broad semantics of "a measurement of costs for a project", but it is more of a cost 'rate' than an absolute cost like `costMeasurements.costGroups` or `costMeasurements.lifeCycleCosting`. It's perhaps worth noting that ICMS (on which `costMeasurements` is based) deals in the measurement of costs and of carbon emissions, but not of abatement/emissions reduction.

Let me know what you think.

**Comment by jpmckinney** [comment]
What I'm wondering is whether there will be many more things like `social.laborBudget` and `environment.abatementCost`. (I guess there's also `landCompensationBudget`).

So far, fields have been grouped based on logic (e.g. things about contracting processes go under `contractingProcesses`) or timeline (e.g. things about the solicitation stage go under `tender`, similarly with `completion`). In general, these do not conflict, since the timeline method mainly adds a new object, and then the logic method fills it in.

With the sustainability modules, we have introduced a new organizational method: theme. However, this can conflict with the other methods. I think for most of the new fields like in #393, there's not really any other way to organize them (other than moving up a level, which is worse). But, for things like budgets/costs, I'm not sure if they are better under the theme or closer to the other budget/cost fields.

Edit2: Since the sustainability modules are optional, an advantage of putting new fields together with existing structures is that it makes them more easily discoverable.

Edit: Another example is consultation meetings. OC4IDS has no other event or milestone fields, so they are fine where they are. However, if we had more such fields, it could make sense to group events together (perhaps by stage, if OC4IDS had more demand for stage objects, discussed earlier in #252).

**Comment by duncandewhurst** [comment]
Ah, yes. I missed `social.landCompensationBudget`. There are also fields related to financing arrangements (see https://github.com/open-contracting/infrastructure/issues/413), which are mapped to `budget.finance`, i.e. already close to other budget fields. I've added those to the list in my previous comment.

I think that's all the new fields. I don't know whether to expect any more in the future. Regarding moving the known new fields closer to existing fields, I figure everything that is already mapped to `budget` or `costMeasurements` is fine, which leaves:

* `social.landCompensationBudget`: We could move this to something like `budget.landCompensation` to have it closer to existing budget fields, but then it would be further from `social.indigenousLand`, to which it is closely related. If we did move it, we should probably also move `social.indigenousLand` to `locations.indigenousLand` to keep it closer to existing location fields.
* `contractingProcesses.summary.social.laborBudget`: This field is about the budget allocated by the supplier. There aren't any other fields about a supplier's budget so I'm not sure where it could move. Also worth noting is that `.laborObligations` is a sibling field under `contractingProcesses.summary.social`.

**Comment by jpmckinney** [comment]
Ok, I think those two budget fields make more sense where they are already proposed to go. We can continue to keep an eye on how we organize fields, to avoid any conflicting organizational principles.

**Comment by duncandewhurst** [comment]
Sounds good. What is your preference for `abatementCost`?

**Comment by jpmckinney** [comment]
Is there a similar reason to keep it in `environment`? If not, maybe move to `costMeasurements`.

**Comment by duncandewhurst** [comment]
Only that it is specifically about the cost of reducing carbon emissions, in which sense it fits with other fields related to the environmental and climate impact of a project.

**Comment by jpmckinney** [comment]
Hmm, I don't have strong feelings either way. We can leave it with the theme, since we don't currently have examples of environmental fields living outside that container.

**Comment by duncandewhurst** [comment]
@evelyndinora, @mgraca-prado - to summarise the above discussion: we agreed on the proposal in the issue description.

**Comment by EvelynDinora** [comment]
@duncandewhurst fine with me. Thanks
