### ISSUE TITLE
Project monitoring (oversight functions)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#417]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Type of project monitoring </summary>

## Type of project monitoring

**Module:** Climate finance
**Indicator:** KPIs

### Disclosure format

> Select from a list: 
>
> * internal
> * external
> * mixed

### OC4IDS mapping

> Map to `environment.climateOversightFunctions`.

</details>

@evelyndinora explained the use case for this element and provided some further detail on the meaning of the proposed codes:

> The SG wants to see an optimal positive impact on climate metrics, but this should be credible.
> This is not exactly monitoring but I think it could be applicable. The primary difference between the internal and the external oversight functions is the degree of independence with which they are able to carry out their activities. Another difference is with regard to the reporting lines, where typically the internal oversight body reports to management, while the external oversight body reports to the governing body. However, this difference is reduced in situations where the internal oversight body has dual reporting lines, to both management and the governing body. Lastly, there are also differences in terms of the focus of oversight activities carried out internally, or externally. 
>
> Ref. https://www.unevaluation.org/document/detail/88 

# Proposal

Add the following field to the environment object proposed in #393:

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
environment.climateOversightFunctions | Climate oversight functions | The functions tasked with oversight of the project’s climate impact, from the closed oversightFunctions codelist. | Array | oversightFunctions

Add an oversightFunctions codelist with the following codes:

Codelist | Code | Title | Description
-- | -- | -- | --
oversightFunctions | internal | Internal | An oversight function that is functionally and managerially part of the project. Internal oversight functions typically report to management.
oversightFunctions | external | External | An oversight function that is functionally and managerially independent from the project. External oversight functions typically report to an external body.

# Example

A project with both internal and external climate oversight functions:

```json
{
  "environment": {
    "climateOversightFunctions": ["internal", "external"]
  }
}
```

# Sources

* [Oversight and Evaluation in the UN System - United Nations Evaluation Group](https://www.unevaluation.org/document/detail/88) - code descriptions (page 5)

## Discussion

@evelyndinora, @mgraca-prado:

* Is the scope of the proposed field correct (oversight of the project's climate impact)?
* The UN document shared by Evelyn defines internal and external oversight functions with respect to an organization. The proposed code descripitons adapt the definitions to be with respect to a project, but I'm concerned that the meaning of 'project' in that context is a bit vague, e.g. it could be interpreted to mean the government agency that is the project owner, the project company/SPV (in the case of a PPP), or the main supplier. What is it you're interested in measuring internality/externality against?

**Comment by duncandewhurst** [comment]
@evelyndinora, @mgraca-prado, it would be great to get your feedback on the discussion points above, please.

**Comment by EvelynDinora** [comment]
@duncandewhurst Yes, the scope of the proposed field is correct. Thanks

**Comment by duncandewhurst** [comment]
@EvelynDinora I'm assuming that you're happy that no further clarification is required concerning the second discussion point. Let me know if not.

@jpmckinney please let me know if you're happy with this proposal.

**Comment by jpmckinney** [comment]
I'm not sure that "The functions tasked with oversight of the project’s climate impact" describes the field.

It's more like "Whether the oversight of this project's climate impact is performed internally, externally or both."

**Comment by jpmckinney** [comment]
As such, I think the field name and codelist name can also be improved. I don't know an appropriate term whose domain would cover the terms "internal" "external" in this context (in other contexts, maybe: perspective, position, relationship). "type" and its synonyms ("nature", etc.) are sort of overused catch-all terms, but I guess `climateOversightTypes` is an improvement.

**Comment by duncandewhurst** [comment]
`climateOversightTypes` sounds good to me. How about the following?

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
environment.climateOversightTypes | Climate oversight types | Whether the oversight of this project's climate impact is performed internally, externally or both, from the closed climateOversightTypes codelist. | Array | climateOversightTypes

Codelist | Code | Title | Description
-- | -- | -- | --
climateOversightTypes | internal | Internal | Oversight that is functionally and managerially part of the project. Internal oversight functions typically report to management.
climateOversightTypes | external | External | Oversight that is functionally and managerially independent from the project. External oversight functions typically report to an external body.

**Comment by jpmckinney** [comment]
LGTM
