### ISSUE TITLE
projectType codelist: Add decommissioning

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#418]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Infrastructure assets to be decommissioned </summary>

## Infrastructure assets to be decommissioned 

**Module:** Climate finance
**Indicator:** Stranded assets

### Disclosure format

> Identify the asset for disposal purpose [free text] 

### OC4IDS mapping

> For each set of decommissioned assets in a specified location, create a new OC4IDS project and:
> * Set `.type` to 'decommissioning'
> * Set `.title` to the name of the asset
> * Add a `RelatedProject` object to the `.relatedProjects` array and set its:
>   * `.id` and `.title` to the `.id` and `.title` of the OC4IDS project for the replacement of the asset
>   * `.scheme` to 'oc4ids'
>   * `.relationship` to 'replacement'

</details>

# Proposal

Add the following codes:

Codelist | Code | Title | Description
-- | -- | -- | --
projectType | decommissioning | Decommissioning | The primary focus of this project is the decommissioning of an existing asset.

# Example

```json
{
 "id": "oc4ids-bu3kcz-123456789", 
 "title": "Otahuhu B Power Station", 
 "type": "decommissioning",
 "relatedProjects": [ 
   { 
     "id":"oc4ids-bu3kcz-987654321",
     "scheme": "oc4ids",
     "title": "Otahuhu C Power Station"
     "relationship": "replacement"
   } 
 ] 
} 
```

cc @evelyndinora @mgraca-prado

**Comment by odscjen** [comment]
@jpmckinney any comments or objections to this proposal?

**Comment by jpmckinney** [comment]
👍

**Comment by duncandewhurst** [comment]
Moving to agreed as this change was already discussed with CoST.
