### ISSUE TITLE
Socioeconomic assessments of transition and decommissioning costs

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#419]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Decommission costs (Decommission) </summary>

## Decommission costs (Decommission)  

**Module:** Climate finance
**Indicator:** Climate management

### Disclosure format

> Disclose socio-economic assessments on transition and decommissioning costs (E.g.: [Doc]).

### OC4IDS mapping

> TBC

</details>

The original wording proposed by the consultant that carried out the research for the climate finance module was "Assessment of so-economic ‘transition costs’ of asset de-commissioning" with the following clarification:

> The underlying point was that in many climate finance projects there is a transition element, which means, of course, moving from one thing to another, and that, therefore, the ‘old thing’ needs to be taken into consideration when measuring the impact of the project. It may be operationally separate, but it’s part of the climate finance investment. 

## Discussion

There is already a 'Decommissioning cost forecast' element in the environment and climate module, which is mapped to `costMeasurements` (see https://github.com/open-contracting/infrastructure/issues/287), so my understanding is that this extra element is aimed at encouraging disclosure of a broader assessment of the of the socioeconomic costs associated with asset decommissioning in the context of transitioning to a low-carbon economy.

However, I'm struggling to find an example of such an assessment for an infrastructure project or an authoritative definition of "transition costs" that is applicable to this context.

@evelyndinora @mgraca-prado:

1. Do you have an example of such an assessment that you can share?
2. Can you provide a definition?

**Comment by EvelynDinora** [comment]
@duncandewhurst I am asking Richard to provide a definition. Let me come back later to you. Many thanks

**Comment by EvelynDinora** [comment]
@duncandewhurst this is the answer:

First, Example of Assessment:
 
Here is something to look at – although it’s not so much an assessment, as a way of thinking about how to assess the transition costs:
 
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.tips.org.za/images/report_Estimating_the_cost_of_a_just_transition_in_South_Africas_coal_sector.pdf
 
Also:
 
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://pccommissionflow.imgix.net/uploads/images/PCC-analysis-and-recommenations-on-the-JET-IP-May-2023.pdf
 
Second, Definition:
 
The literature doesn’t seem to provide an obvious or precise definition of ‘transition cost’, but looks at it from a variety of angles.
 
What I had in mind the socio-economic costs of de-commissioning a fossil fuel related piece of infrastructure, and the negative impact on the lives and livelihoods of people directly and indirectly impact on by the closure, most obviously in terms of income and employment.
 
This quote from this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9418681/ is quite good:
 
A just transition partly depends on how job creation and destruction is distributed across space, time, and racial demographics during the transition ([Bridge et al., 2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9418681/#bib3); [Healy and Barry, 2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9418681/#bib18); [Mertins-Kirkwood, 2018](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9418681/#bib33)). Employment changes will first play out in communities on the frontlines of the energy transition, including communities hosting coal-fired power plants ([Carley and Konisky, 2020](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9418681/#bib6))…

**Comment by duncandewhurst** [comment]
Thanks, @EvelynDinora.

Those examples are similar to the ones I looked at, i.e. sector-level or country-level assessments, rather than anything specific to an individual infrastructure project.

I think that we could craft a description for a new 'transitionCostAssessment' document type based on Richard's definition, but given the above context, I'm unsure if such a document would ever actually exist for an individual infrastructure project. Do you still want to include this element in the sustainability modules?

**Comment by EvelynDinora** [comment]
@duncandewhurst No. Let´s exclude this element from the module. 

I have discussed with Richard and we are not convinced that this assessment is done at project level. I did a quick research and could not find one. Thanks!

**Comment by duncandewhurst** [comment]
Sounds good. I've removed it from the [sustainability elements spreadsheet](https://docs.google.com/spreadsheets/d/165epI69oQ5YyL4-2q8VubFn9VuNham2Pi1u0P49id9o/edit#gid=0) cc @mgraca-prado

To close this issue we'll need to prepare a PR to remove the element (3.32) from `sustainability.yaml`
