### ISSUE TITLE
Climate finance decision-maker

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#420]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Climate finance decision-maker (Identification) </summary>

## Climate finance decision-maker (Identification)

**Module:** Climate finance
**Indicator:** Decision-making process

### Disclosure format

> Identify who approved the climate finance investment in the country (organization, party, role) 

### OC4IDS mapping

TBC

</details>

@evelyndinora provided the following clarification:

> it is the public authority in a country (e.g. Ministry of Finance, Ministry of Environment, the Presidential Commision of Climate Change, etc.) who is charge of approving the climate finance investment. This is done before project preparation. 

## Discussion

I'm struggling to understand what this means exactly. Looking, for example, at the [Green Climate Fund project cycle](https://www.greenclimate.fund/project-cycle), the process goes like this:

1. A country's government and National Designated Authorities (NDAs) or focal points develop a country or entity work programme aimed at identifying project ideas. These are submitted to GCF for review, endorsement and information.
2. Project ideas submitted in response to GCF RFPs or through dedicated platforms and innovative partnerships, such as the Climate Investment Platform, are incorporated into country or entity work programmes.
3. An accredited entity (e.g. the Development Bank of South Africa) works with the NDA/focal point to prepare a concept note summarising a project. These are submitted to GCF for feedback.
4. The accredited entity develops a funding proposal and submits it to GCF
5. Different parts of GCF review the funding proposal in several stages before submitting it to the board for approval
6. The GCF board approves the investment

As discussed in https://github.com/open-contracting/ocds-extensions/issues/209, typically, that investment isn't in a specific infrastructure project. Rather, the accredited entity (financing party in OC4IDS terms) then makes investments in specific infrastructure projects, e.g.

```mermaid
flowchart TD
  A["Funding source,
  e.g. GCF"]-- "'Parent' investment" -->
  B["Financing party, e.g.
  Development Bank of South Africa"]-- "Investment" -->
  C["Infrastructure
    Project 1"] &  D["Infrastructure
    Project 2"] & E["Infrastructure
    Project 3"]
```

Each of the accredited entity/financing party's investments in a specific infrastructure project goes through it's own approval process, e.g. the [approved funding proposal](https://www.greenclimate.fund/sites/default/files/document/fp209-dbsa.pdf) for South Africa's Water Reuse programmes describes the approval process for sub-projects to receive funding from the DBSA:

![image](https://github.com/open-contracting/infrastructure/assets/19265814/cd05859f-4dc9-482a-b83b-b2e65bf116e2)

So my understanding is that there are two levels of climate finance investment approval: an approval from the ultimate funder (e.g. the GCF) for the 'parent' investment and an approval from the financing party for each investment in an infrastructure project.

@evelyndinora, @mgraca-prado - does the proposed data point refer to the financing party/accredited entity's approval in the above scenario? If not, please clarify where the approval that you're interested in fits into the above process and provide an example from a real project.

**Comment by EvelynDinora** [comment]
@duncandewhurst this is the NDA/focal point who approved that a project (programme is prepared as climate finance), even if the approval was done before the project (individual investment is prepared). This refers more to the identification phase. This is another role for an organisation. It means who had the authority to classified the project as "climate finance" investment. This data point will be known by the PEs when they are publishing data in the identification phase.

**Comment by duncandewhurst** [comment]
@EvelynDinora thanks for the clarification.

If I understood correctly, in GCF terms, we're talking about the 'implicit' approval of an NDA or focal point choosing to include a project in its country or entity work programme before submitting that work programme to the GCF (step 1 of the process in the issue description).

The GCF describes NDAs and focal points as:

> government institutions that serve as the interface between each country and the Fund. [[Source](https://www.greenclimate.fund/about/partners/nda#)]

The GEF has a similar concept of "operational focal points" described as:

> GEF Operational Focal Point (OFP): means a government official nominated by a GEF Participant (as defined by the Instrument) who acts as the principal contact point for GEF activities in the country. [[Source](https://www.thegef.org/sites/default/files/documents/Project_Program_Cycle_Policy.pdf) (page 3)]

Like GCF NDAs and focal points, GEF operational focal points are responsible for endorsing project proposals before they are submitted to the GEF: 

> GEF Operational Focal Points are responsible for operations of GEF activities within their countries. This includes reviewing and endorsing project proposals to ensure they are in line with national priorities and strategies. [[Source](https://www.thegef.org/who-we-are/organization)]

Based on the above, I propose that we add the following role to the partyRole codelist:

code | title | description
-- | -- | --
climateFinanceFocalPoint | Climate finance focal point | An entity that serves as the interface between the government of the country in which the infrastructure project is located and climate finance funders such as the Green Climate Fund and the Global Environment Facility. The focal point is responsible for identifying and/or endorsing project ideas prior to submission to the climate finance funder.

Does that sound good?

**Comment by EvelynDinora** [comment]
@duncandewhurst Yes, very good!! thanks

**Comment by duncandewhurst** [comment]
Thanks, Evelyn.

@jpmckinney are you happy with the proposal in my previous comment?

**Comment by jpmckinney** [comment]
Do we need "such as the Green Climate Fund and the Global Environment Facility"? We typically don't name specific organizations in descriptions. Otherwise happy with adding the code.

**Comment by duncandewhurst** [comment]
I'm happy to omit that part. A Google search for "climate finance funders" returns Green Climate Fund as the first result, which suggests the term isn't likely to be misinterpreted.
