### ISSUE TITLE
Project preparation period and approval period

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#421]
## Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details> <summary> Project preparation period (preparation) </summary>

## Project preparation period (preparation)

**Module:** Climate finance
**Indicator:** Accessibility/efficiency

### Disclosure format

> Disclose dates for project preparation [start date, end date] 

### OC4IDS mapping

TBC

</details>

<details> <summary> Project approval period (preparation) </summary>

## Project approval period (preparation)

**Module:** Climate finance
**Indicator:** Accessibility

### Disclosure format

> Disclose dates for project approval [submission date, approval date] 

### OC4IDS mapping

TBC

</details>

@evelyndinora, provided the following clarification of the uses cases and meaning of these fields:

> Climate action is needed urgently. But it takes time to prepare a project. What the SG wants to see is the efficiency (or inefficiency) in terms of project preparation. Please see below: 
> ![image](https://github.com/open-contracting/infrastructure/assets/19265814/b01a50b4-12a6-4e6b-95c0-bcfee9d5d154)
> https://www.greenclimate.fund/project/fp209 
>
> This is the date the project was submitted to approval of the Climate Fund and the date the project is approved by the Climate Fund. This is applicable to all available climate funds. Then we can use the start date of a project to measure efficiency in financial flows. 

## Discussion

As discussed in https://github.com/open-contracting/infrastructure/issues/420 and elsewhere, there can be several levels of 'project' and investment at play, e.g.

```mermaid
flowchart TD
  A["Funding source,
  e.g. GCF"]-- "'Parent' investment" -->
  B["Financing party, e.g.
  Development Bank of South Africa"]-- "Investment" -->
  C["Infrastructure
    Project 1"] &  D["Infrastructure
    Project 2"] & E["Infrastructure
    Project 3"]
```

@evelyndinora, @mgraca-prado, my understanding is that the 'project' referred to in the elements proposed in the CoST IDS/OC4IDS review is not the infrastructure project, but the 'parent' investment project (not sure if that is the right term exactly). Is that correct?

**Comment by EvelynDinora** [comment]
Hi @duncandewhurst, 

Yes, both periods are important to know, but for the 'parent' investment project the PE´s don't necessarily know or access to this data. So, the period will be for each individual project contained in the parent investment.   Many thanks.

**Comment by duncandewhurst** [comment]
Thanks, @EvelynDinora. Great, I'm much happier only modelling the periods for the individual infrastructure projects :-)

In which case:

* The preparation period is covered by https://github.com/open-contracting/infrastructure/issues/252
* For the approval period, since approval isn't a project stage in the CoST IDS, I suggest that we model the submission and approval using milestones: https://github.com/open-contracting/infrastructure/issues/253

Sound good?

**Comment by duncandewhurst** [comment]
@EvelynDinora I'm assuming that you're happy with the proposal in my previous update so I'll move this issue to agreed - let me know if not.

**Comment by EvelynDinora** [comment]
Yes, sounds good!
