### ISSUE TITLE
OC4IDS 0.9.4: Pre-release tasks

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#423]
I'm creating this issue to list any final tasks that we'll need to do once the other issues in the 0.9.4 milestone are closed:

From https://github.com/open-contracting/infrastructure/pull/422:

- [x] Update titles and descriptions in `sustainability.yaml` with the final versions from the [CoST IDS sustainability elements spreadsheet](https://docs.google.com/spreadsheets/d/165epI69oQ5YyL4-2q8VubFn9VuNham2Pi1u0P49id9o/edit#gid=0)
- [x] Final copy-edit of mapping and examples in `sustainability.yaml`
- [x] Resolve any outstanding issues reported by `./manage.py lint`
- [x] Check the built version of `schema.md` and update `:collapse:` option of jsonschema directives as needed (probably just for the project table).
- [x] Run `ocdskit schema-strict`
- [x] Check and update ordering of new fields
- [x] Replace `csv-table-no-translate` with `csv-table` for existing mapping tables (#383)

**Comment by duncandewhurst** [comment]
When copy-editing the mappings in `sustainability.yaml` we can reduce repetition of the CoST IDS disclosure formats, e.g. for land compensation budget

```yaml
    disclosure format: Disclose budget allocated to fund land compensation (E.g. \[value\]).
    mapping: 'Project Level: Set `.social.landCompensationBudget` to the amount and currency of the budget allocated for land compensation.'
```

Can be shortened to

```yaml
    disclosure format: Disclose budget allocated to fund land compensation (E.g. \[value\]).
    mapping: 'Project Level: Map to `.social.landCompensationBudget`.'
```

**Comment by odscjen** [comment]
- [x] Remove extra "Open codelists" heading in `codelists.md`

**Comment by duncandewhurst** [comment]
>     * [ ]  Check and update ordering of new fields

I figure it makes sense to review the ordering of all the top-level fields. @jpmckinney please let me know if you're happy with the following ordering:

- 'General' metadata:
  -   `id`
  -   `identifiers`
  -   `updated`
  -   `language`
  -   `title`
  -   `description`
  -   `status`
  -   `locations`
- Type/purpose data:
  -   `type`
  -   `sector`
  -   `purpose`
  -   `policyAlignment`
  -   `benefits`
  -   `social`
  -   `environment`
  -   `additionalClassifications`
- Time-based data:
  -   `period`
  -   `identificationPeriod`
  -   `preparationPeriod`
  -   `implementationPeriod`
  -   `completionPeriod`
  -   `maintenancePeriod`
  -   `decommissioningPeriod`
  -   `assetLifetime`
  -   `milestones`
  -   `forecasts`  
  -   `metrics`
  -   `completion`
- Monetary data:
  -   `budget`
  -   `costMeasurements`
  -   `transactions`
- Organizational data:
  -   `publicAuthority`
  -   `parties`
  -   `lobbyingMeetings`
- References:
  -   `documents`
  -   `contractingProcesses`
  -   `relatedProjects`

**Comment by jpmckinney** [comment]
We can break up the thematic grouping where the field relates to a basic question. Under OCP's upcoming strategy, we're thinking for OC4IDS that the basic questions are "Who built what with whom, for how much, when and where?"

* who: publicAuthority
* built what: title, description
* with whom: I forget if this is only in contracting process data or also in project data
* for how much: budget
* when: period
* and where: locations 

So maybe the listing below (moved fields in bold).

I would not (edit: original text forgot the word "not"!) be opposed to grouping fields that are only used in sustainability modules together at the end (policyAlignment, benefits, social, environment, lobbyingMeetings – can't remember if additionalClassifications is currently only used in modules).

If that's done, then `parties` can be moved up.

- OC4IDS metadata:
  -   `id`
  -   `updated`
  -   `language`
- Cross-referencing:
  -   **`identifiers`** (kept at the top, as fundamental for connecting to other datasets)
- Basic metadata:
  -   **`publicAuthority`**
  -   `title`
  -   `description`
  -   **`budget`**
  -   **`period`**
  -   `locations`
- Workflow data:
  -   **`status`** (swapped position with `locations`)
- Type/purpose data:
  -   `type`
  -   `sector`
  -   `purpose`
- Organizational data:
  -   **`parties`**
- Periods:
  -   **`assetLifetime`** (moved up as this can put the others into context, and describing the asset is often of greater interest than the timelines for individual stages)
  -   `identificationPeriod`
  -   `preparationPeriod`
  -   `implementationPeriod`
  -   `completionPeriod`
  -   `maintenancePeriod`
  -   `decommissioningPeriod`
- Time-based data:
  -   `forecasts`  
  -   `metrics`
  -   **`milestones`** (moved next to completion, as completion is sort of describing a final milestone)
  -   `completion`
- Monetary data:
  -   `costMeasurements`
  -   `transactions`
- References:
  -   `documents`
  -   `contractingProcesses`
  -   `relatedProjects`
- **Sustainability modules:**
  -   `policyAlignment`
  -   `benefits`
  -   `social`
  -   `environment`
  -   `additionalClassifications`
  -   `lobbyingMeetings`

**Comment by duncandewhurst** [comment]
All sounds good to me. `additionalClassifications` is referenced in the 'core' CoST IDS to OC4IDS mapping in the context of sector and purpose so I've moved it to the end of the type/purpose group.
