### ISSUE TITLE
projectSector: New sustainability sector codes

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#424]
# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Sustainable sub-sectors </summary>

## Sustainable sub-sectors

**Module:** Institutional
**Indicator:** Subsectors

### Disclosure format

> Identify relevant sub-sectors related to the project scope. 
Select from a list (non-exhaustive):  
- Renewable energy 
solar, wind,  
hydropower,  
biomass 
geothermal  
Low carbon transport 
- Flood protection 
energy efficiency,  
water and wastewater management 
natural resource management 
Free text to add not mentioned sub-sectors 

### OC4IDS mapping

> Project Level: Add equivalent code from ProjectSector codelist to sector array. 

</details>

# Proposal

Add new codes to the open projectSector codelist to cover additional sustainability sub-sectors.

Add the following codes:
<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-99bc8deb-7fff-27a0-f540-710010ca0dbc">

Codelist | Code | Title | Description
-- | -- | -- | --
projectSector | energy.solar | Solar | Energy the earth receives from the sun in the form of electromagnetic radiation.
  | energy.wind | Wind | Energy obtained by harnessing the movement of the wind.
  | energy.hydropower | Hydropower | Energy generated from falling or running water.
  | energy.biomass | Biomass | Energy contained within living or recently living biological organisms.
  | energy.geothermal | Geothermal | Heat energy harvested directly from the earth.
  | transport.lowCarbon | Low-carbon transportation | Low-carbon sustainable transport, including urban mobility, cycling, air and water vehicles powered by renewable energy sources.
  | naturalResources | Natural resources | The natural resources including forests, land, water and soil. A more detailed breakdown may be provided using the naturalResources.[sub-sector] codes.
  | naturalResources.floodProtection | Flood protection | Flood protection including hard infrastructure such as flood walls and flood gates, and soft infrastructure.

</div>

Update the following existing code descriptions:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-e61835c6-7fff-5ecc-5915-608e41e192bf">

Codelist | Code | Title | Description
-- | -- | -- | --
projectSector | energy | Energy | Energy, including electric power generation, and the transmission and distribution of electricity, oil and gas, for example: power plants, power lines, gas pipelines. A more detailed breakdown may be provided using the energy.[source] codes.

</div>

# Sources

* energy definitions (other than geothermal) [energypedia](https://energypedia.info/wiki/Renewable_Energy_Project_Resource_Center) this resource is linked to via https://ppp.worldbank.org/public-private-partnership/sector/energy 
* geothermal [www.energy.gov](https://www.energy.gov/eere/geothermal/geothermal-basics)
* floodProtection https://en.wikipedia.org/wiki/Flood_control 
* naturalResourceManagement https://en.wikipedia.org/wiki/Natural_resource_management

## Discussion
* @evelyndinora @mgraca-prado Can you provide an example of Energy efficiency infrastructure? In both of these cases I’m struggling to think of what sort of infrastructure project would fall under either of these sector categories. I can think of examples of where energy efficiency would be a factor in the infrastructure project, e.g. retrofitting a school building to make it more energy efficient, but in this example energy efficiency is the project aim but the sector is education.
* Low-carbon transport. There is some unavoidable overlap here with the other transport codes, but some of them already have overlap, e.g. “transport.urban” overlaps with “transport.roads” and as the `sector` object is an array I’m assuming this is okay.

## Notes
* Water and waste water management is already covered in the existing codelist.

cc @evelyndinora @mgraca-prado

**Comment by mgraca-prado** [comment]
@duncandewhurst, I agree with you, we can exclude energy efficiency as a sub-sector

**Comment by odscjen** [comment]
@mgraca-prado @EvelynDinora  @jpmckinney any further objections or clarifications to the proposal or can we move this into the Agreed column?

**Comment by jpmckinney** [comment]
bioenergy -> biomass, otherwise it doesn't match the others (we'd need "solar energy", etc.). From [earlier sector research](https://docs.google.com/spreadsheets/d/17FRnRXaXmsQZusf9_vmlRhRUuA4Fdy2ORIxizABCLRI/edit#gid=1521218815), "Biomass" is the term used by [OECD](https://www.oecd.org/dac/aft/Aid-for-trade-sector-codes.pdf).

I think naturalResourceManagement is typically simply referred to as naturalResources.

floodProtection is a bit odd as a top-level sector. Why not naturalResources.floodProtection?

**Comment by odscjen** [comment]
Agree about bioenergy -> biomass

and agree naturalResourceManagement -> naturalResources

floodProtection is a tricky one. In other databases we looked at as part of the supply side research it appeared as:
* Coastal and riverine infrastructure (including built flood-protection infrastructure) in the [IDB Climate Finance Database](https://publications.iadb.org/en/2021-idb-climate-finance-database), a top level sector of its own
* water - flood defenses in [INFRALATAM](https://www.iadb.org/es/historia/infralatam-you-will-not-find-better-dataand-if-you-do-please-let-us-know) (which appears to be down now annoyingly), so a second level sector under the top level sector Water.
But having said that I think I now agree that it'd fit well under naturalResources

I've updated the proposal accordingly cc @mgraca-prado @evelyndinora

**Comment by odscjen** [comment]
I'm taking Maria's thumbs up to be the okay to move this to Agreed

**Comment by mgraca-prado** [comment]
That is correct Jen @odscjen 

Additionally, a quick question to @odscjen and @duncandewhurst : 
Is there any consolidated page on github that we could see the current modelling? I'm asking because we need to send the report to the WB and I would like to check whether the description of the data points in the report is matching the latest agreed versions.

**Comment by odscjen** [comment]
Thanks Maria :)

@mgraca-prado the [sustainability.yaml](https://github.com/open-contracting/infrastructure/blob/0.9-dev/mapping/sustainability.yaml) doc is probably the best place to find the modelling but it's not fully up-to-date and we're expecting it to being updated a lot over the next 2 weeks. @duncandewhurst unless you've a different thought I don't think there's an alternative place to find all the latest modelling in one location, it's spread across the numerous issues.

**Comment by neelima-j** [comment]
@mgraca-prado The same documentation that @odscjen shared can be seen in a more readable format [in the development copy of the documentation](https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/cost/ids/sustainability/). Its status is as Jen said, and will be updated frequently as issues are worked on.

**Comment by mgraca-prado** [comment]
thanks, this is very helpful, it is just to keep the report aligned
