### ISSUE TITLE
Organization classifications: Geographic scope and high-level sector

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#436]
# Background

I'm breaking this out from #413 so as not to hold up preparing a PR for that issue.

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Accredited Entity Type (preparation)   </summary>

## Accredited Entity Type (preparation) 

**Module:** Climate finance
**Indicator:** Accessibility

### Disclosure format

> Select from the lists: 
> * Private 
> * Public 
> * non-governmental 
> * sub-national 
> * national 
> * regional 
> * international 

### OC4IDS mapping

> TBC

</details>

I've copied the relevant comments from https://github.com/open-contracting/ocds-extensions/issues/207 below.

@duncandewhurst:

> CoST suggested the following classification for financing party type, which we'll need to reconcile with the existing codelist:
> 
> > * Private
> > * Public
> > * non-governmental
> > * sub-national
> > * national
> > * regional
> > * international
> 
> We might consider splitting into separate fields or classifications since the above list mixes two concepts: high-level sector (private, public, non-governmental) and geographic scope (sub-national, national, regional, international).
> 
> @EvelynDinora provided this helpful explanation of the use cases for the classification:
> 
> > the interest of the SG is to see which and what type of entity is facilitating the investments in climate finance projects in the country. The experience tells that major entities such multilateral banks are obtaining funds against national entities. The issue is that major entities are extremely burocratic and the transactional costs are higher than the national entities who can speed up the investments at lower costs (again aggregated data is the main interest but this collected project per project).

@jpmckinney:

> Agree on splitting out geographic scope, etc. These would be classifications on the organization entry in the `parties` array?

@duncandewhurst:

> Yes, I think that makes sense.
> 
> In [#207 (comment)](https://github.com/open-contracting/ocds-extensions/issues/207#issuecomment-1765456721), I was concerned that the details of the actual organisation might not be known/disclosable, but the CoST IDS/OC4IDS review proposes an element for that.

# Discussion

@jpmckinney a couple of questions:

1. Was your suggestion to model this using the [OCDS organization classification extension](https://extensions.open-contracting.org/en/extensions/organizationClassification/1.1/)?
2. If so, are you happy with the `scheme` values below? (If you have a suggestion for a better name for the private/public/non-governmental classification that would be very welcome)

```json
{
  "parties": [
    {
      "details": {
        "classifications": [
          {
            "id": "private",
            "scheme": "COST_IDS_SECTOR"
          },
          {
            "id": "national",
            "scheme": "COST_IDS_GEOGRAPHIC_SCOPE"
          }
        ]
      }
    }
  ]
}
```

cc @evelyndinora @mgraca-prado

**Comment by jpmckinney** [comment]
> Was your suggestion to model this using the [OCDS organization classification extension](https://extensions.open-contracting.org/en/extensions/organizationClassification/1.1/)?

I don't remember, but it sounds good – unless you have a better suggestion.

> If you have a suggestion for a better name for the private/public/non-governmental classification that would be very welcome

TED had a `CA_TYPE` (contracting authority type) XML element, and eForms has Buyer Legal Type field and [codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/buyer-legal-type). So perhaps something like costIdsLegalType.

(In TED, we used all-caps, because the XML elements are all-caps. In general, we can use camelCase.)

> If so, are you happy with the scheme values below?

I think for geographic scope, the usual terminology is [administrative level](https://en.wikipedia.org/wiki/Administrative_division), so costIdsAdministrativeLevel.

**Comment by duncandewhurst** [comment]
Thanks! That all sounds good to me. I'll move this to agreed on the project board.
