### ISSUE TITLE
./manage.py pre-commit removes sustainability example

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#453]
I added it back manually for now.

**Comment by duncandewhurst** [comment]
Fixed in https://github.com/open-contracting/infrastructure/pull/443/commits/b415f8058c8bb5a8bc48bf3cbc5497885f7dbddf and https://github.com/open-contracting/infrastructure/pull/443/commits/3aa0037ed8c34de404d11e7492ffa0105e133a9d
