### ISSUE TITLE
environmental measures: new object and codelist

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#471]
# Background

The new Environment Module included the data point Environmental Measures:

"Disclose the measures adopted by the project to mitigate and/or remedy the environmental impact (E.g. [free text justification/explaining the measures adopted] and document)."

This has been mapped to `document`. A new draft of the data point suggests updating it to the following:

Environmental measures: Identify the measures adopted by the project to mitigate and/or remedy the environmental impact, disclosing the corresponding document that describes the project’s environmental measures. This can include, without limitation, the following:

* waste management
* disposal of construction by-products
* pollution reduction (including noise and dust)
* environmentally responsible sourcing of materials
* environmentally responsible use of land, water and air
* water contamination management
* use of recycled and reused materials
* others (explain)

Other similar data points, e.g. Conservation measures, Climate measures, have been modelled as new objects of the format:

```json
{
  "type": [array from codelist],
  "description": "free-text"
}
```
We could leave the modelling as it is and add a line to the mapping to use `document.description` to record the list items. Or we could create a new object and codelist in a similar manner to https://github.com/open-contracting/infrastructure/issues/402.

@jpmckinney do you have any thoughts? Leaving it as it is and using the `document.description` field would be simpiler but adding the new object would be more consistent.

**Comment by jpmckinney** [comment]
I don't have a strong opinion. If publishers have structured data that can be modelled as an array of codes, then we might as well add it.

**Comment by odscjen** [comment]
# Proposal

Create a `environmentalMeasure` object comprising a `type` and `description`. An array of these measures will be created as `environmentalMeasures` within the `environment` object. `environmentalMeasure.type` will take from an open codelist, environmentalMeasures.

Add the following fields and objects:

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
environment.environmentalMeasures | Environmental measures | The measures adopted by the project to mitigate and/or remedy environmental impacts. | array of `EnvironmentalMeasures` objects | -
EnvironmentalMeasure | Environmental measure | A measure adopted by the project to mitigate and/or remedy environmental impacts. | object |  
EnvironmentalMeasure.type | Type | The type of environmental measure, using the open environmentalMeasures codelist. | string | environmentalMeasures
EnvironmentalMeasure.description | Description | A short description of the environmental measure. |   |  

</div>

Add the following codes:

Codelist | Code | Title | Description
-- | -- | -- | --
environmentalMeasures | wasteManagement | Waste management | Measures that avoid, reduce, recycle and reuse waste generated as a direct result of the project. When waste is produced it shall be treated, destroyed or disposed of in a safe and environmentally sound manner.
environmentalMeasures | constructionWasteDisposal | Disposal of construction by-products | Measures that avoid, reduce, recycle and reuse construction by-products generated as a direct result of the project. When construction by-products are produced they shall be treated, destroyed or disposed of in a safe and environmentally sound manner.
environmentalMeasures | materialSourcing | Environmentally responsible sourcing of materials | Measures that ensure all project materials are sourced in an environmentally sustainable manner. For example, by following internationally recognised standards such as the Leadership in Energy and Environmental Design's (LEED) for building materials or the Forest Stewardship Council's (FSC) for wood.
environmentalMeasures | responsibleUseNaturalResources | Environmentally responsible use of land, water and air | Measures that ensure the sustainable and environmentally responsible use of land, water and air by the project.
environmentalMeasures | waterContaminationManagement | Water contamination management | Measures that apply pollution prevention techniques to monitor and treat or recycle wastewater discharge in order to avoid pollution harmful to human health and the surrounding environment.

</div>

# Example

```json

{ 
 "environment": { 
   "environmentalMeasures": [ 
 	{ 
   	"type": "wasteManagement", 
   	"description": "Waste management measures for the project include..." 
 	} 
   ] 
 }
} 

```
@mgraca-prado 2 of the bullet points you've suggested to add to the new Environmental measures data point are used in the Climate measures and Conservation measures data points so I've copied over the definitions from those as they seem to be sufficient for the purpose of this codelist as well.

@mgraca-prado, @jpmckinney, @EvelynDinora are these code descriptions ok?

# Sources
* wasteManagement primarily from SuRE E3.5
* constructionWasteDisposal primarily adapted from wasteManagement definition already created
* materialSourcing primarily from SuRE E3.3
* waterContaminationManagement from SuRE E4.2

**Comment by odscjen** [comment]
Relevant points from [SuRe - Standard for Sustainable and resilient infrastructure](https://sure-standard.org/wp-content/uploads/2021/07/ST01_Normative_Standard_v2.0_clean.pdf) Theme E3: Resource Management
* Criterion E3.5 Waste management 
> "The Project shall avoid, minimise, recycle (e.g. through relevant co- and by-products) and reuse waste as much as possible. When waste is generated, it shall be treated, destroyed, or disposed of in a safe and environmentally sound manner. The Project shall avoid the generation of hazardous waste; where creation of hazardous waste is unavoidable, the hazardous waste shall be disposed of safely and following local law and international good practice. A waste management plan shall be implemented throughout the Project’s life cycle. The project shall take specific measures to ensure that sensitive receptors, such as children, are not exposed to waste that is hazardous to their health. The Project shall refer to the World Bank Group (WBG) Environmental, Health, and Safety (EHS) Guidelines or other internationally recognized sources under local and international limits (whichever is more stringent) when evaluating and selecting waste management techniques for the Project. If less stringent levels or measures than those provided in the WBG EHS Guidelines are used, complete disclosure and justification for any proposed alternatives is required."
* Criterion E3.3 Responsible sourcing of materials 
 > "The Project shall commit to the sustainable sourcing of materials and major equipment (through an accountable and transparent procurement process) in order to minimise their life cycle impact in accordance with internationally recognised standards such as Leadership in Energy and Environmental Design (LEED’s)
requirements on building materials and material-specific standards such as Forest Stewardship Council (FSC) for wood."
* Criterion E3.2 Water Efficiency 
 > "The Project shall implement practices and use technology that allows for sustainable and efficient use of water resources. The Project shall reduce potable and non-replenishable water consumption, opting for the usage of treated/recycled water, Grey Water and storm-water to meet water needs. The Project shall minimize unintentional water losses."

From theme E4: Pollution
* Criterion E 4.2 Water Pollution
> The Project shall apply technically and Financially Feasible Pollution prevention techniques to monitor and treat or recycle wastewater discharge in order to avoid Pollution harmful to human health and the surrounding environment, taking into account the specific needs of sensitive receptors and vulnerable groups.

**Comment by odscjen** [comment]
Relevant points from [IFC Performance Standards](https://www.ifc.org/content/dam/ifc/doc/2010/2012-ifc-performance-standards-en.pdf)
3: Resource Efficiency and Pollution Prevention
Water Consumption: 
>9. When the project is a potentially significant consumer of water, in addition to applying the resource efficiency requirements of this Performance Standard, the client shall adopt measures that avoid or reduce water usage so that the project’s water consumption does not have significant adverse impacts on others. These measures include, but are not limited to, the use of additional technically feasible water conservation measures within the client’s operations, the use of alternative
water supplies, water consumption offsets to reduce total demand for water resources to within the available supply, and evaluation of alternative project locations.

Hazardous Materials Management: 
>13. The client will avoid or, when avoidance is not possible, minimize and control the release of hazardous materials. In this context, the production, transportation, handling, storage, and use of hazardous materials for project activities should be assessed. The client will consider less hazardous substitutes where hazardous materials are intended to be used in manufacturing processes or other operations. The client will avoid the manufacture, trade, and use of chemicals and hazardous materials subject to international bans or phase-outs due to their high toxicity to living organisms,
environmental persistence, potential for bioaccumulation, or potential for depletion of the ozone layer.

**Comment by odscjen** [comment]
Relevant points from the [IFC EHS General Guidelines Waste Management](https://www.ifc.org/content/dam/ifc/doc/2000/2007-general-ehs-guidelines-waste-management-en.pdf)
 > Waste management should be addressed through a Waste management system that addresses issues linked to waste minimization, generation, transport, disposal, and monitoring.

[IFC EHS General Guidelines Wastewater Management](https://www.ifc.org/content/dam/ifc/doc/2000/2007-general-ehs-guidelines-wastewater-and-ambient-water-quality-en.pdf)
> Wastewater management includes water conservation, wastewater treatment, stormwater management, and wastewater
and water quality monitoring.

**Comment by odscjen** [comment]
Relevant points from the [World Bank ESF ESS3 Resource Efficiency and Pollution Prevention Management](https://thedocs.worldbank.org/en/doc/837721522762050108-0290022018/original/ESFFramework.pdf#page=53&zoom=80)
> The Borrower will implement technically and financially feasible measures for improving efficient consumption of energy, water and raw materials, as well as other resources Such measures will integrate the principles of cleaner production into product design and production processes to conserve raw materials, energy and water, as well as other resources.

>  the Borrower will adopt measures, to the extent technically and financially feasible, that avoid or minimize water usage so that the project’s water use does not have significant adverse impacts on communities, other users and the environment These measures include, but are not limited to, the use of additional technically feasible water conservation measures within the Borrower’s operations, the use of alternative water supplies, water consumption offsets to maintain total demand for water resources within the available supply, and evaluation of alternative project locations.

> The Borrower will avoid the generation of hazardous and nonhazardous waste 15 Where waste generation cannot be avoided, the Borrower will minimize the generation of waste, and reuse, recycle and recover waste in a manner that is safe for human health and the environment Where waste cannot be reused, recycled or recovered, the Borrower will treat, destroy, or dispose of it in an environmentally sound and safe manner that includes the appropriate control of emissions and residues resulting from the handling and processing of the waste material.

**Comment by odscjen** [comment]
Relevant points from the [ENVISION Framework v 3.9.7](https://sustainableinfrastructure.org/wp-content/uploads/EnvisionV3.9.7.2018.pdf)
RA1.1 Support Sustainable Procurement Practices
> The program includes a well-defined process for selecting suppliers and/or manufacturers of materials, supplies, and equipment, including selection criteria focused on environmental practices and social responsibility.

RA1.3 Reduce Operational Waste
> Develop an operational waste management plan that, at a minimum, identifies the materials to be diverted from disposal and whether the materials will be sorted on site or commingled.

RA1.4 Reduce Construction Waste
>  Implement a construction waste management plan that, at a minimum, identifies the materials to be diverted from disposal and whether the materials will be sorted on site or commingled.
> Project teams can improve performance by considering the ability of waste generated during construction to be recycled or beneficially reused, implementing waste management plans to capture waste, and identifying possible recycling centers with appropriate capabilities.
> Material sent to landfills for use as cover is still being disposed of in landfills and therefore does not meet the spirit or intent of this credit. If material is sent to a recycling facility, project teams should consider whether the facility is certified for meeting
acceptable recycling rates. Waste deemed hazardous should not be included in the total waste calculations and should be disposed of according to local, state/provincial, and federal law.

**Comment by mgraca-prado** [comment]
@odscjen, all good to me. Should we then remove pollution reduction and use of recycled and reused materials from the list?

**Comment by odscjen** [comment]
@mgraca-prado my worry is that it could be confusing to publishers if they're given the option to record the same thing in 2 different places. So yes, I'd recommend removing the duplicates from this list.

**Comment by mgraca-prado** [comment]
@odscjen: Agreed Jen!

**Comment by odscjen** [comment]
Great, I'll edit the proposal above to remove them

**Comment by odscjen** [comment]
@jpmckinney gentle prod, have you a chance to review [these definitions](https://github.com/open-contracting/infrastructure/issues/471#issuecomment-1916415960) before I submit a PR for them?

**Comment by jpmckinney** [comment]
Just a few notes:

* Instead of and/or just use "or"
* environmentalMeasures codelist should be environmentalMeasure singular
* The existing climateMeasures should be singular as well
* responsibleUseNaturalResources -> naturalResourceUse (we don't repeat responsible for the others from the title)
* shall -> ought to
* are produced -> append comma
* For example, ... -> For example, Leadership in Energy and Environmental Design (LEED) standards for building materials or Forest Stewardship Council (FSC) standards for wood.
