### ISSUE TITLE
conservationMeasure: add new codes to cover air and water management

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#474]
The IDS data element is being updated to replace:

" soil management" with "land, water and air management" as one of the list of disclosure elements. This data point is mapped to the `environment.conservationMeasure` object which uses the `conservationMeasure.csv` codelist.

The `conservationMeasure` codelist will either need to replace `soilManagement` with a single new code for "land, water and air management" or add two new codes, e.g. `waterManagement` and `airManagement`. Previous research into codes is in https://github.com/open-contracting/infrastructure/issues/401. Taking from that research it would be more appropriate to split this new IDS option into 3 codes. So propose adding 2 new codes:

Codelist | Code | Title | Description
-- | -- | -- | --
conservationMeasure | airManagement | Air management | Measures that reduce air pollutant emissions to within specified guidelines. For example, the World Health Organization (WHO) Air Quality Guidelines.
conservationMeasure | waterManagement | Water management | Measures that ensure water extracted and used by the project is withdrawn responsibly and in a manner that does not cause negative impacts on the quality or quantity available at the source.

Both codes largely drawn from [SuRe - Standard for Sustainable and resilient infrastructure](https://sure-standard.org/wp-content/uploads/2021/07/ST01_Normative_Standard_v2.0_clean.pdf), particularly:
* Criterion E4.1 Air and Soil Pollution (PC) "The Project shall maintain air pollutant emissions below those specified by: applicable local regulations or guidelines; the World Health Organization (WHO) Air Quality Guidelines; and those specified within the World Bank Group (WBG) Environmental, Health, and Safety (EHS) Guidelines; whichever is more stringent" (E4.1 A.4 pg 136)
* Criterion E3.1 Responsible Sourcing of Water (MC) " The Project shall ensure that water extracted and used for the needs of the Project is withdrawn responsibly and in a manner that maintains Environmental Flows, minimises drawdown of aquifers or does not cause other significant negative impacts on the quality or quantity of water available at water sources." (E3.1 A.1 pg 125)

@mgraca-prado, @jpmckinney any objections?

**Comment by jpmckinney** [comment]
Maybe:

> Measures that **control** air pollutant emissions ~~to within specified guidelines~~. For example, the World Health Organization (WHO) Air Quality Guidelines.

The SuRe wording is about "maintaining below" some threshold, which might very well be above the current emissions. I don't think "to within specified guidelines" is essential to the definition.

In terms of consistency, we can update fugitiveEmissionReduction in climateMeasures to read "greenhouse gas and air pollutant emissions".

> Measures that ensure water is extracted for the project responsibly and in a manner that maintains environmental flows, minimizes aquifer drawdown, or mitigates other potentially negative impacts on the quality or quantity of source water.

The SuRe wording has a strange repetition in "extracted ... withdrawn"; I think the key point is the extraction, not the use – based on the rest of the definition. I'm not sure there's a relevant difference between "extracted for the [needs of the] project" and "the project extracts", but I kept the original.

Otherwise, I think we might as well preserve more of the SuRe wording. I consider "not caus[ing] significant impacts" to be the same as mitigating impacts (i.e. making impacts less significant), to mirror the language of the `social` and `environment` objects.

**Comment by odscjen** [comment]
Great thanks @jpmckinney, those suggested changes look good to me. Also agree an update to 'fugitiveEmissionReduction' makes sense.

@mgraca-prado are you happy with James' suggested edits?

**Comment by mgraca-prado** [comment]
Hi @odscjen,
How would the final language be then?
Air management: Measures that control air pollutant emissions. For example, the World Health Organization (WHO) Air Quality Guidelines.
Water management: Measures that ensure water extracted and used by the project is withdrawn responsibly and in a manner that does not cause negative impacts on the quality or quantity available at the source.
Soil management: ?
Just to be sure soil management is still there right?

**Comment by jpmckinney** [comment]
The proposed wording is:

> Measures that control air pollutant emissions. For example, the World Health Organization (WHO) Air Quality Guidelines.

and

> Measures that ensure water is extracted for the project responsibly and in a manner that maintains environmental flows, minimizes aquifer drawdown, or mitigates other potentially negative impacts on the quality or quantity of source water.

soilManagement is already there and will not change:

> Measures that integrate sustainable soil management practices. For example, the Food and Agriculture Organization's Charter and Sustainable Soil Management Criteria.
