### ISSUE TITLE
Use csv-table-no-translate for i18n.csv

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#477]
All of the strings in the [internationalization lookup table](https://standard.open-contracting.org/staging/infrastructure/0.9-dev/en/guidance/language/#internationalization-lookup-table) appear in the list of strings to be translated in Transifex. However, the field paths in the path column should not be translated and the field titles will be translated as a part of the schema resource.

Since the page on which the table appears is most likely to be read as a part of the English language documentation, I think the simplest solution is to use the csv-table-no-translate directive to exclude the table from translation.

@jpmckinney does that sound good?

**Comment by jpmckinney** [comment]
Hmm, but we'll still have "True", "False" and I'm pretty sure the titles will end up being in English.

I think the approach is the same as with `extract_mappings` in `config.mk`.

**Comment by jpmckinney** [comment]
> most likely to be read as a part of the English language documentation

Good point - we can also just not translate it at all.

**Comment by duncandewhurst** [comment]
Not translating it at all sounds good to me, is that just a case of deleting the resource in Transifex?

**Comment by jpmckinney** [comment]
Yes, that should work along with using csv-table-no-translate as suggested.

**Comment by duncandewhurst** [comment]
Just to confirm - do you mean not translating the whole page (and therefore deleting the language.pot resource)? If so, why does it matter if we use csv-table or csv-table-no-translate?

**Comment by jpmckinney** [comment]
Oh, if we're not translating anything on the page, then just ignore the resource, and you can leave the content as-is.

**Comment by duncandewhurst** [comment]
Okay, I've locked the language.pot resource in Transifex so that the translator doesn't accidentally translate it.
