### ISSUE TITLE
Transifex: Recently added resources do not follow the path--to--file naming convention

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#480]
I noticed this whilst reviewing the [translator instructions](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/translation/using_transifex.html#translator) for seeing where strings appear in context in the documentation.

For example, `implementation.pot` below should be named `guidance--implementation`.

![image](https://github.com/open-contracting/infrastructure/assets/19265814/4c117160-9c37-42bc-8260-cc83bd1dcac2)

The correct name still appears in the resource's URL, e.g.
```
https://app.transifex.com/open-contracting-partnership-1/oc4ids-09/viewstrings/#es/guidance--implementation/478790192
```

I can't see anything that could cause this in the `clean_txconfig` or `update_txconfig` commands in `common.mk` so I think this must be due to a change in an underlying library. @jpmckinney any ideas? If not, I can go through and rename the resources manually in the Transifex web interface.

**Comment by jpmckinney** [comment]
I fixed it in an unreleased version of sphinx-intl (2.2.0) https://github.com/sphinx-doc/sphinx-intl/blob/master/CHANGES.rst

For now, you have to rename new resources in Transifex.

**Comment by duncandewhurst** [comment]
Thanks. I've renamed the resources.
