### ISSUE TITLE
update to policy coherence description, mapping and policyCoherence codelist

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#490]
Minor changes have been requested to the text description of the Policy coherence IDS sustainability element:

IDS element | 0.9-dev current description | new requested description
-- | -- | --
Policy coherence | Disclose documentation that evidences that the project is part of, or aligned with, existing plans and policies, providing further details on the project’s policy alignment. Consider alignment with: -SDGs -National plan or strategy -Infrastructure plan or strategy -Sector plan or strategy -Procuring entity plan or strategy -Paris Agreement goals -Nationally Determined Contributions (NDCs) -National Adaptation Plans -Medium-term fiscal frameworks/targets | Disclose documentation that evidences that the project is part of, or aligned with, existing plans and policies, providing further details on the project’s policy alignment. Consider alignment with: -SDGs -National plan or strategy -Infrastructure plan or strategy -Sector plan or strategy -Procuring entity plan or strategy -Paris Agreement goals -Nationally Determined Contributions (NDCs) -National Adaptation Plans -Medium-term fiscal/**budget** frameworks -**Annual budgets** -**Pipeline of infrastructure projects**

(_this will still be a bullet point list but I couldn't get that to show in the table_)

This will require an update to the associated `policyAlignment` codelist, suggesting the following codes and definitions:

Code | Title | Description
-- | -- | --
annualBudget | Annual budget | The planned expenditure for a financial year.
infrastructureProjectPipeline | Pipeline of infrastructure projects | A list of planned infrastructure projects and programs.

I don't think it's necessary to update the `mediumTermFiscalFramework` code to  `mediumTermFiscalBudgetFrameworks` as the definition already mentions that it's a budget tool.

@mgraca-prado, @EvelynDinora are these definitions okay?

An update to the OC4IDS mapping is also requested if the publisher declares alignment with Fiscal/budget frameworks and annual budgets. 
> 4. For Fiscal/budget frameworks and annual budgets, add the budgetary line to which the project belongs.

The existing mapping starts:

> 1. For each plan or policy to which the project is aligned, add a code from the open `policyAlignment` codelist to the `policyAlignment.policies` array and add a further explanation of the alignment to `policyAlignment.description`.

I can see 2 obvious ways the asked for update could be achieved that don't require updating the schema:
1. Add the budget line(s) of the medium-term fiscal/budget frameworks and/or annual budgets the project aligns with to the `policyAlignment.description`. 

Or

2. Get the `BudgetBreakdowns` object in the budget breakdowns' `.budgetBreakdown`array whose `.description` is "Policy alignment". If none exists yet, add a `BudgetBreakdown` object to the budget breakdowns' `.budgetBreakdown` array, set the `.id` incrementally and set it's `.description` to "Policy alignment". add the budget line to `.description`.  For each medium-term fiscal/budget framework and/or annual budget the project is aligned with a) add a `BudgetBreakdown` object to the budget breakdowns' `.budgetBreakdown` array, set it's `id` incrementally and set its `.description` to the budget line to which the project belongs. b) Get the `Organization` in `parties` whose budget the line is from. If none exists yet, add an organization and add 'funder' to its `.roles`. c) Set the budget breakdown's `.sourceParty` to the `.id` and `name` of the budget source.

The IDS element specifies that documentation is supposed to be disclosed so I'm assuming that the details of who the budget line belongs to will be provided as part of that.

The downside is to option 1 is this information is then slightly hidden within the string of text. The downside to option 2 is that while the information is more structured this way it's possibly a bit over complex (it's based on the mapping for the "Funding source for preparation, implementation and maintenance" element), but it does at least mean that all budget related information is kept in the same place, `budget`.

@duncandewhurst @jpmckinney any thoughts or preferences on the updated mapping? My preference is for option 2.

**Comment by duncandewhurst** [comment]
Neither annual budgets nor infrastructure pipelines seem like policies to me so it would be good to hear some feedback from @mgraca-prado on the rationale for including those concepts under the policy coherence element.

As I understand it:

1. A government's budget is a tool it uses to implement its policies. For example, to deliver on its commitments under the Paris Agreement, a government can use its budget to allocate funds to projects related to climate change mitigation and adaptation.
2. An infrastructure pipeline is a national list of planned or projected projects and investments, which is gathered by asking government agencies and, sometimes, private sector organisations, about their planned projects and investments. For example, the UK's [National Infrastructure and Construction Pipeline 2023](https://www.gov.uk/government/publications/national-infrastructure-and-construction-pipeline-2023) gathers information from both public and private sources. Adding infrastructure pipelines to the policy coherence seems akin to disclosing 'this project appears on that list', which feels a bit backwards as the (plan for a) project exists before it is added to the pipeline.

Regarding linking to the 'budgetary line', the economic and fiscal module already includes a [funding source](https://standard.open-contracting.org/infrastructure/latest/en/cost/ids/sustainability/#economic-and-fiscal-funding-source-for-preparation-implementation-and-operation) element. Presently, that is about disclosing the organizations that provide the funding for the project, but it could be expanded to include identifying the budget line from which funding is drawn. That would be in keeping with the [integration example](https://github.com/open-contracting-extensions/ocds_budget_and_spend_extension/blob/master/examples/integration.md) from the OCDS budget and spending classification extension, which maps an identifier for the budget line to `BudgetBreakdown.id`. That extension also adds a `BudgetBreakdown.classification` object for disclosing the budget line in a structured way, but I'm not sure that's needed in OC4IDS. The publication policy can explain how to look up budget line identifiers, if needed.

**Comment by jpmckinney** [comment]
In some countries, like Canada, policies are first published and announced in the budget. So it is definitely a policy document here. Members of Parliament vote on the budget not in terms of their confidence in its fiscal soundness but moreso in terms of their support of its policies.

The code description probably needs to draw out its policy content more.

**Comment by mgraca-prado** [comment]
Hi all,

The rationale for including these additional 'layers' (budgets and pipelines) was to connect currently unlinked systems: budgetary approval systems and procurement systems.

Take Brazil as an example. Federal projects are first approved under the budgetary system (Painel do Orçamento Federal), where large funds are allocated to policy infrastructure programs. Then, three different systems follow the money: Transferegov (tracks budgetary approvals for specific projects), Comprasgov (the procurement portal), and Obrasgov (an infrastructure-specific system). Different reference numbers are used in each system, so requesting alignment information may make it possible to track this flow.

Although this is a budgetary issue, we placed it under policy coherence to consolidate the matter and avoid its dispersion—a challenge highlighted by experts in the interviews and illustrated by the Brazilian example. This approach would help to demonstrate the coherence in the approval process. Since the budgetary system approval and pipelines should be connected to policy programs, it becomes a policy matter as well. Does this make sense?

@duncandewhurst  @odscjen @jpmckinney @EvelynDinora

**Comment by odscjen** [comment]
Thanks all, @mgraca-prado your explanation makes sense to me, from your and James' comment it seems clear these items do belong here in the policy declaration.

Re @jpmckinney suggestion to draw out the policy element more in the definitions, how about:

Code | Title | Description
-- | -- | --
annualBudget | Annual budget | The planned expenditure for a financial year. **This may detail the policies that the budget will fund.**
infrastructureProjectPipeline | Pipeline of infrastructure projects | A list of planned infrastructure projects and programs. **This may detail the policies each project and program is a part of.**

This still leaves the modelling of the budget details. @duncandewhurst's suggestion appears to be that the requested change is made to the [funding source](https://standard.open-contracting.org/infrastructure/latest/en/cost/ids/sustainability/#economic-and-fiscal-funding-source-for-preparation-implementation-and-operation) element rather than the [policy coherence](https://standard.open-contracting.org/infrastructure/latest/en/cost/ids/sustainability/#institutional-policy-coherence) element. So this could look like

IDS element | IDS description
-- | --
Funding source for preparation, implementation and operation | Name the funding organization(s)/sources of funding for Preparation, Implementation and Operation **, and disclose the budget line(s) to which the project belongs**. If the information is not available for any of the stages, select ['funding/budget source not specified'] for the respective stage where the nature of the funding/budget source could not be identified.

With the mapping being updated to:

> 2a) a. Get the [BudgetBreakdown](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#budgetbreakdown) object in the budget breakdowns' [.budgetBreakdown](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#project-schema.json,/definitions/BudgetBreakdowns,budgetBreakdown) array whose [.description](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#project-schema.json,/definitions/BudgetBreakdown,description) is the name of the stage **and whose [.id](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#project-schema.json,/definitions/BudgetBreakdown,id) is the identifier of the budget line**. If none exists yet, add a [BudgetBreakdown](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#budgetbreakdown) object to the budget breakdowns' [.budgetBreakdown](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#project-schema.json,/definitions/BudgetBreakdowns,budgetBreakdown) array, set its [.id](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#project-schema.json,/definitions/BudgetBreakdown,id) **to the budget line identifier** and set its [.description](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#project-schema.json,/definitions/BudgetBreakdown,description) to the name of the stage. *

@mgraca-prado are you okay with the budget line information being requested in the Economic and Fiscal module rather than the Institutional one? My immediate concern is that if a publisher chooses to use the Institutional module but not the Economic and Fiscal one then that element of linking budgets lines and policies docs will be lost in the OCDS data, although it will still be there in the linked docs for people to find. But I'm unsure how likely that is or how much of an issue it would be?

cc @evelynDinora and @jpmckinney for thoughts

**Comment by jpmckinney** [comment]
Slight edit:

> Name the funding organization(s) or funding source(s) for the preparation, implementation and operation stages of the project, and disclose the budget line(s) to which the project belongs. If this information is not available for any of these stages, select ['funding/budget source not specified'] for the respective stage for which the nature of the funding source could not be determined.

That said:

> select ['funding/budget source not specified'] for the respective stage for which the nature of the funding source could not be determined.

What does this mean? What are they selecting from? How is the respective stage indicated? Why is this clause about the nature of the funding source, whereas the previous clause is about the name?

**Comment by odscjen** [comment]
Thanks for this comment, I realise I'd taken this text from the live version of the site but this element has already been updated to clarify this in the development branch! So it should have been

IDS element | IDS description in dev | suggested new description
-- | -- | --
Funding source for preparation, implementation and operation | Name the funding organization(s) / sources of funding for preparation, implementation and maintenance. Maintenance covers any preventative or corrective maintenance and the day-to-day running of the assets. This stage is also called operation. | Name the funding organization(s) **or funding source(s)** for **the** preparation, implementation and maintenance **stages, and disclose the budget line(s) to which the project belongs**. **The m**aintenance **stage** covers any preventative or corrective maintenance and the day-to-day running of the assets; this stage is also called operation.

**Comment by mgraca-prado** [comment]
Hi @odscjen and @EvelynDinora 

It makes sense to keep at in the economic module. I would only suggest a slight edit in the wording to include the word 'infrastructure' below to limit to infrastructure related policies and projects:

Annual budget: The planned expenditure for a financial year. This may detail the **infrastructure** policies **and projects** that the budget will fund.

Pipeline of infrastructure projects: A list of planned infrastructure projects and programs. This may detail the policies each **infrastructure** project and program is a part of.

Also, maybe it would be better to add the part  **"and disclose the budget line(s) to which the project belongs"** on the IDS Budget for preparation, implementation and operation, instead of the funding source. What do you think?

In terms of where to locate these two IDS elements, maybe to ensure a flow of the elements, what about this order so we have project level first, then budgetary level second.

Procurement strategy
Life cycle cost
Life cycle cost calculation methodology
Cost benefit analysis
Value for money
Maintenance plan
Funding source for preparation, implementation and maintenance
Budget for preparation, implementation and maintenance
Annual Budget
Budget projections
Budget shortfall
Pipeline of infrastructure projects

**Comment by odscjen** [comment]
Thanks both.

@mgraca-prado happy to make those language changes to the policy coherence codes. I think though it does make sense to keep the new line in the Funding source element rather than the Budget one as it's about the line identifier which I think makes most sense when it's attached to a source. If it's with the Budget element there's the chance of a publisher stating the budget amount and the budget line but not saying who the funder is, in which case the budget line wouldn't be much use as we wouldn't know whose budget line it was. Hopefully that makes sense.

Regarding the suggested reordering, the "Annual budget" and "Pipeline of infrastructure projects" aren't being suggested as new elements in themselves. They'll be added to the Policy coherence element in the Institutional module as originally requested, it'll just be the sentence about the budget line that we'll add to the Economic and Fiscal module.

**Comment by mgraca-prado** [comment]
Thanks @odscjen , understood now
