### ISSUE TITLE
Variations as OCDS extension

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#5]
Is it anticipated that variations will be added as an OCDS extension, so that, where OCDS is used, `releaseList` can be a simple list of linked releases? And how do these compare, conceptually, to amendments? FYI, EU uses the term 'modifications'.

**Comment by jpmckinney** [comment]
I agree that amendments and variations are distinct concepts.

Similar to CoST IDS, the EU [Form 20 (Modifications)](http://simap.ted.europa.eu/documents/10184/99173/EN_F20.pdf) focuses on a small number of possible modifications: price (value), duration, scope (description, CPV), location. I haven't mapped Form 20, [because it may disappear](http://standard.open-contracting.org/profiles/eu/master/en/F20/), but given that this concept seems to be the same in CoST IDS, there's the possibility of working on a common extension/model (at least for providing the rationale for changes, as the actual changes are likely better expressed as multiple releases with different values).

Regarding your last bullet, I'll keep that discussion in #9.

**Comment by jpmckinney** [comment]
Coming back to this issue based on conversation in #9:

Having `variations` where it is now essentially allows a user to link to a release and annotate it, when they neither control the source of the OCDS data nor want to author a full release as an alternate means of annotation (where they would use a new extension, based on the common practice of describing modifications, as noted above).

I think annotating releases is a general use case, that extends beyond just `variations`. I'm not sure that the pattern of linking to a release and adding annotations alongside is the right way to go. If enough users wanted to add other annotations to releases, it would seem an anti-pattern to continuously grow the number of fields in `ReleaseListEntry`.

Regardless, I note that in CoST, variations aren't tied to releases (CoST has no concept matching releases), and that it ought to be possible to describe variations without requiring OCDS data to link to. As such, it seems inappropriate to have `variations` on `ReleaseListEntry` at all. To allow this data to be disclosed in a context without OCDS data, `variations` should be on `ContractingProcess`.

If it's necessary to preserve a link between variations and releases, we can add fields to `Variation`, so that users can optionally link to the release in which the variation occurred. That seems better than the other way around, in the present schema.

**Comment by jpmckinney** [comment]
Based on how we resolved #9, I now think `variations` should be on `ContractingProcessSummary` (which wasn't an option when I wrote my earlier comment in this issue).

Release IDs are only unique within the context of a contracting process. Do we need to account for a scenario where the `ContractingProcess` has no `releases`, but has `releaseID`'s in `variations` (and that matching OCDS releases do exist elsewhere)? If so, we might want to consider an `ocid` field to `ContractingProcess`.

As mentioned, this information is similar to the EU's [Form 20 – Modification notice](http://simap.ted.europa.eu/documents/10184/99173/EN_F20.pdf), which has:

* Sections I-VI to identify the contract
* Information about the modification
  * Date of dispatch of this notice
  * Description …
  * Reasons …
  * Increase in price
* Information about the individual modifications
  * Main CPV code and Additional CPV code(s)
  * Place of performance
  * Description of the procurement (scope)
  * Duration … (period)
  * Information on value … (price)
  * Name and address of the contractor …

"VII.2.3) Increase in price" seems to repeat "V.2.4) Information on value of the contract/lot/concession" and "VII.1.5) Duration of the contract, framework agreement, dynamic purchasing system or concession", so we're left with Date, Description and Reasons, which are covered by the proposal.

A significant difference is that the EU's modifications are about *contracts*, whereas CoST variations are, as I understand, about *contracting processes*. Is that correct? Either way, I'm not sure there'd be an implication for the modelling here.

In terms of the choice of terms:

* CoST refers to 'price', but I think this is much more frequently referred to as 'value' (in OCDS and elsewhere). If that's correct, then I recommend using 'value' as the codelist code.
* I don't know how frequently 'variations' is used outside CoST or outside infrastructure. We might prefer 'modifications'.
* I don't know if we prefer 'reason', 'reasons' or 'rationale'. In OCDS, 'rationale' is the preferred term.

Noting that we might get inspiration for future variationType codes from Form 20.

**Comment by duncandewhurst** [comment]
> Based on how we resolved #9, I now think `variations` should be on `ContractingProcessSummary` (which wasn't an option when I wrote my earlier comment in this issue).

Agree, that makes sense.

> Release IDs are only unique within the context of a contracting process. Do we need to account for a scenario where the `ContractingProcess` has no `releases`, but has `releaseID`'s in `variations` (and that matching OCDS releases do exist elsewhere)? If so, we might want to consider an `ocid` field to `ContractingProcess`.

I may have misunderstood, but `ContractingProcessSummary` already has an `ocid` field, so I think this scenario is covered.

> As mentioned, this information is similar to the EU's [Form 20 – Modification notice](http://simap.ted.europa.eu/documents/10184/99173/EN_F20.pdf), which has:
> 
>     * Sections I-VI to identify the contract
> 
>     * Information about the modification
>       
>       * Date of dispatch of this notice
>       * Description …
>       * Reasons …
>       * Increase in price
> 
>     * Information about the individual modifications
>       
>       * Main CPV code and Additional CPV code(s)
>       * Place of performance
>       * Description of the procurement (scope)
>       * Duration … (period)
>       * Information on value … (price)
>       * Name and address of the contractor …
> 
> 
> "VII.2.3) Increase in price" seems to repeat "V.2.4) Information on value of the contract/lot/concession" and "VII.1.5) Duration of the contract, framework agreement, dynamic purchasing system or concession", so we're left with Date, Description and Reasons, which are covered by the proposal.

VII.2.3 explicitly states the pre-modification and post-modification values of the contract, with the helpful clarification that the pre-modification value should include any prior modifications.

Whereas the value in V.2.4 appears to relate to the original value of the contract award ("at the time of conclusion of the contract"), so I don't think the information is repeated.

@kindly also suggested that we should consider including more structured information on before/after values, so we could follow the approach and definitions in form F20 and add these fields to `variation`, since it seems this could be helpful for users where variations are identified from a source other than OCDS releases, or where OCDS data exists but a change history is not published or cached.

> A significant difference is that the EU's modifications are about _contracts_, whereas IDS variations are, as I understand, about _contracting processes_. Is that correct? Either way, I'm not sure there'd be an implication for the modelling here.

The variation fields in IDS all fall under the contract implementation phase and based on the draft definitions in guidance note 9 I think they can also be considered variations about contracts (e.g. for price variation: "Difference between the price at contract award and the current projected price"), though as Tim notes above they may exist independently of a formal/legal contract amendment.

I'm not clear whether the latter statement is true for modifications in the EU context, since there doesn't seem to be a separate form for amendments and I don't know what the rules are for what type of change must be disclosed using form F20.

> In terms of the choice of terms:
> 
>     * CoST refers to 'price', but I think this is much more frequently referred to as 'value' (in OCDS and elsewhere). If that's correct, then I recommend using 'value' as the codelist code.

Agree, we should update this.

>     * I don't know how frequently 'variations' is used outside CoST or outside infrastructure. We might prefer 'modifications'.

From some very brief research, both terms seem to be in use for a variety of types of contract, sometimes in the same country or jurisdiction (e.g. UK government has guidance/templates for both terms). A Google search for "contract modification" | "modification of contract" returns approximately 3 times as many results as the equivalent search for "contract variation" so perhaps we should prefer that term?

@evelynDinora, what do you think?

>     * I don't know if we prefer 'reason', 'reasons' or 'rationale'. In OCDS, 'rationale' is the preferred term.

Since both the EU forms and CoST use 'reasons' and since modifications will be a distinct concept from amendments in OCDS (where 'rationale' is used) I prefer to use `reasons` (which will need updating in the schema from 'reason').

**Comment by jpmckinney** [comment]
> I may have misunderstood, but ContractingProcessSummary already has an ocid field, so I think this scenario is covered.

Ah right, I was looking at `ContractingProcess` :) Good catch re: VII.2.3.

`rationale` is used in `Planning.rationale`, `Tender.procurementMethodRationale` and `Amendment.rationale` (which are all distinct from each other), so to me it seems like the preferred generic term we use in cases where a reason/explanation is desired. Is there another reason to prefer `reasons`?

**Comment by duncandewhurst** [comment]
> 'rationale' is used in `Planning.rationale`, `Tender.procurementMethodRationale` and `Amendment.rationale` (which are all distinct from each other), so to me it seems like the preferred generic term we use in cases where a reason/explanation is desired. Is there another reason to prefer `reasons`?

Only that both CoST and the EU forms use it (the two key use cases for this extension), however let's assume that `rationale` was preferred in OCDS for a reason and go with that.

**Comment by duncandewhurst** [comment]
I've staged these changes in #45, with the exception of renaming 'variation(s)' to 'modification(s)' which I'll wait for feedback from CoST on.

@jpmckinney @kindly I'm open to suggestions on naming for the new fields, I considered: old/new, before/after, former/latter

**Comment by duncandewhurst** [comment]
Noting that Belarus publish the following fields:

* contracts/items/execInfo
* contracts/items/execQuantity
* contracts/items/execValue
* contracts/items/execUnit

Which are described as:

> exec* fields are to report the contract execution. The expected items are first entered in the Contract object. When the contract ends, the actual items are then entered. execInfo contains dates and reason (e.g. non-delivery by supplier, change in plans by procuring entity, etc.).

Depending on whether the changes constitute an amendment or not, this could be mapped to a future variations/modifications extension.

cc @pindec

**Comment by jpmckinney** [comment]
Noting that if we rename variations to modifications in the schema, we'll also need to update the codelist's name (and the heading in the docs).

**Comment by duncandewhurst** [comment]
#45 is merged and the sample data is updated.

Moving this to the beta milestone pending a final decision on renaming variations

**Comment by EvelynDinora** [comment]
We agreed in our last call that we are ok to rename variations as modification according to the EU norm.

**Comment by duncandewhurst** [comment]
thanks @EvelynDinora 

changes staged in https://github.com/open-contracting/infrastructure/pull/74
