### ISSUE TITLE
Global uniqueness of project identifiers

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#58]
The project level schema asks publishers to provide:

> A unique identifier or reference number for this infrastructure project.

Currently there's no further guidance or mechanism to prevent multiple publishers using the same identifier for an infrastructure project.

In OCDS an [ocid prefix](http://standard.open-contracting.org/latest/en/schema/identifiers/#contracting-process-identifier-ocid) is assigned to publishers by the OCDS helpdesk and prepended to existing identifiers for contracting processes to make them globally unique.

Options for ensuring global uniqueness of project identifiers in OC for Infrastructure:

1. Do nothing - risk of identifier clash for infrastructure projects from different publishers

2. Specify an identifier format based on the publisher name/organization identifier - I don't think we should pursue this option for the same [reasons](https://github.com/open-contracting/standard/issues/73#issuecomment-57015793) it was discounted in OCDS

3. Require publishers to request an OCID prefix from the OCDS helpdesk and prepend this to their project identifier - risk of identifier clash if infrastructure projects and contracting processes share an identifier

4. Require publishers to request project identifier prefix from the OCDS helpdesk (i.e. helpdesk maintains a separate list of prefixes for OC for Infrastructure publishers)

5. Require publishers to generate a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) to prepend to their infrastructure project identifiers - this approach is used in the [draft Beneficial Ownership Data Standard](http://standard.openownership.org/en/schema-beta-2/schema/guidance/statement-identifiers.html#strategies-for-identifier-creation).

@jpmckinney @lindseyAM - what do you think?

**Comment by jpmckinney** [comment]
I'd be happy with 4 or 5, with a slight preference for 5. 4 has advantages (i.e. we necessarily learn of any new publishers), but 5 is better longer-term (no need for an authority to manage prefixes).

**Comment by duncandewhurst** [comment]
I discussed this briefly with @ScatteredInk and we noted that if project identifiers are expected to be displayed to an end user in an interface then 5. might not be that aesthetically pleasing (not an issue for BODS)

**Comment by jpmckinney** [comment]
`7483CE73-5C7B-465E-A86D-8E8D6ECB66C3`

`ocds-213czf`

The latter is certainly shorter, though otherwise neither is aesthetically pleasing.

We can go with 4, and then someday offer a tool through which prefixes can be registered. We'd need registration, as we need to compare the generated prefix to existing prefixes, otherwise 4 is not guaranteed to be unique (UUIDs require no such comparison).
