### ISSUE TITLE
Typo: roles is repeated in Organization table

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#6]
https://open-contracting.github.io/infrastructure/projects/reference/#organization

**Comment by timgdavies** [comment]
This seemed to be an issue with the ``jsonschema::`` directive as far as I can see, and occurs [as a result of the latest commit](https://github.com/OpenDataServices/sphinxcontrib-jsonschema/commit/7b696eef47cc14c46a20c67abff18dc794e2f6cc). 

I'll open an issue against that repo to see if we can fix this.

**Comment by jpmckinney** [comment]
I can only see that commit being responsible if you are seeing both "Collapse values don't exist" and "Include values don't exist" during the build – which are errors that should be corrected. Are you seeing either message?

**Comment by Bjwebb** [comment]
I've been reproducing this locally, and I think its this commit that causes the change: https://github.com/OpenDataServices/sphinxcontrib-jsonschema/commit/805612ae0f185b4dbbf304e062eba797c101061f
This also changes how arrays are handled, so looks a likely culprit.

**Comment by timgdavies** [comment]
Thanks @Bjwebb. Flagging to @duncandewhurst that the pinned commit for sphinxcontrib-jsonschema will need updating once the fix is in place, and the docs rebuilt accordingly.

**Comment by Bjwebb** [comment]
Here's the PR that should fix this https://github.com/OpenDataServices/sphinxcontrib-jsonschema/pull/14
