### ISSUE TITLE
Version and language switchers

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#68]
The version and language switchers in the [live version](http://standard.open-contracting.org/infrastructure) are broken.

This isn't an issue right now as there is only one version and one language but we should fix these as part of the beta deploy.

cc @robredpath

**Comment by jpmckinney** [comment]
Let's also add this to the handbook, as I don't think it's documented yet.

**Comment by odscjames** [comment]
Can I get clarification of what versions you are expecting to see in the switcher at the moment? 

Currently it has 2: latest and master

But while http://standard.open-contracting.org/infrastructure/latest/en/ is fine, http://standard.open-contracting.org/infrastructure/master/en/ 404's!

I can see the "switcher" redirects are missing from the Apache conf for this, so there is something to do here to add those like the main site, but is there also something about the entries which is wrong?

**Comment by odscjames** [comment]
I have done this on the dev site - I would like to check some details before putting on live.

**Comment by jpmckinney** [comment]
Can you update the handbook with the changes you had to make?

**Comment by duncandewhurst** [comment]
Thanks @odscjames 

When we deploy the beta, the version switcher should show:

```
Live
   beta (latest)
Development Branches
   master
```
and the language switcher should just show 'English'

**Comment by odscjames** [comment]
Done on live - just docs to do now.

**Comment by odscjames** [comment]
{% set infrastructure_live_versions = ['latest', 'master'] %}

Actually, this should just be latest. Because we want 'master' to be served from the dev server. See #69

(Double check this doesn't break version switcher)

(Call with @duncandewhurst )

**Comment by odscjames** [comment]
Docs merged.

**Comment by odscjames** [comment]
Have updated infrastructure_live_versions
