### ISSUE TITLE
Dev branch access

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#69]
Dev branch builds are currently available at:

http://ocds-standard.dev3.default.opendataservices.uk0.bigv.io/<branch-name>

As part of the beta deploy we should make these accessible at:

http://standard.open-contracting.org/infrastructure/<branch-name>

cc @robredpath

**Comment by odscjames** [comment]
I'm not sure what needs to be done here; we already have a travis deploy file that puts the files on the dev server https://raw.githubusercontent.com/OpenDataServices/opendataservices-deploy/master/open-contracting-infrastructure-deploy.sh and I'm guessing the "Copy the files to the live server" process is used here too? https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/#copy-the-files-to-the-live-server

**Comment by odscjames** [comment]
Ah, ok, so call with @duncandewhurst : We need the Live server to ProxyPass infrastructure branches it doesn't have to the dev server,  like existing site

**Comment by odscjames** [comment]
Done eg http://standard.open-contracting.org/infrastructure/91-new-font/en/ now works

**Comment by duncandewhurst** [comment]
@odscjames I just noticed that visiting a branch (e.g. http://standard.open-contracting.org/infrastructure/master/) results in a directory listing, whereas in the OCDS docs this automatically redirects you to the language subfolder which contains the docs (e.g. http://standard.open-contracting.org/1.1-dev/ leads to http://standard.open-contracting.org/1.1-dev/en/)

Is it much work to replicate that here?

For clarity, when a user enters `http://standard.open-contracting.org/infrastructure/<branch>/` in their browser they should be redirected to `http://standard.open-contracting.org/infrastructure/<branch>/en`

**Comment by ghost** [comment]
@duncandewhurst Sorted!

**Comment by duncandewhurst** [comment]
Brill, thanks james
