### ISSUE TITLE
Manually search index the beta deploy 

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#70]
Currently, new builds must be manually indexed.

See https://github.com/open-contracting-extensions/public-private-partnerships/issues/192

**Comment by jpmckinney** [comment]
Since this is a cross-repo issue, should we just have https://github.com/open-contracting/standard-development-handbook/issues/205 open?

**Comment by duncandewhurst** [comment]
I updated the issue title to reflect what needs to happen for the beta deploy, automatic indexing of branches can be addressed as part of https://github.com/open-contracting/standard-development-handbook/issues/205

**Comment by duncandewhurst** [comment]
@kindly did this as part of the deploy
