### ISSUE TITLE
Documentation updates from the latam training call

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#95]
- [x] add blank OC4IDS JSON file, using https://github.com/open-contracting/json-schema-random
- [x] update title of "using open contracting data to understand infra projects" to "Using data from procurement systems for infrastructure monitoring"
- [x] change the title of "Evaluating disclosures against the Infrastructure Data Standard" to "Assessing compliance with the CoST IDS"
- [x] add an admonition to [what is a project](http://standard.open-contracting.org/infrastructure/latest/en/projects/#what-is-a-project) on different uses of the word 'project' with counter examples to show what we don't mean, i.e. not a national investment project (how 'project' is used in national budget terms), not a large programme of work
- [x] update the diagram and narrative in [what is a project](http://standard.open-contracting.org/infrastructure/latest/en/projects/#what-is-a-project) to use 'contracting process' rather than 'contract'.

**Comment by pindec** [comment]
see pull request #104

**Comment by duncandewhurst** [comment]
Closed by #104

**Comment by jpmckinney** [comment]
I had some review comments (and haven't finished reviewing), for which we'll need a new PR.

**Comment by jpmckinney** [comment]
Re-closed by #106
