### ISSUE TITLE
Clarify where project identifiers should be provided in OCDS data

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#96]
@juanpane flagged that the `planning/budget/projectID` field in OCDS should be used to provide identifiers for national budget projects, not individual infrastructure projects.

We should determine whether the `planning/project/id` field introduced in the [budgets and projects extension](https://github.com/open-contracting-extensions/ocds_budget_projects_extension) would be appropriate or whether a new extension needs to be created.

Once the correct approach is decided we should include guidance in the OC4IDS documentation.

cc @jpmckinney

**Comment by jpmckinney** [comment]
`Budget`:

> This section contains information about the budget line, and associated projects, through which this contracting process is funded. It draws upon data model of the [Fiscal Data Package](https://frictionlessdata.io/specs/fiscal-data-package/), and should be used to cross-reference to more detailed information held using a Budget Data Package, or, where no linked Budget Data Package is available, to provide enough information to allow a user to manually or automatically cross-reference with another published source of budget and project information.

`Budget.projectID`:

> An external identifier for the project that this contracting process forms part of, or is funded via (if applicable). Some organizations maintain a registry of projects, and the data should use the identifier from the relevant registry of projects.

We never explain that there is such a thing as a "budget project" (I'm not entirely clear on what it is), so the present definitions are flexible. That said, it would be odd for a non-budget project to be referenced in the Budget object, unless that project were coterminous with a budget project.

I don't see any problem with `planning/project/id`:

> An externally provided identifier for the project. This might be drawn from a projects register, or may be based on the canonical version of a project name. Project IDs should be unique to a publisher. URIs can be used.

**Comment by duncandewhurst** [comment]
Juan asked that we include this update to the documentation in the 0.9.2 release.

I've drafted an update to the project identifiers guidance in https://github.com/open-contracting/infrastructure/pull/166 based on the discussion above.

@juanpane - please review the updated guidance. You also mentioned an extension to reference the identifier for an investment project. Is that documented somewhere that can be referenced in the OC4IDS guidance?

@jpmckinney - Juan prepared an example showing the three different types of project identifiers (investment project, project in the national budget and infrastructure project) in Paraguay [here](https://docs.google.com/document/d/1V4bsk5GidtLcGAeDJSDVAA_JhN2tMZoabKOkw22PQgI/edit). In that example it seems that whilst the investment project identifier and the identifier for the project in the national budget are different, they actually identify the same thing.

I've also added project identifiers to the [list of worked examples for OCDS 1.1.5](https://docs.google.com/spreadsheets/d/1CclI28-fa2pPIMjckKjexZVkbn5rSgzVi1-1PZ_zsWc/edit#gid=0), because I think this is more relevant to OCDS implementation than OC4IDS implementation.

**Comment by duncandewhurst** [comment]
@juanpane - are you able to review this by the end of next week? We are aiming to get the next release ready before the end of November.

> @juanpane - please review the updated guidance. You also mentioned an extension to reference the identifier for an investment project. Is that documented somewhere that can be referenced in the OC4IDS guidance?
